import createMiddleware from "next-intl/middleware";
import { NextRequest, NextResponse } from "next/server";
import { routing } from "./i18n/routing";
import { STATE_MAP } from "./lib/seo-maps";
import knownSlugsData from "../data/known-destination-slugs.json";

// Build-time snapshot of every destination id in the DB. Regenerated by
// scripts/qa-snapshot-slugs.mjs after seeds change. Used to short-circuit
// unknown-slug requests with a real HTTP 404 — without this, dynamicParams=true
// + ISR caching of notFound() leaves bad slugs serving 200 with the not-found
// body (NEW-2026-05-04-004 / 006).
const KNOWN_DESTINATION_SLUGS: Set<string> = new Set(knownSlugsData.slugs);

const VALID_MONTH_SLUGS: Set<string> = new Set([
  "january", "february", "march", "april", "may", "june",
  "july", "august", "september", "october", "november", "december",
]);

const intlMiddleware = createMiddleware(routing);

// AI + search bot user-agent patterns. Matched case-insensitively against
// the incoming UA. Keep in sync with public/robots.txt allowlist. If the
// list grows, consider moving to a DB-backed table for live edits.
const BOT_PATTERNS: Array<{ name: string; pattern: RegExp }> = [
  { name: "GPTBot", pattern: /GPTBot/i },
  { name: "OAI-SearchBot", pattern: /OAI-SearchBot/i },
  { name: "ChatGPT-User", pattern: /ChatGPT-User/i },
  { name: "PerplexityBot", pattern: /PerplexityBot/i },
  { name: "ClaudeBot", pattern: /ClaudeBot/i },
  { name: "anthropic-ai", pattern: /anthropic-ai/i },
  { name: "Claude-Web", pattern: /Claude-Web/i },
  { name: "Google-Extended", pattern: /Google-Extended/i },
  { name: "Applebot-Extended", pattern: /Applebot-Extended/i },
  // CCBot / Amazonbot / YouBot / PhindBot removed 2026-05-28 — now Disallowed
  // in robots.txt (no-value scrapers). No point spending log-invocations on them.
  { name: "Googlebot", pattern: /Googlebot\/|Googlebot$/i },
  { name: "Bingbot", pattern: /bingbot/i },
  { name: "DuckDuckBot", pattern: /DuckDuckBot/i },
];

function matchBot(ua: string | null): string | null {
  if (!ua) return null;
  for (const b of BOT_PATTERNS) {
    if (b.pattern.test(ua)) return b.name;
  }
  return null;
}

// Fire-and-forget bot-visit logging. Non-blocking, never fails the request.
// 10% sample rate: bot crawls hammer 6k+ pages; full logging burned ~$0.30/day
// in Vercel function invocations. 1-in-10 keeps trend signal intact for the
// /admin/bot-traffic dashboard (multiply by 10 for true volume).
const BOT_LOG_SAMPLE_RATE = 0.1;
function logBotVisit(request: NextRequest, botName: string) {
  if (Math.random() >= BOT_LOG_SAMPLE_RATE) return;
  try {
    const origin = request.nextUrl.origin;
    const body = JSON.stringify({
      bot_name: botName,
      path: request.nextUrl.pathname,
      locale: request.nextUrl.pathname.split("/")[1] || null,
      user_agent: (request.headers.get("user-agent") ?? "").slice(0, 400),
    });
    const secret = process.env.BOT_LOG_SECRET ?? "";
    // Use fetch with keepalive so the request survives middleware return.
    void fetch(`${origin}/api/log-bot-visit`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        ...(secret && { "x-bot-log-secret": secret }),
      },
      body,
      keepalive: true,
    }).catch(() => {
      // swallow — logging failures must never affect bot experience
    });
  } catch {
    // swallow
  }
}

// Wrap next-intl middleware to convert 307 → 301 for locale redirects
// Google treats 307 as temporary — indexes both URLs. 301 consolidates.
export default function middleware(request: NextRequest) {
  // Bot-visit logging (non-blocking). Only HTML routes — skip API/static.
  const ua = request.headers.get("user-agent");
  const bot = matchBot(ua);
  if (bot && !request.nextUrl.pathname.startsWith("/api/")) {
    logBotVisit(request, bot);
  }

  // Destination dedupe 2026-05-28 — `ziro` was a thin duplicate of `ziro-valley`
  // (same Apatani valley, Arunachal). `ziro` had zero destination_months rows so
  // its month pages rendered empty; canonical retained is ziro-valley (tier A,
  // full 12-month scoring, music-festival + paddy POIs). Trek + unique POI were
  // repointed; this 301s every ziro URL (bare or month sub-route) → ziro-valley.
  // Must run BEFORE the known-slug 404 check below, since `ziro` is no longer in
  // the allowlist. `ziro-valley` is safe — the regex stops at `ziro` + `/` or end.
  const ziroMatch = request.nextUrl.pathname.match(
    /^(?:\/(en|hi))?\/destination\/ziro(?:\/([^/]+))?\/?$/,
  );
  if (ziroMatch) {
    const locale = ziroMatch[1] ?? "en";
    const month = ziroMatch[2] ? `/${ziroMatch[2]}` : "";
    return NextResponse.redirect(
      new URL(`/${locale}/destination/ziro-valley${month}`, request.url),
      301,
    );
  }

  // Closes NEW-2026-05-04-004 + NEW-2026-05-04-006 — soft-404 family.
  //
  // /(en|hi)/destination/<slug> with an unknown slug previously hit the
  // dynamic [id] route, ran getDestination() → null → notFound(). Under
  // dynamicParams=true + revalidate ISR caching, Vercel served the not-found
  // response with HTTP 200 instead of 404. Search engines indexed it as
  // duplicate-content; QA flagged it for 9 consecutive days.
  //
  // Fix: check the slug against a build-time snapshot of all known
  // destination ids (apps/web/data/known-destination-slugs.json — 505
  // entries, regenerated by scripts/qa-snapshot-slugs.mjs). Unknown slug →
  // real 404 response from middleware. Same logic for the [month] sub-route:
  // accept only valid month slug names, reject numeric or arbitrary input.
  //
  // STATE_MAP slugs (e.g. /en/destination/rajasthan) deliberately fall
  // through — they get redirected to /state/<id> by the rule below.
  const destSlugMatch = request.nextUrl.pathname.match(
    /^\/(en|hi)\/destination\/([^/]+)(?:\/([^/]+))?\/?$/,
  );
  if (destSlugMatch) {
    const [, , slug, month] = destSlugMatch;
    const isStateRedirect = STATE_MAP[slug] !== undefined;
    if (!isStateRedirect) {
      if (!KNOWN_DESTINATION_SLUGS.has(slug)) {
        return new NextResponse("Not Found", { status: 404, headers: { "content-type": "text/plain; charset=utf-8" } });
      }
      // Month sub-route — only valid named months. Numeric / "marchx" / etc → 404.
      if (month !== undefined && !VALID_MONTH_SLUGS.has(month)) {
        return new NextResponse("Not Found", { status: 404, headers: { "content-type": "text/plain; charset=utf-8" } });
      }
    }
  }

  // Preserve the state-redirect previously handled inside the destination
  // page component. After switching to dynamicParams=false, the page is never
  // invoked for non-destination slugs, so the redirect has to live here.
  //
  // STATE_AND_DESTINATION: slugs that are BOTH a state and a real destination
  // row (city-states / UTs where the city == the state). For these, the
  // destination page wins — skip the redirect or the destination page never
  // renders. Caught after the Delhi eateries section silently disappeared,
  // re-caught 2026-05-17 when /en/state/chandigarh's destination cards
  // silently bounced back to the same state page (same pattern for puducherry).
  const STATE_AND_DESTINATION = new Set(["delhi", "chandigarh", "puducherry"]);

  // Non-locale-prefixed state redirect: /destination/{stateId} → /en/state/{stateId}
  // Without this, the chain is /destination/X → /en/destination/X → /en/state/X (2 hops).
  // Google flags 2-hop chains as "Redirect error". Single hop fixes it.
  const bareDestStateMatch = request.nextUrl.pathname.match(/^\/destination\/([^/]+)\/?$/);
  if (
    bareDestStateMatch &&
    STATE_MAP[bareDestStateMatch[1]] &&
    !STATE_AND_DESTINATION.has(bareDestStateMatch[1])
  ) {
    const stateId = bareDestStateMatch[1];
    return NextResponse.redirect(new URL(`/en/state/${stateId}`, request.url), 301);
  }

  // Locale-prefixed state redirect: /(en|hi)/destination/{stateId} → /{locale}/state/{stateId}
  const destStateMatch = request.nextUrl.pathname.match(/^\/(en|hi)\/destination\/([^/]+)\/?$/);
  if (
    destStateMatch &&
    STATE_MAP[destStateMatch[2]] &&
    !STATE_AND_DESTINATION.has(destStateMatch[2])
  ) {
    const [, locale, stateId] = destStateMatch;
    return NextResponse.redirect(new URL(`/${locale}/state/${stateId}`, request.url), 301);
  }

  // /region/{stateSlug} → /{locale}/state/{stateSlug}. The /region/ route was
  // the legacy path before /state/ became canonical; some states (kerala,
  // tamil-nadu) never had a flat region row so /region/kerala 404s while
  // /region/himachal-pradesh 200s. Consolidate everything to /state/ to kill
  // duplicate-content drift and fix the 404s in one shot. Sub-region IDs
  // (kerala-backwaters, tn-coast etc) aren't in STATE_MAP so they fall through
  // to the existing /region/[id] route as before.
  const regionStateMatch = request.nextUrl.pathname.match(/^\/(en|hi)\/region\/([^/]+)\/?$/);
  if (regionStateMatch && STATE_MAP[regionStateMatch[2]]) {
    const [, locale, stateId] = regionStateMatch;
    return NextResponse.redirect(new URL(`/${locale}/state/${stateId}`, request.url), 301);
  }

  // /(en|hi)/regions → /{locale}/states. The plural index page was orphaned
  // when the region→state route refactor moved /region/{slug} to /state/{slug}
  // and added /states (plural index). /regions never paired with a redirect
  // and now 404s — /states is the consolidated index.
  const regionsIndexMatch = request.nextUrl.pathname.match(/^\/(en|hi)\/regions\/?$/);
  if (regionsIndexMatch) {
    const [, locale] = regionsIndexMatch;
    return NextResponse.redirect(new URL(`/${locale}/states`, request.url), 301);
  }

  // /(en|hi)/region/northeast(/{anything})? → /{locale}/india/northeast.
  // "northeast" isn't a region row (sub-regions only), and isn't a state slug
  // (it's a regional cluster). The /india/northeast page is the existing
  // 8-state NE landing — closest semantic match. Caught from GSC's 2026-04-29
  // Not-found bucket where /hi/region/northeast/june was the residual 404.
  const regionNortheastMatch = request.nextUrl.pathname.match(/^\/(en|hi)\/region\/northeast(?:\/.*)?$/);
  if (regionNortheastMatch) {
    const [, locale] = regionNortheastMatch;
    return NextResponse.redirect(new URL(`/${locale}/india/northeast`, request.url), 301);
  }

  // /(en|hi)/skip-list → /(en|hi)/tourist-traps. The /skip-list/[slug] detail
  // pages still resolve (they're individual trap entries); only the index was
  // missing. Tourist Traps is the editorial home for the same content. Caught
  // 2026-05-06 GSC non-indexing audit (was 404'ing for ~4 GSC URL records and
  // had a broken link from /more).
  const skipListMatch = request.nextUrl.pathname.match(/^\/(en|hi)\/skip-list\/?$/);
  if (skipListMatch) {
    const [, locale] = skipListMatch;
    return NextResponse.redirect(new URL(`/${locale}/tourist-traps`, request.url), 301);
  }

  // Trek dedupe 2026-05-27 — `hampta-pass-trek` was a duplicate of `hampta-pass`
  // (same trek, slug variant). Canonical retained: hampta-pass (longer description,
  // 4-day duration, shorter slug — better for "hampta pass" searches).
  const hamptaMatch = request.nextUrl.pathname.match(/^\/(en|hi)\/treks\/hampta-pass-trek\/?$/);
  if (hamptaMatch) {
    const [, locale] = hamptaMatch;
    return NextResponse.redirect(new URL(`/${locale}/treks/hampta-pass`, request.url), 301);
  }

  // /(en|hi)/vs/kasol-parvati-valley-vs-manikaran → /(en|hi)/vs/kasol-vs-manikaran.
  // Legacy URL refers to a non-existent "kasol-parvati-valley" destination ID;
  // the actual destinations are kasol + parvati-valley + manikaran (separate
  // rows). Google has the legacy URL indexed; redirect to the canonical
  // kasol-vs-manikaran pair so we don't lose the impressions.
  const kasolMatch = request.nextUrl.pathname.match(/^\/(en|hi)\/vs\/kasol-parvati-valley-vs-manikaran\/?$/);
  if (kasolMatch) {
    const [, locale] = kasolMatch;
    return NextResponse.redirect(new URL(`/${locale}/vs/kasol-vs-manikaran`, request.url), 301);
  }

  // GSC 404 cleanup 2026-05-25 — /(en|hi)/region/<state>/<month> URLs
  // never had a route (state/month combos render at /state/<state> only,
  // there's no /state/[id]/[month] route). Drop the month and redirect.
  // The bare /region/<state> case is already covered by the rule above.
  const regionMonthMatch = request.nextUrl.pathname.match(
    /^\/(en|hi)\/region\/([^/]+)\/(january|february|march|april|may|june|july|august|september|october|november|december)\/?$/,
  );
  if (regionMonthMatch && STATE_MAP[regionMonthMatch[2]]) {
    const [, locale, stateSlug] = regionMonthMatch;
    return NextResponse.redirect(
      new URL(`/${locale}/state/${stateSlug}`, request.url),
      301,
    );
  }

  // GSC 404 cleanup 2026-05-25 — legacy /where-to-go/<state>-in-<month>
  // URLs (the current route is /where-to-go/<month> only). 301 to the
  // month-only page; state intent is preserved via the listings on that page.
  const whereToGoMatch = request.nextUrl.pathname.match(
    /^\/(en|hi)\/where-to-go\/[a-z-]+-in-(january|february|march|april|may|june|july|august|september|october|november|december)\/?$/,
  );
  if (whereToGoMatch) {
    const [, locale, month] = whereToGoMatch;
    return NextResponse.redirect(
      new URL(`/${locale}/where-to-go/${month}`, request.url),
      301,
    );
  }

  const response = intlMiddleware(request);

  // Convert temporary redirects (307) to permanent (301) for SEO
  if (response.status === 307) {
    const location = response.headers.get("location");
    if (location) {
      return NextResponse.redirect(new URL(location, request.url), 301);
    }
  }

  return response;
}

export const config = {
  // Match all pathnames except static files and API routes
  matcher: ["/((?!api|_next|_vercel|.*\\..*).*)"],
};
