import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { items, month, travelers, budget, tripName } = body;

  if (!items?.length) {
    return NextResponse.json({ error: "No items in trip" }, { status: 400 });
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) return NextResponse.json({ error: "DB not configured" }, { status: 500 });

  const supabase = createClient(url, key);
  const destIds = items.map((i: any) => i.destinationId);

  const { data: dests } = await supabase
    .from("destinations")
    .select(`
      id, name, tagline, difficulty, elevation_m, vehicle_fit, family_stress,
      daily_cost, nearest_airport, nearest_railhead,
      state:states(name),
      confidence_cards(network, emergency, reach, safety_rating)
    `)
    .in("id", destIds);

  if (!dests) return NextResponse.json({ error: "Failed to fetch data" }, { status: 500 });

  const MONTH_NAMES = ["","January","February","March","April","May","June","July","August","September","October","November","December"];

  // Build a clean text export (printable/shareable)
  let text = `═══════════════════════════════════════════\n`;
  text += `  ${tripName || "My Trip"}\n`;
  text += `  ${MONTH_NAMES[month]} · ${travelers} travelers · ${budget}\n`;
  text += `═══════════════════════════════════════════\n\n`;

  let totalCost = 0;
  let totalDays = 0;

  items.forEach((item: any, idx: number) => {
    const dest = dests.find((d) => d.id === item.destinationId);
    if (!dest) return;

    const stateName = Array.isArray(dest.state) ? dest.state[0]?.name : (dest.state as any)?.name;
    const cc = Array.isArray(dest.confidence_cards) ? dest.confidence_cards[0] : dest.confidence_cards;
    const dayCost = dest.daily_cost?.[budget]?.total ?? 0;
    const stopCost = dayCost * item.days * travelers;
    totalCost += stopCost;
    totalDays += item.days;

    text += `━━━ STOP ${idx + 1}: ${dest.name} (${item.days} days) ━━━\n`;
    text += `${stateName} · ${dest.difficulty} · ${dest.elevation_m ? dest.elevation_m + 'm' : 'Plains'}\n`;
    text += `${dest.tagline}\n\n`;

    if (dest.vehicle_fit) text += `🚗 Vehicle: ${dest.vehicle_fit}\n`;
    if (dest.family_stress) text += `👨‍👩‍👧 Family: ${dest.family_stress}\n`;

    // Infrastructure
    if (cc) {
      const network = cc.network;
      if (network) {
        const ops = [network.jio && "Jio", network.airtel && "Airtel", network.bsnl && "BSNL"].filter(Boolean);
        text += `📶 Network: ${ops.join(", ") || "Limited"}\n`;
        if (network.note) text += `   ${network.note}\n`;
      }
      if (cc.emergency?.nearest_hospital) text += `🏥 Hospital: ${cc.emergency.nearest_hospital}\n`;
      if (cc.emergency?.ambulance) text += `🚑 Ambulance: ${cc.emergency.ambulance}\n`;
    }

    text += `✈️ Airport: ${dest.nearest_airport || 'N/A'}\n`;
    text += `🚂 Rail: ${dest.nearest_railhead || 'N/A'}\n`;

    if (dayCost) text += `💰 Est. cost: ₹${stopCost.toLocaleString()} (${item.days}d × ${travelers} people × ₹${dayCost.toLocaleString()}/day)\n`;

    if (item.notes) text += `📝 Notes: ${item.notes}\n`;
    text += `\n`;
  });

  text += `═══════════════════════════════════════════\n`;
  text += `  TRIP TOTAL\n`;
  text += `  ${items.length} stops · ${totalDays} days · ${travelers} travelers\n`;
  text += `  Estimated budget: ₹${totalCost.toLocaleString()} (${budget})\n`;
  text += `═══════════════════════════════════════════\n\n`;
  text += `Generated by NakshIQ\n`;
  text += `Data verified: April 2026\n`;

  return new NextResponse(text, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${(tripName || "my-trip").replace(/\s+/g, "-").toLowerCase()}.txt"`,
    },
  });
}
