-- =====================================================
-- Agent A: Panch Kailash (5 Kailashes) + Panch Prayag (5 River Confluences)
-- Generated: 2026-05-27
-- Sources: Wikipedia, Uttarakhand tourism portals, govt sites (pithoragarh.nic.in, hpchamba.nic.in)
-- All rows are ON CONFLICT (id) DO UPDATE — idempotent
-- =====================================================

-- =====================================================
-- PANCH KAILASH: 5 Sacred Peaks
-- =====================================================

-- source: https://en.wikipedia.org/wiki/Adi_Kailash
-- source: https://uttarahikes.com/inner-line-permit-adi-kailash-om-parvat/
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'adi-kailash',
  'Adi Kailash',
  'uttarakhand',
  'Kumaon',
  ST_SetSRID(ST_MakePoint(80.6325, 30.3192), 4326)::geography,
  5945,
  ARRAY['peak', 'pilgrimage']::text[],
  ARRAY['spiritual', 'remote']::text[],
  'hard',
  'Pantnagar',
  'Tanakpur',
  'India''s answer to Mount Kailash, accessible via a 6-day trek.',
  'Adi Kailash (also called Chhota Kailash) sits at 5,945m in the rain shadow of the Himalayas. Hindu tradition holds it as the earthly home of Lord Shiva, and it''s far less crowded than the Tibetan original. The trek via Dharchula passes Om Parvat, a peak whose snow face naturally forms the sacred "Om" symbol. You need an Inner Line Permit (issued in 1–3 days at Dharchula SDM office) because the route runs close to the Tibet border. April to June and September to October offer clear skies. Most trekkers reach Jolingkong Lake (Gauri Kund) at the base and stop there rather than summiting—a spiritual choice rather than a technical one.',
  'budget',
  5,
  6,
  'poor',
  false,
  'Dharchula (basic)',
  'ilp',
  ARRAY['Hindi', 'Kumaoni']::text[],
  ARRAY['pilgrimage', 'restricted-access', 'sacred-peak']::text[],
  ARRAY[4, 5, 6, 9, 10]::int[],
  ARRAY[11, 12, 1, 2, 3]::int[],
  '{
    "hi": {
      "name": "आदि कैलाश",
      "tagline": "भारत का छोटा कैलाश, तिब्बत की सीमा पर एक पवित्र यात्रा।",
      "why_special": "आदि कैलाश को हिंदू परंपरा में भगवान शिव का पृथ्वी पर आवास माना जाता है। यह 5,945 मीटर की ऊंचाई पर स्थित है और धारचूला से एक 6-दिवसीय ट्रेक के माध्यम से पहुंचा जा सकता है। यात्रा में ओम पर्वत भी शामिल है, जिसके बर्फ के चेहरे पर प्राकृतिक रूप से पवित्र \"ॐ\" प्रतीक बनता है।"
    }
  }'::jsonb,
  'Pithoragarh',
  'peak',
  'low',
  8,
  9,
  2,
  true,
  true,
  false,
  'B',
  NULL,
  'jeep',
  'high',
  'ilp',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://en.wikipedia.org/wiki/Kinnaur_Kailash
-- source: https://seekinghimalayas.com/treks/kinner-kailash-parikrama
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'kinner-kailash',
  'Kinner Kailash',
  'himachal-pradesh',
  'Kinnaur',
  ST_SetSRID(ST_MakePoint(78.15, 31.50), 4326)::geography,
  6055,
  ARRAY['peak', 'pilgrimage']::text[],
  ARRAY['spiritual', 'scenic']::text[],
  'hard',
  'Shimla',
  'Rampur',
  'A natural Shivalingam rock on a 6,055m peak with a challenging 5-day parikrama.',
  'Kinner Kailash in Kinnaur district is one of the five sacred Kailashes, revered as the home of Lord Shiva and Goddess Parvati. The peak is famous for a 79-foot vertical rock formation that resembles a Shivalingam (the symbol of Shiva). The full Parikrama (circumambulation) circuit is a serious trek taking 5 days; many trekkers now combine road routes with trekking. The monolithic Shivling sits at 4,800m, visible from Kalpa, which also serves as a base. Summer (June–September) brings clear views and pilgrims; winter snows close the routes.',
  'budget',
  4,
  5,
  'moderate',
  true,
  'Kalpa (basic)',
  'none',
  ARRAY['Hindi', 'Kinnauri']::text[],
  ARRAY['pilgrimage', 'viewpoint', 'parikrama']::text[],
  ARRAY[6, 7, 8, 9]::int[],
  ARRAY[11, 12, 1, 2, 3, 4, 5]::int[],
  '{
    "hi": {
      "name": "किन्नर कैलाश",
      "tagline": "किन्नौर की 6,055 मीटर की पवित्र चोटी पर प्राकृतिक शिवलिंग।",
      "why_special": "किन्नर कैलाश को भगवान शिव और देवी पार्वती का घर माना जाता है। इस चोटी पर 79 फुट ऊंचा एक प्राकृतिक शिवलिंग है जो शिव का प्रतीक माना जाता है। पूरा परिक्रमा पथ 5 दिन का एक कठिन ट्रेक है। मानसून के बाद गर्मियों में आसमान साफ होता है।"
    }
  }'::jsonb,
  'Kinnaur',
  'peak',
  'moderate',
  7,
  8,
  3,
  true,
  true,
  false,
  'B',
  NULL,
  'jeep',
  'high',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://en.wikipedia.org/wiki/Shrikhand_Mahadev
-- source: https://bikatadventures.com/Home/Itinerary/shrikhand-mahadev-trek
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'shrikhand-mahadev',
  'Shrikhand Mahadev',
  'himachal-pradesh',
  'Kullu',
  ST_SetSRID(ST_MakePoint(77.20, 32.10), 4326)::geography,
  5227,
  ARRAY['peak', 'pilgrimage']::text[],
  ARRAY['spiritual', 'demanding']::text[],
  'extreme',
  'Bhuntar',
  'Kullu',
  'One of India''s toughest pilgrim treks: a 5-day ordeal with vertical snow pitches and a 75-foot Shivalingam.',
  'Shrikhard Mahadev (Shrikhand Kailash) in Kullu district is revered as the abode of Lord Shiva and Goddess Parvati. It is consistently ranked among the world''s hardest treks. The 32 km journey from the base village of Jaon includes dense forest, glaciers, and 80-degree ice slopes. The summit holds a 75-foot Shivalingam carved into the rock. Nain Sarovar, a high-altitude lake on the route, is believed to have healing properties. Only the full moon periods in July–August (Shravan Purnima) are considered auspicious; the trek is closed the rest of the year. Fitness is non-negotiable: expect altitude sickness, storms, and exposure.',
  'budget',
  5,
  5,
  'poor',
  false,
  'Banjar (basic)',
  'none',
  ARRAY['Hindi', 'Pahari']::text[],
  ARRAY['pilgrimage', 'viewpoint', 'extreme-trek']::text[],
  ARRAY[7, 8]::int[],
  ARRAY[9, 10, 11, 12, 1, 2, 3, 4, 5, 6]::int[],
  '{
    "hi": {
      "name": "श्रीखंड महादेव",
      "tagline": "भारत के सबसे कठिन ट्रेकों में से एक: 5,227 मीटर पर एक 75 फुट का शिवलिंग।",
      "why_special": "श्रीखंड महादेव को भगवान शिव का आवास माना जाता है। जाऊं गांव से 32 किमी का यह यात्रा घने जंगल, ग्लेशियर और 80 डिग्री की बर्फीली ढलानों से होकर जाती है। केवल जुलाई-अगस्त में श्रावण पूर्णिमा को ही यह ट्रेक खुलता है।"
    }
  }'::jsonb,
  'Kullu',
  'peak',
  'low',
  8,
  9,
  1,
  true,
  false,
  false,
  'A',
  NULL,
  'foot',
  'extreme',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://en.wikipedia.org/wiki/Manimahesh_Kailash_Peak
-- source: https://hpchamba.nic.in/manimahesh-yatra/
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'manimahesh-kailash',
  'Manimahesh Kailash',
  'himachal-pradesh',
  'Chamba',
  ST_SetSRID(ST_MakePoint(77.02, 32.54), 4326)::geography,
  5653,
  ARRAY['peak', 'pilgrimage']::text[],
  ARRAY['spiritual', 'scenic']::text[],
  'hard',
  'Kangra',
  'Palampur',
  'An unclimbed sacred peak above Manimahesh Lake, honored by the annual Janmashtami-to-Radha Ashtami yatra.',
  'Manimahesh Kailash (also called Chamba Kailash) has never been summitted—a status locals attribute to its sacred nature. At 5,653m, it overlooks Manimahesh Lake at 3,950m, where thousands of pilgrims bathe during the annual yatra (August–September, Janmashtami to Radha Ashtami). The 7 km trek from Hadsar to Dhancho takes 6–7 hours and is considered moderate compared to other Kailashes. The Gaddi tribe has shepherded this region for centuries and considers the peak their spiritual anchor. The lake is ringed by steep slopes and feels remote even though the trail is well-trodden during season.',
  'budget',
  2,
  3,
  'moderate',
  true,
  'Bharmour (basic)',
  'none',
  ARRAY['Hindi', 'Gaddi']::text[],
  ARRAY['pilgrimage', 'viewpoint', 'sacred-lake']::text[],
  ARRAY[8, 9]::int[],
  ARRAY[10, 11, 12, 1, 2, 3, 4, 5, 6, 7]::int[],
  '{
    "hi": {
      "name": "मणिमहेश कैलाश",
      "tagline": "कभी नहीं चढ़ी गई एक पवित्र चोटी, मणिमहेश झील के ऊपर 5,653 मीटर पर।",
      "why_special": "मणिमहेश कैलाश को भगवान शिव का आवास माना जाता है। इस चोटी को कभी नहीं चढ़ा गया है, जिसे स्थानीय लोग इसकी पवित्रता का प्रमाण मानते हैं। हर साल जन्माष्टमी से राधा अष्टमी तक लाखों भक्त यहां मणिमहेश झील में स्नान के लिए आते हैं।"
    }
  }'::jsonb,
  'Chamba',
  'peak',
  'moderate',
  6,
  7,
  3,
  true,
  true,
  false,
  'B',
  NULL,
  'jeep',
  'medium',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://pithoragarh.nic.in/kailash-mansarovar-yatra/
-- source: https://himalayan360.com/kailash-mansarovar-yatra-route/
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'mansarovar-kailash',
  'Mount Kailash & Mansarovar',
  'uttarakhand',
  'Kumaon',
  ST_SetSRID(ST_MakePoint(81.31, 31.07), 4326)::geography,
  6638,
  ARRAY['peak', 'temple', 'restricted']::text[],
  ARRAY['spiritual', 'extreme']::text[],
  'extreme',
  'Pantnagar',
  'Tanakpur',
  'The real Mount Kailash (6,638m) and sacred Lake Mansarovar, a 24-day yatra via the Lipulekh Pass.',
  'Mount Kailash in Tibet is Hinduism''s holiest mountain, the home of Lord Shiva himself. Mansarovar Lake at 4,530m sits below it. The shortest Indian route departs Dharchula in Pithoragarh via the newly motorable Lipulekh Pass (5,334m), making a 24-day journey achievable for pilgrims with fitness and acclimatization discipline. The route passes through Gunji and Navidhang (with views of Om Parvat), crosses into Tibet at Lipulekh, and continues to Taklakot for further acclimatization before reaching Mansarovar and the 52 km Kailash Parikrama (including the notorious Dolma La Pass at 5,630m). This is managed entirely by the Indian government; you cannot book independently. Permits from the Ministry of External Affairs are required (demand far exceeds supply). Altitude, cold, and weather are serious hazards.',
  'splurge',
  20,
  24,
  'poor',
  false,
  NULL,
  'pap',
  ARRAY['Hindi', 'Kumaoni']::text[],
  ARRAY['pilgrimage', 'restricted-access', 'viewpoint', 'lake', 'international']::text[],
  ARRAY[5, 6, 8, 9]::int[],
  ARRAY[10, 11, 12, 1, 2, 3, 4, 7]::int[],
  '{
    "hi": {
      "name": "कैलाश और मानसरोवर",
      "tagline": "तिब्बत में भगवान शिव का सबसे पवित्र घर, भारत से लिपुलेख दर्रे होकर 24-दिन की यात्रा।",
      "why_special": "कैलाश को हिंदू धर्म में भगवान शिव का सबसे पवित्र निवास माना जाता है। मानसरोवर झील 4,530 मीटर की ऊंचाई पर इसके नीचे है। धारचूला से लिपुलेख दर्रे के माध्यम से नई मोटरेबल सड़क से यह यात्रा 24 दिन में संभव है, लेकिन भारत सरकार द्वारा पूरी तरह नियंत्रित है।"
    }
  }'::jsonb,
  'Pithoragarh',
  'peak',
  'low',
  9,
  9,
  1,
  false,
  false,
  false,
  'A',
  NULL,
  'foot-jeep',
  'extreme',
  'pap',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- =====================================================
-- PANCH PRAYAG: 5 Sacred River Confluences (Uttarakhand)
-- =====================================================

-- source: https://en.wikipedia.org/wiki/Panch_Prayag
-- source: https://travelvaidya.com/blog/panch-prayag-of-uttarakhand/
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'vishnuprayag',
  'Vishnuprayag',
  'uttarakhand',
  'Garhwal',
  ST_SetSRID(ST_MakePoint(79.5753, 30.5625), 4326)::geography,
  1372,
  ARRAY['confluence', 'pilgrimage']::text[],
  ARRAY['spiritual']::text[],
  'easy',
  'Jolly Grant (Dehradun)',
  'Rishikesh',
  'Where the Alaknanda and Dhauliganga meet: the first of five sacred confluences.',
  'Vishnuprayag marks the confluence of the Alaknanda and Dhauliganga rivers in Chamoli district. This is the highest and first of the Panch Prayag, at 1,372m. The site holds a temple dedicated to Lord Vishnu. Pilgrims bathe at the ghat before proceeding downstream to the other four confluences. The town is small but accessible via the Badrinath highway, which remains open year-round. Combined with nearby Auli (ski resort) and the Chopta trek route, Vishnuprayag fits into larger Garhwal circuits.',
  'budget',
  1,
  1,
  'moderate',
  true,
  'Joshimath (20 km)',
  'none',
  ARRAY['Hindi', 'Garhwali']::text[],
  ARRAY['pilgrimage', 'confluence', 'sacred-site']::text[],
  ARRAY[4, 5, 6, 10]::int[],
  NULL,
  '{
    "hi": {
      "name": "विष्णुप्रयाग",
      "tagline": "अलकनंदा और धौलीगंगा का संगम, पाँच प्रयागों में सबसे ऊँचा।",
      "why_special": "विष्णुप्रयाग चमोली जिले में अलकनंदा और धौलीगंगा नदियों का संगम है। यह 1,372 मीटर की ऊंचाई पर पाँच पवित्र प्रयागों में सबसे पहला है। यहां भगवान विष्णु का एक मंदिर है। बद्रीनाथ राजमार्ग साल भर खुला रहता है।"
    }
  }'::jsonb,
  'Chamoli',
  'confluence',
  'moderate',
  3,
  5,
  3,
  true,
  true,
  true,
  'C',
  NULL,
  'car',
  'low',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://en.wikipedia.org/wiki/Panch_Prayag
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'nandaprayag',
  'Nandaprayag',
  'uttarakhand',
  'Garhwal',
  ST_SetSRID(ST_MakePoint(79.33, 30.36), 4326)::geography,
  1358,
  ARRAY['confluence', 'pilgrimage']::text[],
  ARRAY['spiritual']::text[],
  'easy',
  'Jolly Grant (Dehradun)',
  'Rishikesh',
  'The Alaknanda meets the Nandakini at this second sacred confluence, set in Chamoli district.',
  'Nandaprayag is where the Alaknanda and Nandakini rivers meet at 1,358m, making it the second of the five prayags (in downstream order). A temple dedicated to Goddess Nanda stands at the confluence. The town is small and roadside, accessed via the Badrinath highway. Most pilgrims combine visits to multiple prayags in a single road circuit (70–256 km from Rishikesh depending on the prayag).',
  'budget',
  1,
  1,
  'moderate',
  true,
  'Ghat road temple',
  'none',
  ARRAY['Hindi', 'Garhwali']::text[],
  ARRAY['pilgrimage', 'confluence', 'sacred-site']::text[],
  ARRAY[4, 5, 6, 10]::int[],
  NULL,
  '{
    "hi": {
      "name": "नंदप्रयाग",
      "tagline": "अलकनंदा और नंदाकिनी का संगम, दूसरा पवित्र प्रयाग।",
      "why_special": "नंदप्रयाग में अलकनंदा और नंदाकिनी नदियां 1,358 मीटर की ऊंचाई पर मिलती हैं। यह पाँच प्रयागों में दूसरा है। यहां देवी नंदा का एक मंदिर है। बद्रीनाथ राजमार्ग से आसानी से पहुंचा जा सकता है।"
    }
  }'::jsonb,
  'Chamoli',
  'confluence',
  'moderate',
  3,
  5,
  3,
  true,
  true,
  true,
  'C',
  NULL,
  'car',
  'low',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://en.wikipedia.org/wiki/Panch_Prayag
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'karnaprayag',
  'Karnaprayag',
  'uttarakhand',
  'Garhwal',
  ST_SetSRID(ST_MakePoint(79.15, 30.24), 4326)::geography,
  1050,
  ARRAY['confluence', 'pilgrimage']::text[],
  ARRAY['spiritual']::text[],
  'easy',
  'Jolly Grant (Dehradun)',
  'Rishikesh',
  'The Alaknanda and Pindar rivers converge at this third prayag, honoring the Mahabharata hero Karna.',
  'Karnaprayag sits where the Alaknanda meets the Pindar River at about 1,050m. The site is named after Karna, the tragic hero of the Mahabharata. A temple stands at the confluence ghat. The town straddles the main highway to Auli and the inner Garhwal, making it a natural stop on multi-prayag circuits. The confluence is less crowded than Devprayag (the lowest and most accessible prayag).',
  'budget',
  1,
  1,
  'moderate',
  true,
  'Highway town',
  'none',
  ARRAY['Hindi', 'Garhwali']::text[],
  ARRAY['pilgrimage', 'confluence', 'sacred-site', 'mythology']::text[],
  ARRAY[4, 5, 6, 10]::int[],
  NULL,
  '{
    "hi": {
      "name": "कर्णप्रयाग",
      "tagline": "अलकनंदा और पिंडार का संगम, महाभारत के नायक कर्ण को समर्पित।",
      "why_special": "कर्णप्रयाग में अलकनंदा और पिंडार नदियां मिलती हैं। यह नाम महाभारत के नायक कर्ण के नाम से है। संगम पर एक मंदिर है। यह पाँच प्रयागों में तीसरा है और अन्य स्थलों की तुलना में कम भीड़ है।"
    }
  }'::jsonb,
  'Chamoli',
  'confluence',
  'moderate',
  3,
  5,
  3,
  true,
  true,
  true,
  'C',
  NULL,
  'car',
  'low',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://en.wikipedia.org/wiki/Panch_Prayag
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'rudraprayag',
  'Rudraprayag',
  'uttarakhand',
  'Garhwal',
  ST_SetSRID(ST_MakePoint(78.98, 30.28), 4326)::geography,
  895,
  ARRAY['confluence', 'pilgrimage']::text[],
  ARRAY['spiritual']::text[],
  'easy',
  'Jolly Grant (Dehradun)',
  'Rishikesh',
  'Where the Alaknanda and Mandakini unite at this fourth prayag, known as Shiva''s meeting place.',
  'Rudraprayag is the confluence of the Alaknanda and Mandakini rivers at 895m, the second-lowest of the five prayags. The site is sacred to Lord Shiva. A temple stands at the confluence ghat. The town is a transit hub on the main Badrinath highway and serves pilgrims heading to Kedarnath via the alternate Mandakini route. The town saw a devastating 2013 flash flood, and recovery efforts continue.',
  'budget',
  1,
  1,
  'moderate',
  true,
  'Highway town',
  'none',
  ARRAY['Hindi', 'Garhwali']::text[],
  ARRAY['pilgrimage', 'confluence', 'sacred-site']::text[],
  ARRAY[4, 5, 6, 10]::int[],
  NULL,
  '{
    "hi": {
      "name": "रुद्रप्रयाग",
      "tagline": "अलकनंदा और मंदाकिनी का संगम, भगवान शिव को समर्पित।",
      "why_special": "रुद्रप्रयाग में अलकनंदा और मंदाकिनी नदियां 895 मीटर की ऊंचाई पर मिलती हैं। यह पाँच प्रयागों में चौथा है। संगम पर भगवान शिव को समर्पित एक मंदिर है। यह बद्रीनाथ राजमार्ग पर स्थित है।"
    }
  }'::jsonb,
  'Rudraprayag',
  'confluence',
  'moderate',
  3,
  5,
  3,
  true,
  true,
  true,
  'C',
  NULL,
  'car',
  'low',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- source: https://en.wikipedia.org/wiki/Panch_Prayag
INSERT INTO destinations (
  id, name, state_id, region, coords, elevation_m, type, vibe, difficulty,
  nearest_airport, nearest_railhead, tagline, why_special, budget_tier,
  ideal_duration_min, ideal_duration_max, cell_network, atm_available,
  medical_facility, permit_required, languages_spoken, tags, best_months,
  avoid_months, translations, subregion, place_type, crowd_level, hiddenness,
  remoteness, infrastructure_score, solo_suitable, couple_suitable, biker_suitable,
  content_tier, hero_image_url, vehicle_fit, family_stress, permit_type,
  phase2_fields
) VALUES (
  'devprayag',
  'Devprayag',
  'uttarakhand',
  'Garhwal',
  ST_SetSRID(ST_MakePoint(79.07, 29.97), 4326)::geography,
  340,
  ARRAY['confluence', 'pilgrimage']::text[],
  ARRAY['spiritual']::text[],
  'easy',
  'Jolly Grant (Dehradun)',
  'Rishikesh',
  'The Alaknanda and Bhagirathi become the Ganges here—the holiest of the five confluences.',
  'Devprayag at 340m is the lowest and arguably the most sacred of the five prayags. Here the Alaknanda and Bhagirathi rivers meet to form the River Ganges proper. The confluence is marked by a striking change in water color where the two rivers meet. A 9th-century temple stands at the ghat. Devprayag is the closest prayag to Rishikesh (70 km), making it the most accessible entry point for a multi-prayag circuit. The town sits on the main highway and has guesthouses and ashrams for pilgrims.',
  'budget',
  1,
  1,
  'moderate',
  true,
  'Ghat temple town',
  'none',
  ARRAY['Hindi', 'Garhwali']::text[],
  ARRAY['pilgrimage', 'confluence', 'sacred-site', 'ganga-origin']::text[],
  ARRAY[4, 5, 6, 10]::int[],
  NULL,
  '{
    "hi": {
      "name": "देवप्रयाग",
      "tagline": "अलकनंदा और भागीरथी का संगम, जहाँ गंगा का जन्म होता है।",
      "why_special": "देवप्रयाग 340 मीटर की ऊंचाई पर पाँच प्रयागों में सबसे महत्वपूर्ण है। यहां अलकनंदा और भागीरथी नदियां मिलकर गंगा नदी बनाती हैं। संगम पर 9वीं सदी का एक प्राचीन मंदिर है। यह ऋषिकेश से मात्र 70 किमी दूर है।"
    }
  }'::jsonb,
  'Tehri Garhwal',
  'confluence',
  'high',
  2,
  5,
  3,
  true,
  true,
  true,
  'C',
  NULL,
  'car',
  'low',
  'none',
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, state_id = EXCLUDED.state_id, region = EXCLUDED.region,
  coords = EXCLUDED.coords, elevation_m = EXCLUDED.elevation_m, type = EXCLUDED.type,
  vibe = EXCLUDED.vibe, difficulty = EXCLUDED.difficulty, nearest_airport = EXCLUDED.nearest_airport,
  nearest_railhead = EXCLUDED.nearest_railhead, tagline = EXCLUDED.tagline,
  why_special = EXCLUDED.why_special, budget_tier = EXCLUDED.budget_tier,
  ideal_duration_min = EXCLUDED.ideal_duration_min, ideal_duration_max = EXCLUDED.ideal_duration_max,
  cell_network = EXCLUDED.cell_network, atm_available = EXCLUDED.atm_available,
  medical_facility = EXCLUDED.medical_facility, permit_required = EXCLUDED.permit_required,
  languages_spoken = EXCLUDED.languages_spoken, tags = EXCLUDED.tags,
  best_months = EXCLUDED.best_months, avoid_months = EXCLUDED.avoid_months,
  translations = EXCLUDED.translations, subregion = EXCLUDED.subregion,
  place_type = EXCLUDED.place_type, crowd_level = EXCLUDED.crowd_level,
  hiddenness = EXCLUDED.hiddenness, remoteness = EXCLUDED.remoteness,
  infrastructure_score = EXCLUDED.infrastructure_score, solo_suitable = EXCLUDED.solo_suitable,
  couple_suitable = EXCLUDED.couple_suitable, biker_suitable = EXCLUDED.biker_suitable,
  content_tier = EXCLUDED.content_tier, hero_image_url = EXCLUDED.hero_image_url,
  vehicle_fit = EXCLUDED.vehicle_fit, family_stress = EXCLUDED.family_stress,
  permit_type = EXCLUDED.permit_type, phase2_fields = EXCLUDED.phase2_fields;

-- =====================================================
-- COLLECTIONS: 2 circuit collections
-- =====================================================

-- source: https://www.shivyaatrakailash.in/blog/panch-kailash-five-sacred-peaks
INSERT INTO collections (
  id, name, description, items, tags, content_type, strategy_intro, connector_notes
) VALUES (
  'panch-kailash-circuit',
  'Panch Kailash Circuit',
  'The Five Kailashes: five sacred mountains across India revered as the earthly homes of Lord Shiva. Each offers a different scale of pilgrimage, from the accessible Manimahesh Yatra (August–September) to the extreme Shrikhard Mahadev trek. The summit Mount Kailash in Tibet and its Mansarovar Lake remain the holiest; the others are pathways to the same spiritual goal for those who cannot reach the Tibetan border.',
  '[
    {"destination_id": "mansarovar-kailash", "rank": 1, "note": "The original Mount Kailash in Tibet (6,638m) — most sacred but requires 24-day government-managed yatra."},
    {"destination_id": "adi-kailash", "rank": 2, "note": "Adi Kailash (5,945m) in Uttarakhand — closest to Mansarovar with 6-day trek via Dharchula, inner-line permit required."},
    {"destination_id": "kinner-kailash", "rank": 3, "note": "Kinner Kailash (6,055m) in Kinnaur — 5-day parikrama with natural Shivalingam at 4,800m; accessible June–September."},
    {"destination_id": "shrikhand-mahadev", "rank": 4, "note": "Shrikhard Mahadev (5,227m) in Kullu — India''s hardest pilgrim trek, only open July–August during Shravan Purnima."},
    {"destination_id": "manimahesh-kailash", "rank": 5, "note": "Manimahesh Kailash (5,653m) in Chamba — unclimbed peak with moderate 7 km trek to lake; annual yatra August–September."}
  ]'::jsonb,
  ARRAY['pilgrimage', 'sacred-peaks', 'hard-treks']::text[],
  'circuit',
  'Five sacred mountains, one spiritual goal. These peaks form the Panch Kailash, a circuit of pilgrimage sites revered across Hindu tradition. Start with Manimahesh (August–September, moderate access, annual fair) or Adi Kailash (April–June, inner-line permit, closer to the original Mansarovar). The others demand fitness and acclimatization.',
  'Each Kailash has its own season and accessibility. Manimahesh and Kinner are moderate; Adi Kailash requires permits; Shrikhard Mahadev is among the world''s hardest treks; Mansarovar in Tibet is government-managed. Pilgrims often tackle 2–3 over a lifetime.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, items = EXCLUDED.items,
  tags = EXCLUDED.tags, content_type = EXCLUDED.content_type,
  strategy_intro = EXCLUDED.strategy_intro, connector_notes = EXCLUDED.connector_notes;

-- source: https://en.wikipedia.org/wiki/Panch_Prayag
INSERT INTO collections (
  id, name, description, items, tags, content_type, strategy_intro, connector_notes
) VALUES (
  'panch-prayag-circuit',
  'Panch Prayag Circuit',
  'The Five Confluences: five sacred river mergers in Uttarakhand where the Alaknanda River meets its tributaries and forms the holy Ganges. All five are accessible year-round via the Badrinath highway. Each confluence marks a pilgrimage ghat with temples and offers ritual bathing. Devprayag is the most accessible (70 km from Rishikesh); Vishnuprayag is the highest.',
  '[
    {"destination_id": "vishnuprayag", "rank": 1, "note": "Alaknanda + Dhauliganga at 1,372m — the highest and first of the five; temple dedicated to Vishnu."},
    {"destination_id": "nandaprayag", "rank": 2, "note": "Alaknanda + Nandakini at 1,358m — second confluence; Goddess Nanda temple at the ghat."},
    {"destination_id": "karnaprayag", "rank": 3, "note": "Alaknanda + Pindar at 1,050m — third prayag, named after Mahabharata hero Karna; moderate crowds."},
    {"destination_id": "rudraprayag", "rank": 4, "note": "Alaknanda + Mandakini at 895m — fourth confluence sacred to Shiva; hub for Kedarnath pilgrims."},
    {"destination_id": "devprayag", "rank": 5, "note": "Alaknanda + Bhagirathi at 340m — the holiest, where the Ganges is born; closest to Rishikesh (70 km)."}
  ]'::jsonb,
  ARRAY['pilgrimage', 'river-confluences', 'easy-access']::text[],
  'circuit',
  'Follow the Alaknanda downstream through five sacred confluences. All are on or near the Badrinath highway, accessible year-round. Start at Devprayag (70 km from Rishikesh) or work upstream. Pilgrims often bathe at all five in a single road circuit before visiting Badrinath Temple.',
  'These five sites are the gateway to Garhwal pilgrimage. A road circuit takes 2–3 days by car; bathing at each ghat is the core ritual. Best months: April–June and September–October (clear skies). Devprayag is the most famous (Ganga birth); Vishnuprayag is the start of the Alaknanda journey.'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, items = EXCLUDED.items,
  tags = EXCLUDED.tags, content_type = EXCLUDED.content_type,
  strategy_intro = EXCLUDED.strategy_intro, connector_notes = EXCLUDED.connector_notes;
