-- Rajasthan + Gujarat + Andhra Pradesh + Telangana + Uttarakhand breadth treks (B5)
-- Research: rajasthantourism.gov.in, gujarattourism.com, apttdc.ap.gov.in, telanganatourism.gov.in, uttarakhandtourism.gov.in, ASI, district admin sites
-- Destination verification: all 10 destination IDs verified present in DB (mount-abu, alwar, udaipur, neemrana, champaner-pavagadh, porbandar, ahmedabad, araku-valley, hyderabad, binsar)
-- Total: 10 treks inserted

INSERT INTO treks (id, destination_id, name, difficulty, duration_days, max_altitude_m, distance_km, best_months, permits_required, kids_suitable, fitness_level, description, highlights, warnings, permit_details, source_url)
VALUES

-- RAJASTHAN (4)
('achalgarh-fort-trek', 'mount-abu', 'Achalgarh Fort Trek', 'easy', 1, 1380, 4, ARRAY[10,11,12,1,2,3,4,5], false, true, 'beginner', 'A 4km easy walk from Mount Abu to the 10th-century Achalgarh Fort, featuring the sacred Achaleshwar Mahadev Temple with a 5-meter brass Nandi statue and Jain temples with intricate marble carvings. Panoramic Aravalli views and peaceful pilgrimage site. No permits required.', ARRAY['Achaleshwar Mahadev Temple','10th-century fort ruins','Jain marble temples','Aravalli mountain views','Sacred pilgrimage site'], ARRAY['Steep sections for less-fit visitors','Bring water - limited shade on ascent'], 'No permits required', 'https://www.indianpanorama.in/experiences/nature-wildlife/hills/achalgarh.php')

, ('bhangarh-fort-trek', 'alwar', 'Bhangarh Fort Trek', 'easy', 1, 900, 5, ARRAY[10,11,12,1,2,3,4,5], false, true, 'beginner', 'A 5km heritage walk around the 16th-century Bhangarh Fort (built 1573 by Raja Madho Singh I), once housing 10,000 residents. Explore temple ruins, palace foundations, and ramparts in the Sariska Reserve foothills. CRITICAL: ASI prohibits entry sunset to sunrise due to wildlife (leopards, wild boar) and structural hazards — day visit only.', ARRAY['16th-century fort complex','Temple ruins and palaces','Sariska Reserve wildlife','Aravalli heritage site'], ARRAY['ASI day-visit only: NO entry after sunset','Leopards and wild boar present','Structural hazards - stay on marked paths','No facilities or water - bring supplies'], 'Day visits only (ASI regulation). Entry sunset-to-sunrise strictly forbidden for safety reasons.', 'https://www.freepressjournal.in/lifestyle/where-is-bhangarh-indias-only-certified-haunted-site-with-night-ban')

, ('sajjangarh-monsoon-palace-trek', 'udaipur', 'Sajjangarh Monsoon Palace Trek', 'easy', 1, 944, 6, ARRAY[10,11,12,1,2,3,4,5], false, true, 'beginner', 'A 6km trek ascending the Bansdara peak (944m) to the 1884 Sajjangarh Monsoon Palace, built by Maharana Sajjan Singh of Mewar Dynasty. Originally designed as an astronomical center, now a palatial retreat with sweeping views of Lake Fateh Sagar, City Palace, and Chittorgarh. 2-hour climb through Aravalli slopes.', ARRAY['White marble palace (1884)','Bansdara peak summit','Lake Fateh Sagar views','City Palace and Chittorgarh vistas','Aravalli forest trails'], ARRAY['Steep ascent - paced walking advised','Exposed sections - sun protection needed','No water sources on trail'], 'None required', 'https://udaipurtourism.co.in/monsoon-palace-sajjangarh-palace-udaipur')

, ('neemrana-fort-trek', 'neemrana', 'Neemrana Fort Ramparts Heritage Walk', 'easy', 1, 460, 3, ARRAY[1,2,3,4,5,10,11,12], false, true, 'beginner', 'A 3km heritage ramparts walk through Neemrana Fort Palace (15th-century), sprawling 25 acres across Aravalli ridges. Explore terraces, courtyards, and multi-level medieval architecture. The fort offers India''s oldest zip-line. Knowledgeable guides available. Many steps and ramps throughout.', ARRAY['15th-century fort palace','14-tiered architecture','Terrace courtyards and courtyards','India''s oldest zip-line','Aravalli ridge views'], ARRAY['Many steps and ramps - not accessible for limited mobility','Crumbling stonework - careful footing required'], 'None required', 'https://www.neemranahotels.com/blog/explore-the-historic-town-of-neemrana-rajasthan.html')

-- GUJARAT (3)
, ('pavagadh-summit-trek', 'champaner-pavagadh', 'Pavagadh Summit Trek to Kalika Mata Temple', 'moderate', 1, 762, 5, ARRAY[10,11,12,1,2,3,4,5], false, false, 'intermediate', 'A 5km step-and-climb trek to the summit of Pavagadh (762m), ending at the sacred Kalika Mata Temple (10th–11th century Shakti Peeth shrine). Approximately 2,000 stone steps ascend through sacred slopes; 250 additional steps from ropeway station to temple. Alternative: ropeway covers 740m and descends on foot. Within UNESCO-listed Champaner–Pavagadh Archaeological Park.', ARRAY['Kalika Mata Temple (Shakti Peeth)','2,000 stone steps','Pavagadh summit (762m)','Ropeway alternative option','UNESCO World Heritage site'], ARRAY['2,000+ steps - extreme fitness recommended','Steep ascent with limited shade','Temple access - respect religious protocols','Water scarcity on steps'], 'Hindu pilgrimage site - respectful dress required. Ropeway: 740m cable, 250 steps from station to temple.', 'https://www.bharatvarshayatra.com/pavagadh-temple-where-spirituality-meets-ancient-history/')

, ('barda-hills-trek', 'porbandar', 'Barda Wildlife Sanctuary Coastal Forest Trek', 'moderate', 1, 620, 8, ARRAY[11,12,1,2,3], false, false, 'intermediate', 'An 8km trek through Barda Wildlife Sanctuary (192 sq km), a crucial second home for Asiatic lions (Gir–Barda Project since 1979). Dry mixed forest with 650+ plant species, wildlife sightings of leopards, sambar deer, chinkara, and resident/migratory birds. Coastal scrub ecosystem near Porbandar; guide mandatory.', ARRAY['Asiatic lion habitat (Gir-Barda Project)','Leopards and sambar deer','650+ plant species','Bird watching paradise','Saurashtra coastal scrub ecosystem'], ARRAY['Lions present - guide MANDATORY','No solo trekking allowed','Limited water sources','Oct-May season only (wildlife migration)'], 'Guide mandatory. Part of Gir–Barda Project to establish second lion population.', 'https://gujarattourism.com/saurashtra/porbandar/barda-wildlife-sanctuary.html')

, ('polo-forest-trek', 'ahmedabad', 'Polo Forest Vijaynagar Ruins Trek', 'easy', 1, 280, 6, ARRAY[9,10,11,12,1,2], false, true, 'beginner', 'A 6km trek through Polo Forest (Vijaynagar Forest), a dry mixed deciduous forest near Abhapur in Sabarkantha district. Discover 15th-century Hindu and Jain temple ruins (Sharaneshwar Shiva Temple, Surya Mandir) on the Harnav River banks. Post-monsoon (Sept–Feb) lush; forest is undeveloped with no entry fee or permit. Easy 4–5 hour walk.', ARRAY['15th-century temple ruins','Sharaneshwar Shiva Temple','Harnav River walks','Dry deciduous forest','Archaeological sites'], ARRAY['Limited facilities - no water or food vendors','Unmarked trails in some sections','Best post-monsoon (wet/slippery Sept-Nov)'], 'No permits or entry fees required. No formal guide infrastructure.', 'https://www.safargujarat.com/polo-forest-sabarkantha/')

-- ANDHRA PRADESH (1)
, ('araku-bhairavakona-trek', 'araku-valley', 'Araku Valley to Bhairavakona Cave Trek', 'moderate', 1, 1100, 12, ARRAY[10,11,12,1,2,3], false, false, 'intermediate', 'A 12km combined trek from Araku Valley town into the Nallamala hills (Eastern Ghats) reaching Bhairavakona, a complex of 8 rock-cut cave temples (7th–8th century AD, Pallava style). Dedicated to Kala Bhairava (Shiva), the site includes 200m Bhairavakona waterfalls and tribal Prakasam district heritage. Immersion in Eastern Ghats tribal culture.', ARRAY['8 rock-cut cave temples (7th-8th century)','200m Bhairavakona waterfalls','Pallava architectural style','Eastern Ghats tribal culture','Sacred Kala Bhairava shrine'], ARRAY['12km full-day trek - high fitness required','Steep sections with waterfalls (wet/slippery)','Tribal area - respect local customs','Limited commercial infrastructure'], 'Tribal area - local guides recommended for respectful cultural interaction.', 'https://www.tripadvisor.com/Attraction_Review-g25298772-d5877574-Reviews-Bhairavakona-Kothapalli_Prakasam_District_Andhra_Pradesh.html')

-- TELANGANA (1)
, ('yadagirigutta-trek', 'hyderabad', 'Yadagirigutta Lakshmi Narasimha Temple Trek', 'easy', 1, 480, 4, ARRAY[1,2,3,4,5,10,11,12], false, true, 'beginner', 'A 4km trek up Yadagirigutta hill (300 feet, 480m peak near Yadadri Bhuvanagiri district) to the Sri Lakshmi Narasimha Swamy Temple, worshipping Lord Narasimha in five forms. Rebuilt as major pilgrimage complex (2022). Cave temple with self-manifested deity idol. Short, accessible climb with panoramic views.', ARRAY['Sri Lakshmi Narasimha Swamy Temple','5 forms of Lord Narasimha','Rebuilt modern complex (2022)','Cave temple shrine','Pilgrim viewpoint over plains'], ARRAY['Pilgrimage site - respect religious protocols','Crowds on weekends and festivals','Exposed sections - sun protection needed'], 'Hindu pilgrimage site. Respectful dress (no sleeveless). Women can visit all areas.', 'https://www.templewalks.com/lord-vishnu-temples/sri-lakshmi-narasimha-swamy-temple-yadagirigutta-timings-info/')

-- UTTARAKHAND (1)
, ('binsar-zero-point-trek', 'binsar', 'Binsar Zero Point Sunrise Trek', 'easy', 1, 2412, 4, ARRAY[3,4,5,9,10,11], false, true, 'beginner', 'A 4km trek from Binsar village (within Binsar Wildlife Sanctuary, Almora district) to Zero Point (2412m), a marked alpine viewpoint in the Kumaon Ranges. Early-morning ascent rewards with golden sunrise over Nanda Devi, Trishul, Panchachuli, and Kedarnath peaks. Easy trail through oak, pine, and rhododendron forests; home to 200+ bird species and leopards, barking deer, Himalayan bears.', ARRAY['2412m Zero Point viewpoint','Nanda Devi and Trishul peaks','Sunrise over 4 Himalayan peaks','Binsar Wildlife Sanctuary','Oak/pine/rhododendron forests'], ARRAY['Early morning start required for sunrise','Weather-dependent visibility','Limited water sources - bring enough','March-June: rhododendron blooms (May peak)'], 'Binsar Wildlife Sanctuary entry (minimal fee). Start pre-dawn (4-5am) for sunrise. Self-guided or informal guides available.', 'https://www.rewildindia.com/binsar-trek.php')

ON CONFLICT (id) DO NOTHING;
