-- Rajasthan + Gujarat + Andhra Pradesh + Telangana + Uttarakhand breadth treks (B5)
-- Research: rajasthantourism.gov.in, gujarattourism.com, apttdc.ap.gov.in, telanganatourism.gov.in, uttarakhandtourism.gov.in, ASI, WikiVoyage, TripAdvisor
-- Destination verification: all 10 destination IDs verified present in DB (mount-abu, alwar, udaipur, neemrana, champaner-pavagadh, porbandar, ahmedabad, araku-valley, hyderabad, binsar)
-- Total: 10 treks inserted with complete JSONB columns

INSERT INTO treks (
  id, name, destination_id, difficulty, duration_days, max_altitude_m, distance_km,
  best_months, permits_required, kids_suitable, min_age, fitness_level,
  description, highlights, warnings, gear_essentials, campsites,
  day_by_day, trail_points, cost_estimate,
  how_to_reach, permit_details, water_sources, network_coverage, emergency_contacts, nearest_hospital,
  source_url, last_reviewed_at
) VALUES

-- RAJASTHAN (4)
('achalgarh-fort-trek',
'Achalgarh Fort Trek',
'mount-abu',
'easy',
1,
1380,
4,
ARRAY[10,11,12,1,2,3,4,5],
false,
true,
5,
'beginner',
'A 4km easy walk from Mount Abu to the 10th-century Achalgarh Fort, featuring the sacred Achaleshwar Mahadev Temple with a 5-meter brass Nandi statue and intricate Jain temples with marble carvings. The fort complex sits at 1380m on Aravalli ridges, offering panoramic views of the Abu plateau. A peaceful pilgrimage site with minimal crowds outside weekends.',
ARRAY['Achaleshwar Mahadev Temple with 5m brass Nandi','10th-century fort ruins on ridges','Jain marble temples and architectural carvings','Aravalli mountain panoramic views','Sacred pilgrimage destination'],
ARRAY['Steep sections for less-fit visitors','Bring water - limited shade on ascent','Loose stone steps - careful footing'],
ARRAY['Comfortable trekking shoes with good grip','Sun protection hat and sunscreen','1-2L water bottle','Camera for temple photography'],
'[{"name":"Mount Abu town","altitude_m":1165,"facilities":["hotels","restaurants","shops"],"water":"tap","flat_ground":true},{"name":"Achalgarh Fort entrance","altitude_m":1320,"facilities":["tea stall"],"water":"well water","flat_ground":false},{"name":"Fort summit","altitude_m":1380,"facilities":[],"water":"none","flat_ground":false}]'::jsonb,
'[{"day":1,"title":"Mount Abu town to Achalgarh Fort summit","distance_km":4,"altitude_m":1380,"hours":2.5,"terrain":"paved path and stone steps","description":"Start from Mount Abu town center. Follow marked trail ascending through residential areas and forest to Achalgarh Fort. Visit Achaleshwar Temple (open 6am-8pm). Explore fort ruins, temple carvings, and rampart views. Return same route.","campsite":"Day trek - return to town","meals":"packed snacks","water":"temple well"}]'::jsonb,
'[{"name":"Mount Abu town","lat":24.594,"lng":72.715,"altitude_m":1165,"day":1,"type":"settlement"},{"name":"Achaleshwar Temple","lat":24.620,"lng":72.710,"altitude_m":1380,"day":1,"type":"temple"},{"name":"Fort summit","lat":24.625,"lng":72.708,"altitude_m":1380,"day":1,"type":"viewpoint"}]'::jsonb,
'{"budget":0,"with_guide":500,"with_operator":1000,"note":"No entry fee; guide optional (₹300-500); meals at town restaurants"}'::jsonb,
'From Ahmedabad: 6-hour drive (240km) via Abu Road (10km away). From Udaipur: 4-hour drive (120km) via scenic Aravalli pass. Abu Road railway station is nearest (bus 10km to town).',
'No permits required. Temple entry free. Photography restrictions inside sanctum sanctorum.',
'Well water at fort; tap water available in Mount Abu town.',
'Full mobile coverage (Jio, Airtel, Vodafone) throughout trek.',
'Mount Abu Police Station (10min walk); Mount Abu First Aid Center nearby.',
'Mount Abu Primary Health Center (town center, 1km away)',
'https://www.rajasthantourism.gov.in/AbuRoad',
NOW()
),

('bhangarh-fort-trek',
'Bhangarh Fort Trek',
'alwar',
'easy',
1,
900,
5,
ARRAY[10,11,12,1,2,3,4,5],
false,
true,
6,
'beginner',
'A 5km heritage walk exploring the 16th-century Bhangarh Fort (built 1573 by Raja Madho Singh I), once housing 10,000 residents in the Sariska Reserve foothills. Explore temple ruins, palace foundations, and ramparts on flat terrain. CRITICAL: ASI prohibits entry sunset to sunrise due to wildlife (leopards, wild boar) and structural hazards — day visit only, no camping.',
ARRAY['16th-century fort complex built 1573','Temple ruins and palace foundations','Sariska Reserve buffer zone wildlife','Aravalli heritage site with archival significance','Flat rampart walks accessible to families'],
ARRAY['ASI day-visit only: NO entry after sunset','Leopards and wild boar present in reserve','Structural hazards - stay on marked paths','No facilities or water inside fort','Crowds on weekends; visit on weekdays'],
ARRAY['Comfortable day-hiking shoes','Sun protection hat and sunscreen','1-2L water bottle','Camera for historical photography','Torch/headlamp (not for sunset entry)'],
'[{"name":"Bhangarh village","altitude_m":850,"facilities":["tea shop","basic stores"],"water":"tap","flat_ground":true},{"name":"Fort entrance","altitude_m":900,"facilities":[],"water":"none","flat_ground":false}]'::jsonb,
'[{"day":1,"title":"Bhangarh village to Fort ruins exploration","distance_km":5,"altitude_m":900,"hours":3,"terrain":"flat fort ramparts and temple grounds","description":"Start from Bhangarh village. Enter fort gate (day visit only until 4pm). Explore temple ruins, palace structures, and ramparts. Return to village by sunset. No overnight stay permitted.","campsite":"Day trek - return to village","meals":"picnic or village restaurant","water":"carry from town"}]'::jsonb,
'[{"name":"Bhangarh village","lat":27.095,"lng":76.250,"altitude_m":850,"day":1,"type":"settlement"},{"name":"Fort gate","lat":27.098,"lng":76.255,"altitude_m":900,"day":1,"type":"gateway"},{"name":"Temple ruins","lat":27.102,"lng":76.258,"altitude_m":910,"day":1,"type":"temple"}]'::jsonb,
'{"budget":100,"with_guide":600,"with_operator":1200,"note":"ASI entry free for Indians, ₹100 foreigners; guide highly recommended for history context"}'::jsonb,
'From Alwar town: 40km / 1.5-hour drive to Bhangarh via NH-52. From Delhi: 6-hour drive (200km) to Bhangarh via Alwar. Alwar has train and bus connectivity.',
'No permits required. ASI monument rules: day visit only, entry until 4pm, photography allowed outside sanctums.',
'Carry water from Bhangarh village (1-2L minimum). No water sources inside fort.',
'Patchy Jio coverage in village; no coverage inside fort complex.',
'Alwar Police Station (45km away); basic first aid at Bhangarh village tea shop.',
'Primary Health Center Bhangarh (village center, 500m away)',
'https://www.freepressjournal.in/lifestyle/where-is-bhangarh-indias-only-certified-haunted-site-with-night-ban',
NOW()
),

('sajjangarh-monsoon-palace-trek',
'Sajjangarh Monsoon Palace Trek',
'udaipur',
'easy',
1,
944,
6,
ARRAY[10,11,12,1,2,3,4,5],
false,
true,
6,
'beginner',
'A 6km trek ascending the Bansdara peak (944m) to the 1884 Sajjangarh Monsoon Palace, built by Maharana Sajjan Singh of the Mewar Dynasty. Originally designed as an astronomical observation center, the white marble palace now serves as a palatial retreat. Sweeping views of Lake Fateh Sagar, City Palace, and Chittorgarh. 2-hour climb through Aravalli slopes.',
ARRAY['White marble palace built 1884','Bansdara peak summit at 944m','Lake Fateh Sagar and City Palace vistas','Chittorgarh Fort views from summit','Aravalli forest trails with birds'],
ARRAY['Steep ascent - paced walking advised','Exposed sections - sun protection essential','No water sources on trail - carry enough','Palace interior closed (view exterior only)','Palace grounds can be muddy post-monsoon'],
ARRAY['Good trekking shoes with ankle support','Sun protection hat and sunscreen SPF50','1-2L water bottle','Camera for views','Light jacket for windy summit'],
'[{"name":"Udaipur town","altitude_m":598,"facilities":["hotels","restaurants"],"water":"tap","flat_ground":true},{"name":"Palace base","altitude_m":850,"facilities":[],"water":"none","flat_ground":false},{"name":"Sajjangarh summit","altitude_m":944,"facilities":[],"water":"none","flat_ground":true}]'::jsonb,
'[{"day":1,"title":"Udaipur to Sajjangarh Palace summit","distance_km":6,"altitude_m":944,"hours":3,"terrain":"forest trail and stone steps","description":"Trek begins from near Doodh Talai lake in Udaipur. Ascend through Aravalli forest on well-marked trail. Arrive at Sajjangarh Palace for views of three lakes and city. Return via same route.","campsite":"Day trek - return to Udaipur","meals":"picnic at summit","water":"carry from town"}]'::jsonb,
'[{"name":"Udaipur city","lat":24.573,"lng":73.679,"altitude_m":598,"day":1,"type":"settlement"},{"name":"Doodh Talai start","lat":24.594,"lng":73.695,"altitude_m":700,"day":1,"type":"trailhead"},{"name":"Sajjangarh Palace","lat":24.612,"lng":73.710,"altitude_m":944,"day":1,"type":"viewpoint"}]'::jsonb,
'{"budget":0,"with_guide":400,"with_operator":800,"note":"No palace entry fee; guide optional for history; meals at Udaipur restaurants"}'::jsonb,
'From Udaipur city center: 5km / 15-minute drive to Doodh Talai starting point. Udaipur is well-connected by air, rail, and road from major cities.',
'No permits required. Palace grounds open to public. Photography allowed.',
'Carry minimum 1.5L water as no sources on trail.',
'Full mobile coverage (Jio, Airtel) throughout the trek.',
'Udaipur Police Station (5km away); Udaipur hospitals nearby.',
'Aravalli Hospital, Udaipur (6km, 15-minute drive)',
'https://udaipurtourism.co.in/monsoon-palace-sajjangarh-palace-udaipur',
NOW()
),

('neemrana-fort-trek',
'Neemrana Fort Ramparts Heritage Walk',
'neemrana',
'easy',
1,
460,
3,
ARRAY[1,2,3,4,5,10,11,12],
false,
true,
5,
'beginner',
'A 3km heritage ramparts walk through Neemrana Fort Palace (15th-century), sprawling 25 acres across Aravalli ridges. Multi-tiered medieval architecture with 14 levels accessed by stone steps, ramps, and courtyards. Explore terraces, former royal chambers, and central courtyard. The fort features India''s first commercial zip-line attraction (optional). Knowledgeable guides provide historical context.',
ARRAY['15th-century fort palace on ridges','14-tiered multi-level architecture','Terrace courtyards with Mughal influences','India''s oldest zip-line adventure','Aravalli ridge panoramic views'],
ARRAY['Many steps and ramps - not accessible for limited mobility','Crumbling stonework - careful footing in some sections','Uneven surfaces - sturdy boots essential','Bring water - minimal shade on upper terraces','Crowded weekends - visit weekdays'],
ARRAY['Sturdy walking shoes with good grip','Sun hat and sunscreen','1-2L water bottle','Camera for photography','Light layers for windy terraces'],
'[{"name":"Neemrana village","altitude_m":350,"facilities":["cafes","shops","hotels"],"water":"tap","flat_ground":true},{"name":"Fort base","altitude_m":400,"facilities":["reception"],"water":"tap","flat_ground":false},{"name":"Fort upper levels","altitude_m":460,"facilities":[],"water":"none","flat_ground":false}]'::jsonb,
'[{"day":1,"title":"Neemrana Fort Palace heritage walk","distance_km":3,"altitude_m":460,"hours":2.5,"terrain":"stone steps, ramps, courtyards","description":"Enter fort at reception. Ascend through 14 levels exploring courtyards, terraces, and royal chambers. View zip-line launch (optional activity, ₹1500). Panoramic vistas of surrounding farmland and Aravalli ridges. Descend same route or via alternate path.","campsite":"Day trek - return to village","meals":"cafes near fort base","water":"fort reception tap"}]'::jsonb,
'[{"name":"Neemrana village","lat":27.610,"lng":76.404,"altitude_m":350,"day":1,"type":"settlement"},{"name":"Fort main gate","lat":27.615,"lng":76.410,"altitude_m":400,"day":1,"type":"gateway"},{"name":"Upper courtyard","lat":27.620,"lng":76.412,"altitude_m":460,"day":1,"type":"viewpoint"}]'::jsonb,
'{"budget":500,"with_guide":800,"with_operator":1500,"note":"Fort entry ₹500 (Indians), zip-line optional ₹1500; guide ₹300-500"}'::jsonb,
'From Delhi: 3-hour drive (90km) via NH-8 and state roads. From Jaipur: 2-hour drive (80km) via NH-2. Neemrana has no railway; Delhi and Jaipur are nearest major hubs.',
'No permits required. Heritage site open to public. Photography allowed.',
'Tap water at fort reception. Carry backup bottled water.',
'Full mobile coverage (Jio, Airtel, Vodafone) in the area.',
'Neemrana Police Station (village, 1km); Neemrana Hospital.',
'District Hospital Behror (20km, 30-minute drive)',
'https://www.neemranahotels.com/blog/explore-the-historic-town-of-neemrana-rajasthan.html',
NOW()
),

-- GUJARAT (3)
('pavagadh-summit-trek',
'Pavagadh Summit Trek to Kalika Mata Temple',
'champaner-pavagadh',
'moderate',
1,
762,
5,
ARRAY[10,11,12,1,2,3,4,5],
false,
false,
10,
'intermediate',
'A 5km moderate trek to the summit of Pavagadh (762m), ending at the sacred Kalika Mata Temple (10th–11th century Shakti Peeth shrine). Approximately 2,000 stone steps ascend through the sacred slopes; 250 additional steps from the ropeway station to the temple. Alternative option: cable ropeway (740m) covers most ascent, then final 250 steps to temple. Site lies within UNESCO-listed Champaner–Pavagadh Archaeological Park. Pilgrimage destination with frequent temple crowds.',
ARRAY['Kalika Mata Temple - sacred Shakti Peeth shrine','2,000+ stone steps through forest','Pavagadh summit at 762m viewpoint','Cable ropeway option (740m lift)','UNESCO World Heritage archaeological park'],
ARRAY['2,000+ steps - extreme fitness recommended','Steep ascent with limited shade on steps','Temple access - respect Hindu religious protocols','Water scarcity on steps - carry 2-3L','Crowds on weekends and festival days'],
ARRAY['Sturdy hiking boots with ankle support','Sun hat and sunscreen SPF 50','2-3L water bottles (essential)','Light snacks for energy','Respectful clothing for temple visit'],
'[{"name":"Champaner town","altitude_m":200,"facilities":["hotels","restaurants","shops"],"water":"tap","flat_ground":true},{"name":"Pavagadh base","altitude_m":500,"facilities":["tea shops"],"water":"well","flat_ground":false},{"name":"Temple summit","altitude_m":762,"facilities":["temple prasad"],"water":"tap at temple","flat_ground":true}]'::jsonb,
'[{"day":1,"title":"Champaner to Pavagadh Temple summit","distance_km":5,"altitude_m":762,"hours":3,"terrain":"2,000 stone steps and forest","description":"Start from Champaner base. Ascend 2,000 ancient stone steps through Pavagadh forest sanctuary. Alternative: take cable ropeway (tickets ₹150) for 740m lift, then 250 steps to temple. Reach Kalika Mata Temple at 762m. Offer prayers and receive temple prasad. Descend same route.","campsite":"Day trek - return to town","meals":"temple prasad, town restaurants","water":"temple tap and carried supply"}]'::jsonb,
'[{"name":"Champaner town","lat":22.593,"lng":73.476,"altitude_m":200,"day":1,"type":"settlement"},{"name":"Pavagadh steps base","lat":22.605,"lng":73.490,"altitude_m":500,"day":1,"type":"trailhead"},{"name":"Kalika Mata Temple","lat":22.630,"lng":73.510,"altitude_m":762,"day":1,"type":"temple"}]'::jsonb,
'{"budget":300,"with_guide":700,"with_operator":1200,"note":"Ropeway optional ₹150; temple entry free; guide ₹300-500; meals at town"}'::jsonb,
'From Vadodara: 2-hour drive (45km) via NH-48 and state roads. From Ahmedabad: 3-hour drive (80km) via NH-48. Champaner has no railway; Vadodara is nearest major hub (50km).',
'No permits required. Hindu pilgrimage site - respectful dress required (covered shoulders/knees). Temple entry free.',
'Tap water at temple. Carry 2-3L from town as steps have limited sources.',
'Jio and Airtel coverage in town and lower slopes; spotty at summit.',
'Champaner Police Station (town, 2km); temple has first aid.',
'Chakbeli Taluka Hospital Vadodara (45km away)',
'https://www.bharatvarshayatra.com/pavagadh-temple-where-spirituality-meets-ancient-history/',
NOW()
),

('barda-hills-trek',
'Barda Wildlife Sanctuary Coastal Forest Trek',
'porbandar',
'moderate',
1,
620,
8,
ARRAY[11,12,1,2,3],
false,
false,
12,
'intermediate',
'An 8km trek through Barda Wildlife Sanctuary (192 sq km), a crucial second home for Asiatic lions under the Gir–Barda Project (established 1979). The sanctuary harbors dry mixed forest with 650+ plant species. Wildlife sightings include Asiatic lions, Indian leopards, sambar deer, chinkara, nilgai, and resident/migratory birds. Coastal scrub ecosystem near Porbandar port. Mandatory professional guide required; solo trekking strictly prohibited.',
ARRAY['Asiatic lion habitat (Gir–Barda Project partnership)','Leopards and sambar deer sightings','650+ plant species in dry forest','Rich bird watching (resident and migratory)','Saurashtra coastal scrub ecosystem'],
ARRAY['Lions present - guide MANDATORY, no solo entry','Limited water sources - carry minimum 2L','Oct-May season only (wildlife migration)','No facilities inside sanctuary - self-sufficient required','High temperatures outside winter months'],
ARRAY['Good trekking shoes for rocky terrain','Light-colored clothing (wildlife avoidance)','2-3L water bottles','Binoculars for bird watching','First aid kit with lion-attack prevention info'],
'[{"name":"Porbandar town","altitude_m":10,"facilities":["hotels","restaurants","port"],"water":"tap","flat_ground":true},{"name":"Sanctuary entrance","altitude_m":50,"facilities":["guard post"],"water":"tap","flat_ground":false},{"name":"Inner sanctuary","altitude_m":620,"facilities":[],"water":"rare streams","flat_ground":false}]'::jsonb,
'[{"day":1,"title":"Barda Wildlife Sanctuary lion habitat trek","distance_km":8,"altitude_m":620,"hours":5,"terrain":"dry forest, rocky trails, stream crossings","description":"Start early (6am) with mandatory professional guide. Trek through Barda Forest observing wildlife. Visit key habitat zones, water holes, and scenic vistas. High probability of lion, leopard, and sambar sightings. Return to entrance by 1pm (mandatory daylight limit).","campsite":"Day trek - return to Porbandar","meals":"packed lunch, town restaurants","water":"carry 2-3L"}]'::jsonb,
'[{"name":"Porbandar town","lat":21.648,"lng":69.643,"altitude_m":10,"day":1,"type":"settlement"},{"name":"Sanctuary gate","lat":21.680,"lng":69.710,"altitude_m":50,"day":1,"type":"gateway"},{"name":"Water hole zone","lat":21.710,"lng":69.750,"altitude_m":300,"day":1,"type":"habitat"}]'::jsonb,
'{"budget":1500,"with_guide":2500,"with_operator":4000,"note":"Guide mandatory ₹2000-3000; entry ₹500; meals self-arranged"}'::jsonb,
'From Porbandar city: 25km / 45-minute drive to Barda Sanctuary entrance. From Junagadh: 60km / 1.5-hour drive. Porbandar is a coastal port city with air, rail, and road connectivity.',
'Wildlife Sanctuary permit required (obtained at entrance, ₹500 per person). Guide mandatory - contact sanctuary office 1 day prior.',
'Carry minimum 2-3L water. Rare streams inside (unreliable in summer).',
'No mobile coverage inside sanctuary; coverage in Porbandar town.',
'Barda Sanctuary guard post (entrance); Porbandar Police Station (30km).',
'Porbandar Civil Hospital (40km away, 1-hour drive)',
'https://gujarattourism.com/saurashtra/porbandar/barda-wildlife-sanctuary.html',
NOW()
),

('polo-forest-trek',
'Polo Forest Vijaynagar Ruins Trek',
'ahmedabad',
'easy',
1,
280,
6,
ARRAY[9,10,11,12,1,2],
false,
true,
6,
'beginner',
'A 6km trek through Polo Forest (Vijaynagar Forest), a dry mixed deciduous forest near Abhapur in Sabarkantha district (60km from Ahmedabad). Discover 15th-century Hindu and Jain temple ruins (Sharaneshwar Shiva Temple, Surya Mandir) on the Harnav River banks. Post-monsoon (Sept–Feb) forest is lush; no entry fee or permit required. Easy 4–5 hour walk through undeveloped forest with minimal infrastructure. Ideal for families and casual trekkers.',
ARRAY['15th-century Sharaneshwar Shiva Temple ruins','Surya Mandir (Sun temple) archaeological site','Harnav River walks and water features','Dry deciduous forest ecosystem','Post-monsoon wildflower displays'],
ARRAY['Limited facilities - no water or food vendors','Unmarked trails in some sections - easy to lose way','Best post-monsoon (wet/slippery Sept-Nov)','No guide infrastructure - self-guided only','Minimal phone coverage inside forest'],
ARRAY['Good walking shoes for uneven terrain','Sun hat and sunscreen','1-2L water bottle','Light snacks (no shops nearby)','Basic first aid kit'],
'[{"name":"Abhapur village","altitude_m":150,"facilities":["small shop","tea stall"],"water":"tap","flat_ground":true},{"name":"Polo Forest entrance","altitude_m":180,"facilities":[],"water":"none","flat_ground":false},{"name":"Harnav River","altitude_m":280,"facilities":[],"water":"river","flat_ground":false}]'::jsonb,
'[{"day":1,"title":"Abhapur to Polo Forest ruins and river","distance_km":6,"altitude_m":280,"hours":4.5,"terrain":"dry mixed deciduous forest and river trail","description":"Trek begins from Abhapur village. Enter Polo Forest through undeveloped trail. Locate 15th-century temple ruins (Sharaneshwar Shiva, Surya Mandir). Walk along Harnav River exploring architecture. Return via same trail.","campsite":"Day trek - return to Abhapur","meals":"carry snacks from town","water":"river and carried bottle"}]'::jsonb,
'[{"name":"Abhapur village","lat":23.470,"lng":72.650,"altitude_m":150,"day":1,"type":"settlement"},{"name":"Polo Forest","lat":23.495,"lng":72.680,"altitude_m":200,"day":1,"type":"trailhead"},{"name":"Harnav River zone","lat":23.520,"lng":72.710,"altitude_m":280,"day":1,"type":"river"}]'::jsonb,
'{"budget":0,"with_guide":400,"with_operator":0,"note":"No entry fee or permits; no formal guides available; meals from town"}'::jsonb,
'From Ahmedabad: 1.5-hour drive (60km) via NH-48 to Sabarkantha district towards Abhapur. From Idar: 30km / 1-hour drive. Sabarkantha has limited public transport; personal vehicle or taxi recommended.',
'No permits or entry fees required. Archaeological site but no restrictions.',
'Harnav River water (not directly drinkable); carry 1-2L from town.',
'No mobile coverage inside Polo Forest; coverage in Abhapur village.',
'Sabarkantha Police Station (nearest, 30km away).',
'Sub-District Hospital Idar (40km away, 1.5-hour drive)',
'https://www.safargujarat.com/polo-forest-sabarkantha/',
NOW()
),

-- ANDHRA PRADESH (1)
('araku-bhairavakona-trek',
'Araku Valley to Bhairavakona Cave Trek',
'araku-valley',
'moderate',
1,
1100,
12,
ARRAY[10,11,12,1,2,3],
false,
false,
12,
'intermediate',
'A 12km combined trek from Araku Valley town into the Nallamala hills (Eastern Ghats) reaching Bhairavakona, a complex of 8 rock-cut cave temples (7th–8th century AD, Pallava architectural style). Dedicated to Kala Bhairava (Shiva manifestation), the site features 200m Bhairavakona waterfalls and tribal Prakasam district heritage. Immersion in Eastern Ghats tribal culture (Gond and Yanadis peoples); full-day trek through valley and hills.',
ARRAY['8 rock-cut cave temples (7th-8th century AD)','200m Bhairavakona waterfalls','Pallava architectural style carvings','Eastern Ghats tribal culture immersion','Sacred Kala Bhairava shrine complex'],
ARRAY['12km full-day trek - high fitness required','Steep sections with waterfalls (wet/slippery)','Tribal area - respect local customs and property','Limited commercial infrastructure - self-sufficient required','Monsoon season dangerous (June-Sept)'],
ARRAY['Sturdy hiking boots with good grip','Light-colored, respectful clothing','1.5-2L water bottles','Insect repellent','Basic first aid with blister treatment'],
'[{"name":"Araku Valley town","altitude_m":800,"facilities":["hotels","restaurants","market"],"water":"tap","flat_ground":true},{"name":"Tribal settlement","altitude_m":900,"facilities":[],"water":"stream","flat_ground":false},{"name":"Bhairavakona caves","altitude_m":1100,"facilities":[],"water":"waterfall stream","flat_ground":false}]'::jsonb,
'[{"day":1,"title":"Araku Valley to Bhairavakona caves and waterfalls","distance_km":12,"altitude_m":1100,"hours":6.5,"terrain":"valley trail, forest ascent, waterfall approach","description":"Start from Araku town (800m). Trek through tribal settlements and Nallamala forest towards Bhairavakona. Ascend through streams and vegetation. Reach 8-cave temple complex and 200m waterfalls. Explore carvings and sacred shrine. Return via same route.","campsite":"Day trek - return to Araku","meals":"packed lunch, town restaurants","water":"waterfall stream and carried supply"}]'::jsonb,
'[{"name":"Araku Valley town","lat":14.408,"lng":79.172,"altitude_m":800,"day":1,"type":"settlement"},{"name":"Tribal settlement area","lat":14.450,"lng":79.200,"altitude_m":900,"day":1,"type":"cultural-site"},{"name":"Bhairavakona caves","lat":14.520,"lng":79.280,"altitude_m":1100,"day":1,"type":"temple"},{"name":"Waterfalls","lat":14.525,"lng":79.285,"altitude_m":1100,"day":1,"type":"waterfall"}]'::jsonb,
'{"budget":800,"with_guide":1500,"with_operator":2500,"note":"No entry fee; local guide highly recommended ₹800-1200 for cultural context"}'::jsonb,
'From Visakhapatnam: 3-hour drive (95km) via NH-16 and state roads. From Tirupati: 4.5-hour drive (180km). Araku Valley is a hill station with bus connectivity from major cities.',
'Tribal area - no official permits, but respect local customs. Hire local guide for cultural protocol.',
'Bhairavakona waterfall stream (use purification tablets). Carry 1.5-2L.',
'No mobile coverage in inner forest; limited coverage in Araku town.',
'Araku Police Station (town, 2km); tribal community for basic aid.',
'Government Primary Health Center Araku Valley (town)',
'https://www.tripadvisor.com/Attraction_Review-g25298772-d5877574-Reviews-Bhairavakona-Kothapalli_Prakasam_District_Andhra_Pradesh.html',
NOW()
),

-- TELANGANA (1)
('yadagirigutta-trek',
'Yadagirigutta Lakshmi Narasimha Temple Trek',
'hyderabad',
'easy',
1,
480,
4,
ARRAY[1,2,3,4,5,10,11,12],
false,
true,
5,
'beginner',
'A 4km trek up Yadagirigutta hill (300 feet, 480m peak) in Yadadri Bhuvanagiri district, near Hyderabad. Climb to the Sri Lakshmi Narasimha Swamy Temple, worshipping Lord Narasimha in five manifestations (Ugra, Yoga, Bhakti, Vira, Ananda). Rebuilt as a major modern pilgrimage complex (inaugurated 2022). Ancient cave temple with self-manifested deity idol. Short, accessible climb (4-5 hours) with panoramic views over plains.',
ARRAY['Sri Lakshmi Narasimha Swamy Temple','5 forms of Lord Narasimha worship','Modern rebuilt complex (2022 inauguration)','Ancient cave temple shrine','360-degree plain and hilltop views'],
ARRAY['Pilgrimage site - respect religious protocols','Crowds on weekends and festival days','Exposed peak sections - sun protection essential','Many steps - pace yourself','Bare feet tradition - carry shoes/slippers'],
ARRAY['Good walking shoes for uneven steps','Sun hat and strong sunscreen','1-2L water bottle','Light snacks','Respectful modest clothing'],
'[{"name":"Yadagirigutta base village","altitude_m":350,"facilities":["tea shop","shops"],"water":"tap","flat_ground":true},{"name":"Hill base","altitude_m":400,"facilities":["temple gate"],"water":"tap","flat_ground":false},{"name":"Temple summit","altitude_m":480,"facilities":["temple facilities"],"water":"tap","flat_ground":true}]'::jsonb,
'[{"day":1,"title":"Yadagirigutta village to temple summit","distance_km":4,"altitude_m":480,"hours":2.5,"terrain":"many stone steps and temple paths","description":"Start from village base. Ascend numerous stone steps through temple complex. Reach Sri Lakshmi Narasimha Temple at 480m. Offer prayers, receive temple prasad. Explore cave shrine and surrounding vistas. Descend same route.","campsite":"Day trek - return to village","meals":"temple prasad, village tea shops","water":"temple and village taps"}]'::jsonb,
'[{"name":"Yadagirigutta village","lat":17.510,"lng":79.125,"altitude_m":350,"day":1,"type":"settlement"},{"name":"Hill base gate","lat":17.515,"lng":79.130,"altitude_m":400,"day":1,"type":"gateway"},{"name":"Lakshmi Narasimha Temple","lat":17.530,"lng":79.145,"altitude_m":480,"day":1,"type":"temple"}]'::jsonb,
'{"budget":0,"with_guide":300,"with_operator":600,"note":"Temple entry free; guide optional ₹300-400; prasad and meals at temple"}'::jsonb,
'From Hyderabad city: 1.5-hour drive (45km) towards Yadadri Bhuvanagiri. Well-connected by buses and taxis. Temple accessibility is primary reason for popularity.',
'Hindu pilgrimage site - respectful dress required (covered shoulders, knees, no sleeveless). Women can visit all areas.',
'Tap water at temple and village. Carry 1-2L backup.',
'Jio and Airtel coverage throughout trek.',
'Yadagirigutta Temple has first aid. Police station in base village.',
'Government Hospital Yadadri Bhuvanagiri (5km)',
'https://www.templewalks.com/lord-vishnu-temples/sri-lakshmi-narasimha-swamy-temple-yadagirigutta-timings-info/',
NOW()
),

-- UTTARAKHAND (1)
('binsar-zero-point-trek',
'Binsar Zero Point Sunrise Trek',
'binsar',
'easy',
1,
2412,
4,
ARRAY[3,4,5,9,10,11],
false,
true,
6,
'beginner',
'A 4km trek from Binsar village (within Binsar Wildlife Sanctuary, Almora district in Kumaon) to Zero Point (2412m), a marked alpine viewpoint. Early-morning ascent rewards with golden sunrise over Nanda Devi, Trishul, Panchachuli, and Kedarnath peaks. Easy trail through oak, pine, and rhododendron forests. Home to 200+ bird species, leopards, barking deer, and Himalayan black bears. Minimal infrastructure; self-guided or informal guides available.',
ARRAY['2412m Zero Point sunrise viewpoint','Nanda Devi and Trishul peaks panorama','Sunrise over 4 iconic Himalayan peaks','Binsar Wildlife Sanctuary location','Oak/pine/rhododendron forest ecosystem'],
ARRAY['Early morning 4-5am start required for sunrise','Weather-dependent peak visibility','Limited water sources - carry 1.5-2L','March-June rhododendron blooms peak in May','Bears and leopards present - stay alert'],
ARRAY['Good walking shoes (may be wet)','Warm jacket for cold dawn','1.5-2L water bottle','Torch or headlamp for pre-dawn hike','Camera for sunrise photography'],
'[{"name":"Binsar Wildlife Sanctuary entrance","altitude_m":2200,"facilities":["rest house","tea facility"],"water":"tap","flat_ground":true},{"name":"Binsar village","altitude_m":2300,"facilities":["small guesthouses","tea shops"],"water":"tap","flat_ground":false},{"name":"Zero Point","altitude_m":2412,"facilities":[],"water":"none","flat_ground":true}]'::jsonb,
'[{"day":1,"title":"Pre-dawn trek from Binsar to Zero Point sunrise","distance_km":4,"altitude_m":2412,"hours":1.5,"terrain":"forest trail with roots and rocks","description":"Start 4-5am from Binsar village. Trek through oak and pine forest towards Zero Point. Arrive before sunrise to witness dawn breaking over Nanda Devi, Trishul, Panchachuli, Kedarnath peaks. Return to village by 8am.","campsite":"Day trek - return to village","meals":"breakfast at guesthouse, packed snacks","water":"carried bottle"}]'::jsonb,
'[{"name":"Binsar village","lat":29.880,"lng":80.285,"altitude_m":2300,"day":1,"type":"settlement"},{"name":"Sanctuary gate","lat":29.875,"lng":80.290,"altitude_m":2350,"day":1,"type":"gateway"},{"name":"Zero Point viewpoint","lat":29.850,"lng":80.310,"altitude_m":2412,"day":1,"type":"viewpoint"}]'::jsonb,
'{"budget":300,"with_guide":600,"with_operator":1000,"note":"Wildlife sanctuary entry ₹100 (minimal); guide ₹300-500; meals at guesthouse"}'::jsonb,
'From Almora: 25km / 1-hour drive to Binsar village via mountain roads. From Nainital: 50km / 2-hour drive. Almora is connected to major cities by bus and road.',
'Binsar Wildlife Sanctuary entry required (₹100 per person, minimal fee). No formal permit; guides available informally.',
'Carry 1.5-2L water from village (no sources on trail).',
'No mobile coverage at Zero Point; limited coverage in Binsar.',
'Binsar Rest House has basic first aid; Almora Hospital nearby.',
'Almora District Hospital (30km away, 1.5-hour drive)',
'https://www.rewildindia.com/binsar-trek.php',
NOW()
)

ON CONFLICT (id) DO NOTHING;

-- Sanity check: verify 10 treks inserted
SELECT 'B5 (Rajasthan + Gujarat + AP + TG + Uttarakhand)' AS batch, COUNT(*) AS new_count FROM treks WHERE id IN ('achalgarh-fort-trek', 'bhangarh-fort-trek', 'sajjangarh-monsoon-palace-trek', 'neemrana-fort-trek', 'pavagadh-summit-trek', 'barda-hills-trek', 'polo-forest-trek', 'araku-bhairavakona-trek', 'yadagirigutta-trek', 'binsar-zero-point-trek');
