#!/bin/bash
# run-veo.sh — the daily Veo generation job.
#
# Runs as a LaunchAgent via /bin/bash. That combination is deliberate and both
# halves matter (scar, 2026-09-09/10): cron cannot unlock the login keychain, and
# launchd through a non-FDA interpreter cannot read ~/Desktop. /bin/bash already
# holds Full Disk Access on this machine, so a LaunchAgent invoking /bin/bash
# gets both — which this job needs, because the storyboard code lives in the repo
# under ~/Desktop while the job itself must live under ~/Automation (launchd is
# TCC-blocked under ~/Desktop).
set -uo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$HOME/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE" || exit 1
say() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

say "=== veo-daily start ==="

# 1. Top up the queue from today's data. Safe to run repeatedly: enqueue()
#    dedupes on clip name and the ledger stops a destination repeating.
python3 build-queue.py || say "WARN build-queue exited non-zero"

PENDING=$(python3 -c "import json,os;p='veo_queue.json';print(sum(1 for r in (json.load(open(p)) if os.path.exists(p) else []) if r.get('status')=='pending'))" 2>/dev/null || echo 0)
say "pending clips: $PENDING"
if [ "$PENDING" -eq 0 ]; then
  say "nothing pending — exiting clean"
  say "=== veo-daily end (exit=0) ==="
  exit 0
fi

# 2. Build the paste pack. Generation itself CANNOT be automated — this is a
#    finding, not a TODO. Proven end to end on 2026-09-21:
#      - Google refuses to complete a sign-in in an automation-controlled
#        browser ("Couldn't sign you in / may not be secure").
#      - Signing in with a normal Chrome works, but the first Playwright launch
#        against that profile INVALIDATES the session. Observed in sequence:
#        plain Chrome signed in -> Playwright signed out -> plain Chrome signed
#        out. Google binds the session to the browser.
#      - Chrome has blocked --remote-debugging-port on a real profile since 136
#        (this machine runs 153), so CDP into the founder's own Chrome is out.
#      - Copying cookies out of his main profile is credential material and was
#        deliberately not done.
#    flow-run.mjs is kept for its probe//selector work but is NOT called here;
#    calling it would burn six sign-in checks to produce nothing, which is how
#    the previous gap stayed invisible.
node make-paste-pack.mjs
RC=$?
if [ $RC -ne 0 ]; then
  say "⚠️  paste pack failed (exit=$RC)"
  say "=== veo-daily end (exit=$RC) ==="
  exit $RC
fi

PACK="$HOME/Desktop/Reports/NakshIQ-Veo-Paste-Pack-$(date +%F).html"
if [ -f "$PACK" ]; then
  say "pack ready: $PACK"
  # One notification, because a pack nobody opens is the same as no pack.
  osascript -e "display notification \"$PENDING clips ready to paste into Flow\" with title \"NakshIQ Veo\" sound name \"Ping\"" >/dev/null 2>&1 || true
fi

# 3. Sweep up anything generated by hand since the last run and ship it. Safe to
#    run every day: it no-ops when ~/Downloads holds nothing fresh, and pairing
#    refuses rather than mislabelling.
bash intake.sh || say "WARN intake failed"

say "=== veo-daily end (exit=0) ==="
exit 0
