-- Generated by scripts/build-blog-inserts.mjs on 2026-10-10
-- Run in Supabase Dashboard SQL Editor. One transaction covers all posts.

BEGIN;

-- is-mount-abu-in-december-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'mount-abu-december-verdict',
  'is-mount-abu-in-december-worth-it',
  'Is Mount Abu in December worth it?',
  'Peak winter at Rajasthan''s only hill station — cold mornings, full bookings, and a clean 10/10.',
  'best-time',
  'brief',
  2,
  '/images/destinations/mount-abu.jpg',
  ARRAY['verdict', 'mount-abu', 'december', 'rajasthan', 'hill-station'],
  ARRAY['mount-abu'],
  'Is Mount Abu in December worth it? Weather, crowds and the verdict',
  'Mount Abu in December scores 10/10 on our ledger — 8-22°C, clear skies, Guru Shikhar sunrises. Here is the honest read, the Christmas-week crowding, and what it costs.',
  'December scores a full 10/10 for Mount Abu — the peak of its winter run, with Christmas and New Year crowds from Gujarat to plan around. Here is what the month delivers, and what to book ahead.',
  '# Is Mount Abu in December worth it?

Short answer: yes. Our ledger scores [Mount Abu in December](/en/destination/mount-abu/december) at **10/10 — go**. It''s peak winter at Rajasthan''s only hill station, and the Christmas-New Year rush from Gujarat is the one thing worth planning around.

## What December actually looks like

Temperatures run a cold, clear 8-22°C — cool enough for a shawl at Nakki Lake in the evening, comfortable for every daytime stop on the circuit. Sunrise at Guru Shikhar, Rajasthan''s highest point at 1,722m, is the dataset''s specific callout for this month. The catch is timing: the Christmas and New Year window pulls heavy traffic from Ahmedabad and Vadodara, both a short drive away, and our note is direct about it — book accommodation at least two weeks ahead if your dates fall anywhere near the holidays.

## The context that matters

December isn''t an isolated good month — it''s the middle of a long run. October through February all score a clean **10/10** on our ledger, five consecutive months. March holds at 8/10 before April drops to 6/10 as the heat builds. May and June are the real low point at **4/10 — skip**: 28-38°C is unusually hot for a hill station, with little relief even at 1,220m elevation. July and August sit at 6/10 — monsoon greens the Aravallis and the waterfalls run, but it reads as a "wait," not a reason to go. September recovers to 8/10 as the rain eases.

So if your dates are flexible: any of October through February works about as well as December. The trade-off inside that window is crowds (heaviest around Christmas-New Year and Diwali-adjacent weekends) versus quiet (January, once the holiday rush clears).

## What it costs

Mount Abu''s peak-season pricing — which covers December — runs a mid-range hotel at a typical **₹2,700/night** (range ₹1,550-4,650), a homestay around ₹2,950, and a hostel dorm bed at ₹410. Food runs about ₹900 a day per person, and a full-day taxi is ₹2,100. Outside the Christmas-New Year peak, the same categories can run noticeably lower even within December''s own window — worth asking before booking. Full breakdown on the [cost page](/en/cost/mount-abu).

## Getting there

Mount Abu has no airport or railhead of its own — the nearest airport is Udaipur (160km) and the nearest railhead is Abu Road (28km), the last stretch by road. Most visits run 1-2 days, enough for Nakki Lake, the Dilwara Temples, and a Guru Shikhar sunrise.

## Verdict

- **Fixed December dates:** go — peak of a five-month good run, but book 2+ weeks ahead around Christmas and New Year.
- **Flexible dates:** January is the quieter equivalent once the holiday crowds clear; November and October trade a few degrees of warmth for lighter weekend traffic.
- **May–June:** skip. The heat genuinely erodes what a hill station is for.

Full month-by-month scoring for Mount Abu is on the [destination page](/en/destination/mount-abu).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-sissu-in-december-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'sissu-december-verdict',
  'is-sissu-in-december-worth-it',
  'Is Sissu in December worth it?',
  'The Atal Tunnel''s Lahaul side at 3,100m, mid-winter — our ledger says skip, and here''s the honest reason.',
  'best-time',
  'brief',
  2,
  '/images/destinations/sissu.jpg',
  ARRAY['verdict', 'sissu', 'december', 'himachal-pradesh', 'lahaul'],
  ARRAY['sissu'],
  'Is Sissu in December worth it? Why our ledger says skip',
  'Sissu in December scores 4/10 on our ledger — passes shut, most guesthouses closed, minimal services at 3,100m. Here is the honest read, and when to actually go instead.',
  'Sissu scores a 4/10 for December — our ledger''s plain read is that passes are shut and most guesthouses close at this elevation. Here is why, and which months actually work.',
  '# Is Sissu in December worth it?

Short answer: no, not without winter-specific planning. Our ledger scores [Sissu in December](/en/destination/sissu/december) at **4/10 — skip**. At 3,100m on the Lahaul side of the Atal Tunnel, December is deep winter, not a scenic edge case.

## Why the ledger says skip

Our note is direct: passes are shut, most guesthouses are closed, and services are minimal. Attempting Sissu in December without winter-specific plans — a 4x4, confirmed open accommodation, cold-weather gear — is described on our dataset as "asking for a rescue." This isn''t a mild-weather caution; at 3,100m, December cold is a real operational constraint, not just a comfort issue.

## What the rest of the year looks like

Sissu''s good months cluster tightly: May, June, September and October all score **10/10 — go**. April and November sit at 6/10 — workable but not peak, with November specifically flagged as the point where "high-altitude access winding down" starts to matter (Spiti''s Losar road, Ladakh''s Manali route and Zoji La all closing progressively through the month). July and August hold at 6/10 too, inside the monsoon window. January, February and March match December at 4/10 — the same deep-winter closures apply across the whole cold season, not just at year-end.

So this isn''t a case of December being an unlucky exception in an otherwise flexible calendar — it''s one end of a five-month closed season (December through March) bookending a reliable May-to-October window.

## What it costs, even at the cheapest point of the year

December falls in Sissu''s low season for pricing — rates are at their floor, not their peak. A mid-range hotel runs a typical **₹3,450/night** (range ₹1,950-5,950), a homestay around ₹1,050, and a hostel dorm bed at ₹380. Food runs about ₹700 a day. The low price is a symptom of the same problem the month-score flags: demand is low because access is restricted, not because it''s a secret bargain window. Full breakdown on the [cost page](/en/cost/sissu).

## Getting there

Sissu has no airport or railhead of its own — the nearest airport is Bhuntar, about 110km away via the Atal Tunnel, and the nearest railhead is Joginder Nagar, roughly 180km. That approach is exactly the kind of route that gets harder to rely on once winter closures set in.

## Verdict

- **Fixed December dates:** skip, or go in only with confirmed open accommodation and a winter-capable vehicle.
- **Flexible dates:** May, June, September and October are the four strong months — October for post-monsoon clarity, May-June for the Atal Tunnel''s full opening.
- **Shoulder option:** April or November, if you want the valley without peak crowds and can accept a narrower weather window.

Full month-by-month scoring for Sissu is on the [destination page](/en/destination/sissu).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- shikharji-height-and-parikrama-distance
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'shikharji-height-distance',
  'shikharji-height-and-parikrama-distance',
  'Shikharji height and parikrama distance: the real numbers',
  '1,365m at the summit, 27km for the full circuit, done in one hard day — here''s what our trek dataset logs.',
  'guide',
  'brief',
  2,
  '/images/destinations/shikharji.jpg',
  ARRAY['guide', 'shikharji', 'parasnath', 'trek', 'jharkhand', 'pilgrimage'],
  ARRAY['shikharji'],
  'Shikharji height and parikrama distance — 1,365m, 27km, one day',
  'Shikharji''s summit sits at 1,365m, and the sacred parikrama circuit covers 27km in a single day — rated hard difficulty on our dataset. Here is the real number, and when to climb it.',
  'Shikharji''s summit sits at 1,365m, with a 27km single-day parikrama rated hard on our dataset. Here is the real distance, the elevation gain, and the months that make the climb manageable.',
  '# Shikharji height and parikrama distance: the real numbers

Short answer: **1,365m** at the summit, and the full parikrama (sacred circuit) covers **27km**, done in a single day, rated **hard** difficulty. This is Shri Sammed Shikharji — Parasnath hill in Jharkhand''s Giridih district — one of Jainism''s most important pilgrimage sites, and the numbers surprise people who expect a short temple visit rather than a full day on the trail.

## The numbers

Our trek dataset logs the Shikharji Parikrama as a 27km route completed in one day, with a maximum altitude of 1,365m, rated hard. That''s not a typo-friendly "easy half-day" climb — it''s a genuinely demanding single push, usually started before dawn so pilgrims can complete the full circuit of temples (there are more than 20 along the route) and descend before dark.

Shikharji the destination sits at that same 1,365m elevation — the summit figure and the destination elevation line up, since the hill itself is the pilgrimage site. There''s no separate "base camp" elevation in our data to subtract from; the climb essentially starts near the base town and gains most of its height across the full 27km loop rather than in one short steep stretch.

## When to actually attempt it

Our best-months data for Shikharji covers October through March — six months, not a narrow window. That''s a wider good-weather season than most high-altitude treks get, because Parasnath hill''s 1,365m elevation means it never faces the snow-closure problem that shuts down treks above 3,000m. The constraint here is heat and humidity, not snow: Jharkhand''s pre-monsoon and monsoon months (April through September) aren''t in the dataset''s recommended window, which tracks with a 27km single-day hard route being far tougher in heat and humid air than in cool winter conditions.

## What it costs

Shikharji''s peak season (October through March) runs a mid-range hotel at a typical **₹3,150/night** (range ₹1,800-5,400), a homestay around ₹1,850, and a hostel dorm bed at ₹350. Food runs about ₹700 a day, and a full-day taxi is ₹1,650. Outside peak, the same categories drop substantially — a mid-range room falls to roughly ₹1,500. Full breakdown on the [cost page](/en/cost/shikharji).

## Getting there

Shikharji''s nearest railhead is Parasnath station, just 15km away — the closer option by far. The nearest airport is Ranchi, about 180km. Most visits run 1-2 days: one day for the parikrama itself, with an optional extra day to rest before or after given the climb''s difficulty.

## The one-line answer

1,365m at the summit, 27km for the full parikrama, one hard day — climb it October through March, and start before dawn.

Full destination details for Shikharji are on the [destination page](/en/destination/shikharji).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- agra-ghumne-ka-kharcha
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'agra-cost-hindi',
  'agra-ghumne-ka-kharcha',
  'आगरा घूमने का खर्च — सीज़न के हिसाब से असली आंकड़े',
  'ताजमहल देखने के बजट से लेकर होटल, खाना और टैक्सी तक, पूरा हिसाब',
  'guide',
  'brief',
  2,
  '/images/destinations/agra.jpg',
  ARRAY['cost', 'agra', 'hindi', 'budget', 'uttar-pradesh'],
  ARRAY['agra'],
  'आगरा घूमने का खर्च — होटल, खाना, टैक्सी के सीज़न-वार आंकड़े',
  'आगरा घूमने का खर्च कितना है? पीक सीज़न में मिड-रेंज होटल ₹2,700/रात, खाना ₹1,250/दिन, डे-टैक्सी ₹1,800। बजट से लग्ज़री तक पूरा हिसाब और 2 दिन की सैंपल ट्रिप।',
  'आगरा में पीक सीज़न (अक्टूबर, नवंबर, दिसंबर, फरवरी, मार्च) का मिड-रेंज होटल ₹2,700/रात के आसपास बैठता है। पूरा सीज़न-वार हिसाब, और 2 दिन की ट्रिप का असली अनुमान।',
  '# आगरा घूमने का खर्च — सीज़न के हिसाब से असली आंकड़े

आगरा का खर्च सीज़न के साथ काफ़ी बदलता है। नीचे के आंकड़े हमारे रेट-लेज़र से हैं, वही जो [आगरा के कॉस्ट पेज](/hi/cost/agra) पर चलता है।

## पहले सीज़न समझिए

- **पीक:** अक्टूबर, नवंबर, दिसंबर, फरवरी, मार्च — ठंडा और साफ़ मौसम, सबसे ज़्यादा भीड़ और रेट।
- **शोल्डर:** जनवरी, अप्रैल, सितंबर — बीच का रास्ता, रेट भी बीच में।
- **लो:** मई, जून, जुलाई, अगस्त — भीषण गर्मी और मॉनसून, रेट सबसे कम लेकिन ताजमहल देखने के लिए सुबह जल्दी निकलना ज़रूरी हो जाता है।

आगरा की ऊंचाई सिर्फ़ 171 मीटर है, तो यह मौसम में भी ज़्यादा उतार-चढ़ाव वाली जगह है — पहाड़ी destinations की तरह ठंड से बचाव नहीं मिलता।

## ठहरने का खर्च (प्रति रात)

| श्रेणी | पीक सीज़न | शोल्डर | लो सीज़न |
| --- | --- | --- | --- |
| होस्टल डॉर्म | ₹400 (₹210–780) | ₹300 | ₹190 |
| बजट होटल | ₹1,000 (₹550–1,750) | ₹750 | ₹500 |
| मिड-रेंज होटल | ₹2,700 (₹1,500–4,650) | ₹2,000 | ₹1,300 |
| होमस्टे | ₹2,750 (₹1,350–5,700) | ₹2,050 | ₹1,350 |
| लग्ज़री होटल | ₹12,100 (₹7,050–30,600) | ₹9,050 | ₹5,900 |

ताजमहल के पास के इलाक़ों में होटल रेट हमेशा थोड़ा ज़्यादा होते हैं — रेलवे स्टेशन या बस स्टैंड के आसपास ठहरना सस्ता पड़ता है।

## रोज़ का खर्च

| मद | पीक सीज़न | शोल्डर | लो सीज़न |
| --- | --- | --- | --- |
| खाना (प्रति व्यक्ति, प्रति दिन) | ₹1,250 | ₹1,250 | ₹1,250 |
| पूरे दिन की टैक्सी | ₹1,800 | ₹1,800 | ₹1,800 |
| इंटरसिटी किराया (स्लीपर बस / 2nd AC, एक तरफ़) | ₹1,450 | ₹1,150 | ₹950 |
| एक्टिविटी (सैंपल, जैसे मोन्यूमेंट टिकट) | ₹2,050 | ₹1,450 | ₹950 |

खाना और डे-टैक्सी का रेट हमारे लेज़र पर पूरे साल एक जैसा है — यह मौसम से नहीं बदलता, सिर्फ़ ठहरने और इंटरसिटी किराए में फ़र्क़ आता है।

## 2 दिन की ट्रिप — दो असली अनुमान

**कपल, मिड-रेंज, नवंबर (पीक), 2 दिन / 1 रात:** होटल ₹2,700 + खाना (दो दिन, दो लोग) ₹5,000 + एक दिन टैक्सी ₹1,800 + आना-जाना (2 लोग, दोनों तरफ़) ₹5,800 = **लगभग ₹15,300**।

**अकेले, बजट, लो सीज़न (जून), 2 दिन / 1 रात:** बजट होटल ₹500 + किफ़ायती खाना ₹1,000 + आना-जाना ₹1,900 + लोकल ऑटो/वॉक = **लगभग ₹3,400–3,800**।

(यह अनुमान मुख्य हब से इंटरसिटी किराए पर आधारित है — आगरा का अपना रेलवे स्टेशन आगरा कैंट है, और नज़दीकी एयरपोर्ट आगरा खेरिया है।)

## पैसा बचाने के तीन ईमानदार तरीके

1. **पीक महीनों से बचिए अगर बजट टाइट है** — अक्टूबर-मार्च में होटल रेट मिड-रेंज में दोगुने तक हो जाते हैं; शोल्डर महीने (जनवरी, अप्रैल, सितंबर) में मौसम अभी भी ठीक रहता है, रेट कम।
2. **डे-ट्रिप का विकल्प देखिए** — ताजमहल और आगरा फोर्ट एक दिन में कवर हो सकते हैं, तो एक रात का होटल खर्च भी बचाया जा सकता है।
3. **खाना और टैक्सी का रेट साल भर एक जैसा है** — यहां मौसम के हिसाब से मोलभाव की गुंजाइश कम है, असली बचत ठहरने के चुनाव में ही है।

पूरा सीज़न-वार कैलकुलेटर [आगरा के कॉस्ट पेज](/hi/cost/agra) पर है, और महीने-दर-महीने की रेटिंग [आगरा के डेस्टिनेशन पेज](/hi/destination/agra) पर।',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- kedarnath-in-late-october-crowds
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'kedarnath-october-crowds',
  'kedarnath-in-late-october-crowds',
  'Kedarnath in late October: crowds, darshan, and the road',
  'The temple is quiet this time of year. The highway getting there, as of early October, was not.',
  'guide',
  'brief',
  3,
  '/images/destinations/kedarnath.jpg',
  ARRAY['guide', 'kedarnath', 'october', 'uttarakhand', 'pilgrimage', 'crowds'],
  ARRAY['kedarnath'],
  'Kedarnath in late October: crowd levels and road conditions',
  'Kedarnath in October scores 10/10 on our ledger — cold, clear, and historically the quietest darshan of the open season. But the approach road saw real pilgrim-traffic jams in early October 2026. Here is both sides, honestly.',
  'Kedarnath in October is our ledger''s top month for a relaxed darshan — but the approach highway logged real multi-hour jams in early October 2026. Here is what each source actually says, with dates.',
  '# Kedarnath in late October: crowds, darshan, and the road

Short answer: at the temple itself, October is historically the calmest month of the open season. On the road getting there, conditions can be genuinely congested — a documented jam hit the approach highway as recently as October 4, 2026. Both things are true, and they''re not the same question.

## What the month usually looks like

Our ledger scores [Kedarnath in October](/en/destination/kedarnath/october) at **10/10 — go**, and the note is specific: 0-8°C, clear skies, snow-dusted peaks, and "tiny queues" at the shrine itself. The season''s rush has thinned out by this point — most of the May-to-June and September surge has passed — and the write-up calls October "arguably the cleanest month up here," with maximum visibility and the last of the full-service season before the temple closes for winter in mid-November. If your question is specifically about standing in line for darshan, the historical pattern says it should be short.

## What the road looked like on October 4, 2026

A separate, more recent signal complicates the "quiet month" picture. A road update dated October 4, 2026 reported 3-4 hour jams on the Rudraprayag-Srinagar highway and the Phata-Sonprayag stretch, driven by over 15,000 pilgrims and 6,000-7,000 vehicles using the 75km Rudraprayag-Gaurikund route daily during what was described as the yatra''s "second phase." The worst congestion was at the Sirombagarh sliding zone, Dhari Devi, and a 6km single-lane section between Sonprayag and Gaurikund.

That''s a real, dated data point — not a general seasonal comment — and it means the approach can bottleneck even in a month where the temple queue itself is short. Treat it as current as of its own date (October 4, 2026) rather than a permanent condition: road status on mountain routes changes week to week, and we don''t have a dated reading closer to late October specifically.

## What this means for a late-October trip

- **At the shrine:** the historical pattern favors you — October is the ledger''s top-scoring month specifically because the crowds that define May-June and September have eased.
- **On the approach:** budget extra time on the Rudraprayag-Gaurikund stretch, especially around the single-lane Sonprayag-Gaurikund section, and don''t assume the drive will match the shrine''s calm.
- **On operators:** we don''t have verified data on specific tour operators for this route, so we''re not going to name any — that''s a question worth putting directly to other recent travelers rather than taking a brochure''s word for it.
- **On timing:** the temple closes for the season in mid-November, so late October still sits inside the open window, with the cold already setting in per the month''s 0-8°C range.

## What it costs

October falls in Kedarnath''s peak season for costs. A mid-range hotel runs a typical **₹3,400/night** (range ₹1,950-5,800), a homestay around ₹3,600, and a hostel dorm bed at ₹700. Food runs about ₹800 a day, and a full-day taxi is ₹3,250. Full breakdown on the [cost page](/en/cost/kedarnath).

## Getting there

Kedarnath''s nearest airport is Dehradun (Jolly Grant); the nearest railhead is Rishikesh or Haridwar, both well short of the trek itself. Most visits run 2-4 days, which accounts for the approach, the climb, and a buffer for exactly the kind of highway delay reported in early October.

Full month-by-month scoring for Kedarnath is on the [destination page](/en/destination/kedarnath).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

COMMIT;
