-- Generated by scripts/build-blog-inserts.mjs on 2026-08-22
-- Run in Supabase Dashboard SQL Editor. One transaction covers all posts.

BEGIN;

-- is-varkala-in-october-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'varkala-october-verdict',
  'is-varkala-in-october-worth-it',
  'Is Varkala in October worth it?',
  'The cliff strip reopens October 1 — what''s actually rebuilt by the time you land.',
  'best-time',
  'brief',
  2,
  '/images/destinations/varkala.jpg',
  ARRAY['verdict', 'varkala', 'october', 'kerala', 'weather'],
  ARRAY['varkala'],
  'Is Varkala in October worth it? Season opening, weather, and what''s still rebuilding',
  'Varkala in October scores 8/10 on our ledger — go. The season opens October 1 with dry 24-31C weather and calm seas, but the North Cliff strip takes until mid-month to fully reopen.',
  'October 1 is when Varkala''s season officially opens after monsoon. Our ledger scores it 8/10 — go — but the cliff strip isn''t at full strength on day one. Here''s what''s actually open when.',
  '# Is Varkala in October worth it?

Short answer: our ledger scores [Varkala in October](/en/destination/varkala/october) at **8/10 — go**. The monsoon closure lifts on October 1, the sea calms down, and this is the first month of the season that actually works.

## What changes on October 1

Varkala runs on a hard seasonal switch. June through August score **2/10 — skip**: the beach is unsafe, the cliff-edge zone is actively eroding, and most shacks are shut for the monsoon. September is a **4/10 — wait**, a rebuild month where the sea is still rough for most of it and cafes are under reconstruction. October is where that changes — dry 24–31°C weather returns, the sea settles to a swimmable 27°C, and post-monsoon rain tapers to 100–200mm by month''s end.

The catch worth knowing before you book: the North Cliff strip isn''t at full capacity from day one. Our data notes it reaches full strength — yoga retreats, Ayurveda centres, clifftop shack restaurants all running — by **mid-month**, not the 1st. If you''re flying in for October 2 or 3, expect a quieter, still-reopening version of the strip rather than the full high-season set-up.

## Who this month actually suits

The ledger''s read on October is specific: yoga and meditation retreat-goers, spiritual travellers drawn to the cliffside temples, and coastal photographers get the most out of this window — arriving early enough to have the place before peak-season crowds, without the risk that comes with September''s still-recovering sea. There''s no flagged group who should avoid the month; this is Varkala''s most balanced opening.

## Planning around it

Varkala sits at just 15m elevation on the Kerala coast, reached via Trivandrum International Airport (50km) or the Varkala railway station directly in town. The ideal stay is 2–4 days — enough for the cliff walk, a couple of beach days, and a yoga session or two without over-extending a beach town that rewards a slower pace over a packed itinerary.

Budget days run near ₹1,500, midrange closer to ₹4,000, with luxury stretching to ₹10,000 — a wide enough range that the choice is really about which part of the cliff strip you want to be based on. [Full cost breakdown here](/en/cost/varkala).

## Verdict

- **Early October (1st–10th):** go, but expect a partially-reopened cliff strip — fewer shacks, quieter crowds, still worth it for the weather alone.
- **Mid-to-late October:** the safer bet if you want the full strip experience — retreats, cafes, and restaurants all running.
- **Booking around Onam or peak season pricing:** October is pre-peak, so this is also the cheapest of the good months before November-March rates climb.

Full month-by-month scoring is on the [Varkala destination page](/en/destination/varkala).',
  '2026-07-02 04:30:00+00', NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-somnath-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'somnath-august-verdict',
  'is-somnath-in-august-worth-it',
  'Is Somnath in August worth it?',
  'The Jyotirlinga never closes for monsoon — but the beach and the road might not cooperate.',
  'best-time',
  'brief',
  2,
  '/images/destinations/somnath.jpg',
  ARRAY['verdict', 'somnath', 'august', 'gujarat', 'weather'],
  ARRAY['somnath'],
  'Is Somnath in August worth it? Monsoon weather, darshan queues, and what to skip',
  'Somnath in August scores 6/10 on our ledger — wait, not skip. Heavy rain limits the beach and some roads from Junagadh and Veraval, but darshan queues are at their annual low.',
  'Somnath''s Jyotirlinga temple never shuts for monsoon, and August has the year''s shortest darshan queues. Our ledger scores it 6/10 — wait — here''s the actual trade-off.',
  '# Is Somnath in August worth it?

Short answer: our ledger scores [Somnath in August](/en/destination/somnath/august) at **6/10 — wait**. The temple stays open through monsoon and this is the quietest the pilgrimage gets all year, but heavy rain closes off the parts of the trip that aren''t the temple itself.

## What actually happens in August

Somnath sits right on the Arabian Sea at just 10m elevation, which means monsoon here isn''t a mild inconvenience — it''s the defining fact of the month. Our data calls it "deep monsoon": heavy rain and strong swells make the beach unusable, and the same weather can disrupt road access from Junagadh and Veraval. Humidity runs high and outdoor sightseeing beyond the temple complex is limited.

Against that: the Jyotirlinga temple never closes, and August is when darshan queues hit their annual low. Room rates drop with the crowds. The ledger''s note calls the rain-soaked coastline "raw" and "atmospheric" — a real quality, if you''re the kind of pilgrim who values a quiet temple visit over comfortable sightseeing around it.

## Who the month suits

Our data flags four groups who get real value from an August trip: monsoon-atmosphere photographers, Janmashtami pilgrims tracking the wider Krishna circuit, quiet-temple seekers, and travellers who don''t mind heavy rain. On the other side, beach travellers, anyone on a tight schedule, children-focused itineraries, and light-rain-only travellers are flagged to avoid the month — the beach closure and transport risk hit those groups hardest.

## What comes next, if you can wait

September eases slightly — 25–31°C, the same 6/10 wait verdict, with the sea calming toward late month and Saurashtra travel logistics starting to normalise, though residual monsoon showers and rough-sea days are still possible early on. October is where the ledger turns to **8/10 — go**: 24–33°C, post-monsoon weather returning, the sea calm and breezy, and the opening month of the November–February peak pilgrimage season.

## Planning around it

Somnath is reached via Diu airport (80km) or Veraval railway station, just 7km away. It''s a short trip by design — 1 to 2 days covers the temple and the immediate area. This is also one of the most affordable stops on our ledger: budget days run near ₹750, midrange around ₹2,200, with dharamshala pilgrim lodging keeping costs low even in the luxury tier at ₹6,600. [Full cost breakdown here](/en/cost/somnath).

## Verdict

- **Pilgrimage-only trip, flexible dates:** wait for October — same temple, none of the rain risk.
- **Fixed August dates, or specifically chasing the quiet queues:** go, but build in a buffer day for the Junagadh–Veraval road and don''t plan on the beach.
- **Combining with a wider Gujarat coastal itinerary:** wait — August limits too much of the "around Somnath" portion of that trip.

Full month-by-month scoring is on the [Somnath destination page](/en/destination/somnath).',
  '2026-07-06 07:15:00+00', NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-chikmagalur-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'chikmagalur-august-verdict',
  'is-chikmagalur-in-august-worth-it',
  'Is Chikmagalur in August worth it?',
  'NH-73 is stabilising and Hebbe Falls is at peak flow — but the summit road still isn''t open.',
  'best-time',
  'brief',
  2,
  '/images/destinations/chikmagalur.jpg',
  ARRAY['verdict', 'chikmagalur', 'august', 'karnataka', 'weather', 'monsoon'],
  ARRAY['chikmagalur'],
  'Is Chikmagalur in August worth it? Monsoon roads, waterfalls, and the September case',
  'Chikmagalur in August scores 4/10 on our ledger — wait. NH-73 stabilises as rainfall eases to 600-800mm, but Mullayanagiri''s summit road stays closed most days. September opens it up.',
  'August in Chikmagalur is still monsoon, just a slightly calmer version of July''s. Our ledger scores it 4/10 — wait. Here''s what''s actually open, and why September changes the calculus.',
  '# Is Chikmagalur in August worth it?

Short answer: our ledger scores [Chikmagalur in August](/en/destination/chikmagalur/august) at **4/10 — wait**. The southwest monsoon is still running — 16–25°C with 600–800mm of rain — and it holds the same pattern as July rather than breaking from it.

## What''s open and what isn''t

NH-73, the road most visitors rely on, is stabilising rather than reliably clear — our data notes closures still run 1–2 days a week. The Mullayanagiri summit road stays shut most days through the month. What does work: Hebbe Falls reaches peak flow and is visible from the base even without the summit access, and the plantation canopy is at its most saturated green, offering natural shelter from the rain if you''re moving between coffee estates rather than trying to summit anything.

The ledger is direct about who this suits: monsoon waterfall photographers and adventurous trekkers comfortable with mud get real value from August. Families, casual hikers, and anyone uncomfortable with landslide-prone roads are flagged to wait.

## Why September is the better bet if your dates are flexible

One month out, the picture changes meaningfully. [September](/en/destination/chikmagalur/september) scores **8/10 — go**: the monsoon retreats, rainfall eases to 300–500mm, and Mullayanagiri reopens. [October](/en/destination/chikmagalur/october) holds at **10/10 — go**, the full season opening at 14–26°C with plantations still at their greenest from the residual northeast monsoon. Both months keep the lush, just-rained look that draws people to Chikmagalur in the first place, minus the road closures.

## Planning around it

Chikmagalur sits at 1,090m in the Coorg & Chikmagalur region of Karnataka, reached via Mangalore Airport (152km) or Bangalore Airport (250km), with Kadur railway station the closer railhead at 40km. The ideal stay is 2–3 days.

Plantation homestays with meals are the standout value here, typically ₹2,000–4,000 a night. Budget days on the whole run near ₹1,500, midrange around ₹4,600, luxury up to ₹10,600. [Full cost breakdown here](/en/cost/chikmagalur).

## Verdict

- **Flexible dates:** wait for September or October — same green landscape, none of the road-closure risk, and the summit actually opens.
- **Fixed August dates, comfortable with mud and rain:** go for the waterfalls specifically, but don''t plan around reaching Mullayanagiri''s summit.
- **Traveling with kids, or on a tight timeline that can''t absorb a closed road day:** wait.

Full month-by-month scoring is on the [Chikmagalur destination page](/en/destination/chikmagalur).',
  '2026-07-09 05:20:00+00', NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-gurez-valley-in-september-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'gurez-valley-september-verdict',
  'is-gurez-valley-in-september-worth-it',
  'Is Gurez Valley in September worth it?',
  'Our ledger''s cleanest score of the year for this valley — here''s what makes September different from August or October.',
  'best-time',
  'brief',
  2,
  '/images/destinations/gurez-valley.jpg',
  ARRAY['verdict', 'gurez-valley', 'september', 'kashmir', 'weather'],
  ARRAY['gurez-valley'],
  'Is Gurez Valley in September worth it? The best-scoring month, explained',
  'Gurez Valley in September scores a clean 10/10 on our ledger — go. Post-monsoon clarity, golden meadows, and Habba Khatoon peak sharp against the sky, before Razdan Pass risk sets in.',
  'September is the one month our ledger scores Gurez Valley a clean 10/10. Post-monsoon air, golden meadows, and none of October''s pass-closure risk. Here''s why.',
  '# Is Gurez Valley in September worth it?

Short answer: our ledger scores [Gurez Valley in September](/en/destination/gurez-valley/september) at a clean **10/10 — go**. It''s the single best-scoring month of the year for this valley, and the reason comes down to timing rather than any one feature.

## Why September is the peak, not August or October

Gurez only functions as a destination for part of the year — it sits at 2,400m in Bandipora district, reached from Srinagar (123km) over the Razdan Pass, a road open June through October only. Within that window, September is where three things line up at once: monsoon has fully retreated, giving 5–20°C weather with the year''s best air clarity; the meadows have turned golden; and operators are still running full service, unlike October when the season is visibly winding down.

Our data''s note is unusually direct about this: "photography paradise. Go now." Habba Khatoon peak stands out sharp against clear skies, the Kishanganga river runs calm, and the valley is described as India''s most photogenic in this specific window — a claim tied to the September light and colour, not a general endorsement of the destination.

[August](/en/destination/gurez-valley/august) still scores well at **8/10 — go**, pleasant at 10–25°C with good camping weather, but hasn''t yet turned golden and carries slightly more crowd overlap with peak summer. [October](/en/destination/gurez-valley/october) drops to **6/10 — wait**: genuinely the cleanest visibility of the year, but the Razdan Pass can close with the first snowfall on any given day, and that risk is the whole story of the month.

## Who September suits, and who shouldn''t come

The ledger flags photographers first — this is described as the month Gurez earns its reputation, full stop — along with autumn-colour seekers chasing golden chinar and walnut trees against snow peaks, and repeat Kashmir visitors who want the valley without July–August''s peak-season crowd numbers. It''s explicitly not a kids destination (scored 4.0/10 separately). Three groups are flagged to think twice: anyone who can''t handle 5°C dawns without proper layers, travellers without confirmed road status (late-September closures do happen, just less often than October), and last-minute planners — there''s no expedited process for the army permits this valley requires.

## Planning around it

Gurez has no luxury stays and minimal infrastructure — this is a genuinely remote, restricted-access valley. Budget days run near ₹1,700, midrange around ₹4,600, with a transport line of ₹1,500+ reflecting the rough Bandipora road. [Full cost breakdown here](/en/cost/gurez-valley).

## Verdict

- **Photography-focused trip, flexible dates:** September is the month — don''t substitute October for "cleaner light," the pass risk isn''t worth it.
- **Traveling with kids or elderly:** the valley itself works in September, but infrastructure is thin regardless of month; plan accordingly.
- **Permits not yet arranged:** start now — there''s no fast-track process, and September books up given the reputation.

Full month-by-month scoring is on the [Gurez Valley destination page](/en/destination/gurez-valley).',
  '2026-07-13 08:05:00+00', NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-sabarimala-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'sabarimala-august-verdict',
  'is-sabarimala-in-august-worth-it',
  'Is Sabarimala in August worth it?',
  'The temple is barely open this month, and Onam doesn''t change that.',
  'best-time',
  'brief',
  2,
  '/images/destinations/sabarimala.jpg',
  ARRAY['verdict', 'sabarimala', 'august', 'kerala', 'pilgrimage'],
  ARRAY['sabarimala'],
  'Is Sabarimala in August worth it? Temple hours, monsoon access, and when to actually go',
  'Sabarimala in August scores 2/10 on our ledger — skip. The temple is closed except for a brief monthly darshan window, and monsoon floods can make the pilgrimage route impassable.',
  'Sabarimala''s temple is open for a matter of hours in August, and the monsoon can flood the pilgrimage route entirely. Our ledger scores it 2/10 — skip. Here''s when it actually opens.',
  '# Is Sabarimala in August worth it?

Short answer: our ledger scores [Sabarimala in August](/en/destination/sabarimala/august) at **2/10 — skip**. This isn''t a weather-comfort call — the temple itself is closed for nearly all of the month.

## Why the temple is the whole story here

Sabarimala doesn''t run on a typical open-season calendar. Our data notes the temple is closed except for a brief window on the first day of the Malayalam calendar month — a matter of hours, not a full-access period. August compounds that with monsoon: rains continuing through the month can make the pilgrimage routes into the hills impassable outright, on top of the temple already being shut.

It''s worth clearing up a common assumption directly, because our data addresses it head-on: Onam, the major Kerala festival that often falls in August or early September, is **not Sabarimala-anchored**. There''s no festival-driven reason to time a trip here around it. The ledger''s verdict list for who should go this month is empty. Who should avoid it: everyone.

## When the temple is actually worth visiting

That "everyone avoid" verdict holds through September too — still closed except the same brief monthly window, monsoon trails still slippery, and September specifically carries peak pilgrim crowds tied to the run-up to the sacred season rather than genuine access. October doesn''t improve matters either: it''s pre-Mandala closure, with the temple opening only for that same one-day-a-month window until Mandala season itself opens **November 16–17**.

That date is the real answer to "when should I go instead." The Mandala–Makaravilakku pilgrimage season, running roughly mid-November through mid-January, is when Sabarimala actually functions as a destination — full access, the infrastructure built for it, and the reason the shrine draws the numbers it does.

## Planning around it

Sabarimala sits at 914m elevation in Kerala, reached via Cochin International Airport (170km) or Kottayam railway station (100km). The ideal stay, once the season is open, is short — 1 to 2 days. Costs stay simple year-round: budget pilgrimage stays run near ₹800 a day, midrange closer to ₹1,500. [Full cost breakdown here](/en/cost/sabarimala).

## Verdict

- **Any date between May and October:** skip, no exceptions — the temple access alone rules the trip out regardless of what else lines up.
- **Planning around Onam specifically:** skip — the festival has no Sabarimala tie-in; celebrate it elsewhere in Kerala instead.
- **Flexible dates:** wait for the Mandala season opening in mid-November, when the pilgrimage actually functions as one.

Full month-by-month scoring is on the [Sabarimala destination page](/en/destination/sabarimala).',
  '2026-07-16 04:55:00+00', NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

COMMIT;
