-- Generated by scripts/build-blog-inserts.mjs on 2026-09-17
-- Run in Supabase Dashboard SQL Editor. One transaction covers all posts.

BEGIN;

-- is-varanasi-in-october-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'varanasi-october-verdict',
  'is-varanasi-in-october-worth-it',
  'Is Varanasi in October worth it?',
  '10/10 on the NakshIQ scale — the month the peak season opens',
  'best-time',
  'brief',
  4,
  '/images/destinations/varanasi.jpg',
  ARRAY['verdict', 'uttar-pradesh', 'varanasi', 'october', 'best-time'],
  ARRAY['varanasi'],
  'Is Varanasi in October Worth It? The Honest Verdict',
  'Varanasi scores a clean 10/10 for October in NakshIQ''s dataset — the first month of its six-month peak window. Here''s the weather, the crowd math, and what a night actually costs.',
  'October is the month NakshIQ''s Varanasi dataset opens its peak window — a full 10/10, the highest score the destination gets. Here''s the honest read on why, and the number to budget.',
  '# Is Varanasi in October worth it?

Yes. **Verdict: go.** October is the opening month of NakshIQ''s longest peak window for Varanasi — the dataset scores it a clean 5 out of 5, 10/10 on the site''s displayed scale, and holds that score all the way through March.

## What changes in October

Varanasi''s [month-by-month page](/en/destination/varanasi/october) logs the shift plainly: temperatures ease to 22–32°C, the post-monsoon skies clear, and the ghats — swollen and partly submerged through the rains — re-emerge fully walkable. The dataset ties October to the start of the region''s festival calendar: Dussehra and the run-up to Diwali fall inside the month, and Ganga Aarti at Dashashwamedh Ghat is logged as running at its most elaborate. It''s the version of Varanasi that shows up in most cultural photography and documentary work — the one the site says the month is "built for."

By contrast, the preceding low season (May through August) scores lower across the same dataset: the Ganga runs high, heat sits in the mid-30s to 40s, and several ghats stay partially underwater. October is the clean handoff out of that window, not a marginal improvement on it.

## What it costs

Hotels step up to Varanasi''s peak-season pricing in October, alongside the five months that follow it. A mid-range double runs a typical ₹5,200 a night (range ₹3,000–9,000), up from ₹2,350 in the May–August low season. A homestay typically comes in around ₹3,000, and a hostel dorm bed runs about ₹700. Food averages ₹1,100 a day per person. A day taxi is the steepest jump — ₹4,100 versus ₹1,850 off-peak — since ghat-to-ghat routing gets busier as the pilgrim and tourist calendar fills. Full breakdown, category by category, on the [Varanasi cost page](/en/cost/varanasi).

## Who it suits, and the trade-off

The dataset marks October as manageable with older kids (6/10) rather than a natural family pick — the ghats, the crowd density, and the early-morning boat rituals reward travelers who can walk long stretches and sit through slow, unstructured mornings. Varanasi''s ideal stay runs 2–4 days, enough to work the ghats at both dawn and dusk without rushing.

The catch is booking pressure, the same one that shows up in most first-of-peak months: October opens the six-month window that carries Varanasi through winter, so rooms near the ghats fill early and last-minute rates run above the typical figures above. Varanasi Junction and Lal Bahadur Shastri airport both handle the month''s traffic without issue — the constraint is accommodation, not access.

## The one-line answer

NakshIQ''s data doesn''t hedge on this one: October is a top-scoring month for Varanasi, not a shoulder-season compromise — book the ghat-facing room early, since the peak window has just opened and everyone chasing the same clear skies is looking at the same six months.',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-rishikesh-in-september-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'rishikesh-september-verdict',
  'is-rishikesh-in-september-worth-it',
  'Is Rishikesh in September worth it?',
  '8/10 on the NakshIQ scale — the month rafting season reopens',
  'best-time',
  'brief',
  4,
  '/images/destinations/rishikesh.jpg',
  ARRAY['verdict', 'uttarakhand', 'rishikesh', 'september', 'best-time'],
  ARRAY['rishikesh'],
  'Is Rishikesh in September Worth It? The Honest Verdict',
  'Rishikesh scores 8/10 for September in NakshIQ''s dataset — the month the Ganga settles enough for rafting to reopen. Here''s the weather, the crowd math, and what a night actually costs.',
  'September is the month NakshIQ''s Rishikesh dataset opens back up after the monsoon — 8/10, the start of a five-month run through November and into spring. Here''s the honest read, and the number to budget.',
  '# Is Rishikesh in September worth it?

Yes, with a caveat on timing. **Verdict: go.** NakshIQ''s dataset scores September a 4 out of 5 — 8/10 — for Rishikesh, marking it as the first month of the site''s peak window after two months (July–August) it explicitly flags to avoid.

## What the score is measuring

Rishikesh''s [month-by-month page](/en/destination/rishikesh/september) tracks the direct effect of the monsoon''s retreat: temperatures settle to 20–30°C, the Ganga drops from its monsoon flood level to a runnable state, and white-water rafting — shut through July and August on safety grounds — reopens as the river settles. The dataset calls out September specifically as what it''s "built for": white-water rafters get one of the first clean windows of the season, and the hillsides are still green from the rains rather than the dustier look later months can carry.

October and November score marginally higher in the same dataset — October hits a full 10/10 as the cleanest month of the year — so if your dates are flexible by a few weeks, that''s worth knowing. But September is the first month back on the "go" side of the ledger, not a compromise ahead of the better months.

## What it costs

September sits inside Rishikesh''s five-month peak season (alongside October, November, March, and April) for pricing. A mid-range hotel runs a typical ₹5,500 a night (range ₹3,200–9,400), a homestay around ₹3,200, and a hostel dorm bed about ₹900. Food averages ₹1,150 a day. A day taxi runs ₹4,400 versus ₹1,950 in the July–August low season — the clearest sign the month has already flipped into demand mode. Full breakdown on the [Rishikesh cost page](/en/cost/rishikesh).

## Who it suits

The dataset rates September manageable with older kids (6/10), and the return of rafting is the headline draw — the activity most visitors are timing the trip around. Dehradun''s Jolly Grant airport and the Rishikesh/Haridwar railheads both run normal service by this point in the season. Ideal stay length is 2–4 days, enough to combine a rafting run with the ashram and ghat side of the town.

## The trade-off, stated plainly

The river is settling, not settled — operators run trips once conditions clear, but early September can still carry some residual monsoon runoff depending on the year. If the rafting grade matters more than the exact date, check current river conditions before locking a trip in the first half of the month.

## The one-line answer

NakshIQ''s data puts September back on the "go" side after two months it explicitly rules out — book once you''ve confirmed river conditions, and expect peak-season pricing from day one of the month.',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-chitkul-in-september-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'chitkul-september-verdict',
  'is-chitkul-in-september-worth-it',
  'Is Chitkul in September worth it?',
  '10/10 on the NakshIQ scale — the post-monsoon reveal at India''s last road-connected village',
  'best-time',
  'brief',
  4,
  '/images/destinations/chitkul.jpg',
  ARRAY['verdict', 'himachal', 'chitkul', 'september', 'best-time'],
  ARRAY['chitkul'],
  'Is Chitkul in September Worth It? The Honest Verdict',
  'Chitkul scores a clean 10/10 for September in NakshIQ''s dataset — one of only three months that rate this high. Here''s the weather, the crowd math, and what a night actually costs.',
  'September is one of three months NakshIQ''s Chitkul dataset scores a clean 10/10. Post-monsoon clarity, Kinnauri wooden architecture, and the last of the full-service season before the cold sets in. Here''s the honest read, and the number to budget.',
  '# Is Chitkul in September worth it?

Yes. **Verdict: go.** NakshIQ''s dataset scores September a full 5 out of 5 — 10/10 — for Chitkul, one of only three months in the year that reach this score.

## What the score is actually measuring

Chitkul''s [month-by-month page](/en/destination/chitkul/september) logs September as "the post-monsoon reveal": the air clears of the haze that builds through the rains, the Baspa Valley''s mountains come through at their most photographically distinct, and local operators are still running a full service rather than winding down for winter. At 3,450m elevation, the village — the last one before the Indo-Tibetan border along this route — is built around Kinnauri wooden architecture that the dataset flags as the specific draw of the month.

The trade-off the site is upfront about: nights are already getting cold by September, a real consideration at this altitude even while days stay clear and comfortable. October, the other month in Chitkul''s top tier, pushes that further — colder nights, warmer days, and the last full-service window before roads start closing for the season.

## What it costs

September falls inside Chitkul''s peak season (shared with May and October) for pricing. A mid-range hotel runs a typical ₹6,400 a night (range ₹3,700–11,000), a homestay around ₹3,700, and a hostel dorm bed about ₹850. Food averages ₹1,350 a day. A day taxi runs ₹5,000, and intercity transport to the nearest hub (Shimla or Kalka) typically costs ₹1,800 one way. None of this is a shoulder-season discount — Chitkul''s short peak window means you pay for the clear-sky month rather than around it. Full breakdown on the [Chitkul cost page](/en/cost/chitkul).

## Who it actually suits

The dataset does not rate Chitkul as a kids'' destination (4/10) — the altitude, the cold nights, and the remoteness (nearest airport and railhead are both Shimla/Chandigarh, several hours out) make it better suited to travelers who want an offbeat stop away from the Spiti-circuit crowds. Ideal stay length is short, 2–3 days, enough to sit with the valley without needing more infrastructure than the village has.

## The one-line answer

NakshIQ''s data rates September as one of only three top-scoring months for Chitkul — pack for cold nights regardless of the clear days, and treat the short peak window as the reason to book rather than a reason to wait.',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-hanle-in-october-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'hanle-october-verdict',
  'is-hanle-in-october-worth-it',
  'Is Hanle in October worth it?',
  '4/10 on the NakshIQ scale — outside the window, with September the better call',
  'best-time',
  'brief',
  4,
  '/images/destinations/hanle.jpg',
  ARRAY['verdict', 'ladakh', 'hanle', 'october', 'best-time'],
  ARRAY['hanle'],
  'Is Hanle in October Worth It? The Honest Verdict',
  'Hanle scores only 4/10 for October in NakshIQ''s dataset — outside its June–September window, with roads icing and Umlingla closing without notice. Here''s the honest read, and the better month.',
  'October falls outside Hanle''s core June–September window, and NakshIQ''s dataset scores it accordingly: 4/10, a skip. Here''s what''s actually driving that number, and what September — the last strong month — looks like instead.',
  '# Is Hanle in October worth it?

Not really. **Verdict: skip.** NakshIQ''s dataset scores October only 2 out of 5 — 4/10 — for Hanle, its lowest tier. The reason is straightforward: October sits outside the destination''s core June–September season, and the numbers reflect what that gap actually costs a traveler.

## What the score is measuring

Hanle sits at 4,500m in eastern Ladakh, home to one of the highest-altitude astronomical observatories in the world and a dark-sky reserve that draws stargazers specifically. The [month-by-month page](/en/destination/hanle/october) logs October as rapidly cooling — temperatures from -5°C to 10°C — with roads starting to ice over and the Umling La pass liable to close without warning. It''s still technically the tail of the stargazing season, but the dataset is explicit that conditions have already turned harder and local services have scaled back from their summer footing.

Compare that to September, which scores a full 10/10 in the same dataset: 0–15°C, the driest and clearest skies of the year, the Milky Way arch at its most dramatic, and Umling La still reliably open. September is the last month the site rates as a clean "go" before the shoulder-season trade-offs of October set in.

## What it costs

October falls into Hanle''s shoulder-season pricing bracket, alongside May. A mid-range hotel runs a typical ₹7,700 a night (range ₹4,400–13,000) — cheaper than the ₹11,000 peak-season rate, which is one upside of traveling outside the window if the conditions don''t put you off. A homestay runs about ₹4,400, food averages ₹1,600 a day, and the mandatory permit fee is ₹900. A day taxi — necessary given there''s no railhead and the nearest airport is Leh, 250km away — runs roughly ₹6,500. Full breakdown on the [Hanle cost page](/en/cost/hanle).

## The honest trade-off

If the trip is fixed to October for reasons outside the weather — a specific astronomy event, a broader Ladakh circuit already in motion — the dataset''s read is that this isn''t the version of Hanle that makes the destination worth the detour. Roads need checking daily before departing Leh, and the stargazing window this late in the season is a diminishing one, not the peak experience the destination is known for.

## The one-line answer

NakshIQ''s data is clear that October is the wrong month for Hanle on its own merits — if the dates can move, September is the same destination at 10/10 instead of 4/10, for a genuinely different trip.',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-karnaprayag-in-october-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'karnaprayag-october-verdict',
  'is-karnaprayag-in-october-worth-it',
  'Is Karnaprayag in October worth it?',
  '8/10 on the NakshIQ scale — one of two peak months for the Garhwal confluence town',
  'best-time',
  'brief',
  4,
  '/images/destinations/karnaprayag.jpg',
  ARRAY['verdict', 'uttarakhand', 'karnaprayag', 'october', 'best-time'],
  ARRAY['karnaprayag'],
  'Is Karnaprayag in October Worth It? The Honest Verdict',
  'Karnaprayag scores 8/10 for October in NakshIQ''s dataset — one of two best months for the Alaknanda-Pindar confluence town. Here''s the weather, the crowd math, and what a day actually costs.',
  'October is one of two months NakshIQ''s Karnaprayag dataset scores highest — 8/10, as roads reopen and the autumn pilgrimage rush returns to the confluence. Here''s the honest read, and the number to budget.',
  '# Is Karnaprayag in October worth it?

Yes. **Verdict: go.** NakshIQ''s dataset scores October a 4 out of 5 — 8/10 — for Karnaprayag, one of only two months (alongside the April–June window) that reach the site''s top tier.

## What the score is actually measuring

Karnaprayag sits at 1,050m, at the confluence of the Alaknanda and Pindar rivers, and functions mainly as a Garhwal pilgrimage and transit town. The [month-by-month page](/en/destination/karnaprayag/october) logs October as the return of peak conditions after the monsoon: roads that get monsoon damage through July and August are fully repaired by this point, temperatures settle to a comfortable 12–20°C, and skies clear to what the dataset calls crystalline. The confluence itself runs clear and at manageable levels rather than the swollen, silty flow of the rains, and surrounding peak views go unobstructed. Pilgrims return in force for the autumn rush, which the dataset flags as one of the two defining windows for "a complete Garhwal experience" — the other being the pre-monsoon April–June stretch.

## What it costs

October falls inside Karnaprayag''s peak season for pricing, alongside April, May, and June. A mid-range hotel runs a typical ₹4,700 a night (range ₹2,700–8,000), a homestay around ₹2,700, and a hostel dorm bed about ₹800. Food averages ₹1,000 a day. A day taxi — the practical way to cover the confluence viewpoints and onward Garhwal routes — runs ₹3,700, up from ₹1,650 in the January–February/August low season. Full breakdown on the [Karnaprayag cost page](/en/cost/karnaprayag).

## Who it suits

Karnaprayag works best as a short stop rather than a base — NakshIQ''s data logs an ideal stay of just one day, consistent with its role as a confluence town and transit point on longer Garhwal itineraries rather than a standalone destination. The nearest airport is Dehradun''s Jolly Grant, and Rishikesh is the nearest railhead — both manageable connections for a trip built around Badrinath, Kedarnath, or the wider Char Dham circuit that routes through this stretch of the Alaknanda valley.

## The one-line answer

NakshIQ''s data rates October as one of Karnaprayag''s two strongest months — roads are back to full service and the confluence is at its clearest, so it''s a solid add to an autumn Garhwal itinerary rather than a destination to plan a trip around on its own.',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();



-- Step 4b: publication-date cadence (founder rule 2026-07-26)
-- MAX(published_at) before this batch = 2026-08-19 04:50:00+00 (is-udaipur-in-september-worth-it)
-- Continuing 3/4-day alternating cadence, varied times of day, never future-dated (today 2026-09-17)
UPDATE articles SET published_at = '2026-08-22 04:20:00+00' WHERE slug = 'is-varanasi-in-october-worth-it';
UPDATE articles SET published_at = '2026-08-26 07:35:00+00' WHERE slug = 'is-rishikesh-in-september-worth-it';
UPDATE articles SET published_at = '2026-08-29 04:05:00+00' WHERE slug = 'is-chitkul-in-september-worth-it';
UPDATE articles SET published_at = '2026-09-02 08:10:00+00' WHERE slug = 'is-hanle-in-october-worth-it';
UPDATE articles SET published_at = '2026-09-05 03:50:00+00' WHERE slug = 'is-karnaprayag-in-october-worth-it';

COMMIT;
