-- Generated by scripts/build-blog-inserts.mjs on 2026-10-03
-- Run in Supabase Dashboard SQL Editor. One transaction covers all posts.

BEGIN;

-- is-mount-abu-in-november-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'mount-abu-november-verdict',
  'is-mount-abu-in-november-worth-it',
  'Is Mount Abu in November worth it?',
  'Rajasthan''s only hill station hits its peak window — cool, clear, and the Gujarat crowds already know it.',
  'best-time',
  'brief',
  2,
  '/images/destinations/mount-abu.jpg',
  ARRAY['verdict', 'mount-abu', 'november', 'rajasthan', 'hill-station'],
  ARRAY['mount-abu'],
  'Is Mount Abu in November worth it? Weather, crowds and the verdict',
  'Mount Abu in November scores 10/10 on our ledger — 12-25°C, clear skies, full sightseeing weather. Here is the honest read, plus what it costs.',
  'November scores a full 10/10 for Mount Abu — cool, clear, and right in the middle of Rajasthan''s only hill station''s best stretch. Here is what the month delivers, and what to book around.',
  '# Is Mount Abu in November worth it?

Short answer: yes. Our ledger scores [Mount Abu in November](/en/destination/mount-abu/november) at **10/10 — go**. It sits inside the town''s longest run of good months, not as an isolated exception.

## What November actually looks like

Temperatures run a cool, clear 12-25°C — comfortable for every outdoor stop on the usual list, from Nakki Lake to the Dilwara Temples to a Guru Shikhar sunrise. November also lines up with the peak of Gujarat''s tourist season: Mount Abu sits just across the border and is the closest hill escape for Ahmedabad and Vadodara, so expect genuine weekend crowds. Booking ahead for Friday-Saturday nights isn''t optional advice here, it''s the difference between a room and a full house.

## The context that matters

November isn''t a lucky outlier — it''s the middle of a five-month run. October, November, December, January and February all score a clean **10/10** on our ledger; March holds at 8/10 before April drops to 6/10 as the heat ramps up. May and June are the genuine low point at **4/10 — skip**: unusually hot for a hill station at 28-38°C, with minimal relief over the plains below. July and August sit at 6/10 — the monsoon turns the Aravallis green and the waterfalls run, but it''s a "wait," not a highlight. September recovers to 8/10 as the rain eases and crowds start returning.

So the honest framing: if your dates are flexible, October through February are all genuinely strong, and November doesn''t need to carry the trip alone — it''s one good week in a long good season.

## What it costs

Mount Abu''s peak-season pricing (October through March minus April) runs a mid-range hotel at a typical **₹6,100/night** (range ₹3,500-10,500), a homestay around ₹3,500, and food at about ₹1,300 a day. A full-day taxi runs ₹4,800. Off-peak (May-August), the same categories drop by roughly half. Full breakdown on the [cost page](/en/cost/mount-abu).

## Getting there

Mount Abu has no airport or railhead of its own — the nearest airport is Udaipur (160km) and the nearest railhead is Abu Road (28km), the last stretch by road. Most visits run 1-2 days, which is enough for the standard circuit of Nakki Lake, Dilwara, and Guru Shikhar.

## Verdict

- **Fixed November dates:** go — one of five consecutive 10/10 months.
- **Flexible dates:** any of October through February works about as well; pick based on crowds (quieter in January) versus festival energy (busier around Gujarat''s holiday weekends in November-December).
- **May–June:** skip. The heat genuinely erodes what makes a hill station worth visiting.

Full month-by-month scoring for Mount Abu is on the [destination page](/en/destination/mount-abu).',
  '2026-09-28 05:00:00+00'::timestamptz, NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-nainital-in-december-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'nainital-december-verdict',
  'is-nainital-in-december-worth-it',
  'Is Nainital in December worth it?',
  'The ledger calls it a wait, not a go — early December is a cold, grey continuation of November''s gloom.',
  'best-time',
  'brief',
  2,
  '/images/destinations/nainital.jpg',
  ARRAY['verdict', 'nainital', 'december', 'uttarakhand', 'lake-district'],
  ARRAY['nainital'],
  'Is Nainital in December worth it? The honest verdict',
  'Nainital in December scores 6/10 on our ledger — a wait, not a go. Cold, grey, 4-8°C daytime early in the month. Here is the honest read, and the months that score better.',
  'December scores 6/10 for Nainital — our ledger calls it a wait. Early in the month it is still a cold, grey continuation of November''s gloom. Here is what that actually means for a trip.',
  '# Is Nainital in December worth it?

Short answer: wait, not go. Our ledger scores [Nainital in December](/en/destination/nainital/december) at **6/10**, below the clean 8-10/10 run the town gets from September through November.

## What December actually looks like

The ledger''s own framing is blunt: "December splits into two Nainitals." Early December (the 1st to the 20th) is cold, grey, and empty — a straight continuation of November''s gloom, with daytime temperatures sitting at 4-8°C. It''s not dangerous, but it isn''t the postcard version of the lake either.

The ledger''s deeper notes add a sharper warning for this window: passes can be shut, a number of guesthouses close for the season, and services run minimal — attempting December here without a specific winter plan risks needing a rescue, in the ledger''s own words. That''s a stronger caution than the plain "wait" verdict might suggest, so read it as a genuine flag, not boilerplate.

## The context that matters

December isn''t Nainital''s weak month by accident — it''s the hinge between a strong autumn and a harder winter. October scores a clean **10/10** ("the cleanest month up here — cold nights, warm days, maximum visibility"), and November holds at **8/10** even as temperatures drop sharply toward 2-4°C nights by month-end. January, right after December, scores just **6/10** too — "deep winter... passes locked... most guesthouses unheated." So December sits at the start of a genuine low stretch, not a brief dip before things pick back up.

If a cold-weather, quiet, off-season Nainital is specifically what you want, December and January both deliver that honestly. If you''re choosing dates and have flexibility, September through November is the ledger''s real recommendation — October especially.

## What it costs

December falls in Nainital''s "shoulder" pricing band on our ledger, alongside February, May and August: a mid-range hotel runs a typical **₹3,800/night** (range ₹2,200-6,500), a homestay around ₹2,200, and food about ₹800 a day. A full-day taxi runs ₹3,000. Full breakdown on the [cost page](/en/cost/nainital).

## Getting there

Nainital''s nearest airport is Pantnagar (70km); the nearest railhead is Kathgodam (35km). Most trips run 2-4 days.

## Verdict

- **Fixed December dates:** workable, but go in with winter expectations — cold, quiet, some services closed. Not the lake-town postcard.
- **Flexible dates:** move to September, October or November if the trip is built around the lake and sightseeing rather than deliberately seeking the off-season cold.
- **Peak comparison:** October (10/10) and November (8/10) are both meaningfully stronger than December (6/10) on our own data.

Full month-by-month scoring for Nainital is on the [destination page](/en/destination/nainital).',
  '2026-09-30 06:30:00+00'::timestamptz, NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- vaishno-devi-yatra-distance-how-far-is-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'vaishno-devi-distance-guide',
  'vaishno-devi-yatra-distance-how-far-is-it',
  'How far is the Vaishno Devi yatra? The real distance, leg by leg',
  '13km on foot from Katra to the Bhawan shrine, per the Shrine Board''s own altitude table — here is where each kilometre goes.',
  'guide',
  'brief',
  3,
  NULL,
  ARRAY['guide', 'vaishno-devi', 'katra', 'pilgrimage', 'jammu-kashmir'],
  ARRAY['katra'],
  'Vaishno Devi yatra distance — 13km leg by leg, and how long it takes',
  'The Vaishno Devi yatra from Katra to the Bhawan shrine is 13km on foot. Full leg-by-leg breakdown — Banganga, Charan Paduka, Adhkuwari, Sanjichhat — plus duration and the best months to walk it.',
  'The Vaishno Devi yatra is a verified 13km foot route from Katra to the Bhawan shrine. Here is the leg-by-leg distance breakdown, how many days it actually takes, and when the trail is worth walking rather than riding.',
  '# How far is the Vaishno Devi yatra?

Short answer: **13km**, on foot, from Katra to the Bhawan shrine — the figure our dataset carries from the Shrine Board''s own altitude table, not a rounded estimate. Most yatris cover it in 1 to 3 days depending on pace, rest stops, and whether they continue on to Bhairavnath Temple afterward.

## The route, leg by leg

The trail runs through six official way-stations before the shrine, each with a Shrine Board altitude reading:

| Leg | Distance | Notes |
| --- | --- | --- |
| Katra → Banganga | 1km | Start of the yatra; Yatra Access Card counter at Katra bus stand. ~853m MSL. |
| Banganga → Charan Paduka | 1.5km (2.5km from Katra) | Sacred footprints site. ~1,030m MSL. |
| Charan Paduka → Adhkuwari | 3.5km (6km from Katra) | Major midpoint; ponies and palkis run up to here on the traditional route. ~1,463m MSL. |
| Adhkuwari → Himkoti | 2.5km (8.5km from Katra) | Rest house available. ~1,561m MSL. |
| Himkoti → Sanjichhat | 1km (9.5km from Katra) | Highest way-station; helipad location, Shrine Board langar. ~1,890m MSL. |
| Sanjichhat → Bhawan | 3.5km (13km from Katra) | Main shrine, the sacred cave of Mata Vaishno Devi. ~1,585m MSL. |

So **Charan Paduka to Adhkuwari is 3.5km**, and **Adhkuwari to Sanjichhat is 3.5km** (the Himkoti and Sanjichhat legs combined) — the two most-searched segment questions, both answered directly from the same official table.

Many pilgrims extend the trip by another 1.5km each way to Bhairavnath Temple past the Bhawan — tradition holds the yatra incomplete without it, though it isn''t a requirement. That makes the full round including Bhairavnath roughly 14.5km one-way from Katra.

## How long it actually takes, and the alternatives

Our dataset lists the yatra as a **1 to 3 day** undertaking. A fit walker can do Katra to Bhawan and back in a single long day; spreading it to two or three days leaves room for rest at Adhkuwari or Sanjichhat and a visit to Bhairavnath. Ponies and palkis cover the traditional route as far as Adhkuwari; a helicopter service runs to Sanjichhat, leaving roughly 3.5km on foot either way; and a short ropeway connects Bhawan to Bhairavnath for anyone skipping that climb.

## When to actually walk it

The yatra runs year-round with no closed months, but conditions vary a lot. March through June and September through November are the dataset''s strongest months — clear trails, full helicopter reliability, and (in October specifically) Sharad Navratri drawing 60-80K pilgrims a day, the single busiest stretch of the year. December holds up well too: cool, clear, with a year-end family pilgrimage rush around Christmas and New Year, though snowfall is possible on the Bhairon trail. July is the one genuine caution month — peak monsoon brings landslide-closure risk on the Adhkuwari-Sanjichhat-Bhawan stretch and a 30-40% jump in helicopter cancellations; the dataset marks it a "wait," not a go. January and February are workable but cold and quieter, with snow risk easing through February.

## What it costs

Katra''s peak season (March-June, September-November) runs a mid-range hotel at a typical **₹6,300/night** (range ₹3,700-11,000), food at about ₹1,350 a day, and a full-day taxi at ₹5,000. The shoulder months (February, July, August, December) drop to roughly ₹4,400/night mid-range; January, Katra''s quietest month, is cheaper still at around ₹2,850/night. Full breakdown on the [cost page](/en/cost/katra).

## Verdict

- **"How far is it":** 13km one-way on foot, 26km round trip, plus 3km more each way if you add Bhairavnath.
- **"How long does it take":** 1 day is doable; 2-3 days is more comfortable.
- **Best months:** March-June and September-November for reliability; December works but pack for cold; July is the month to avoid if you have a choice.

Full month-by-month scoring for Katra is on the [destination page](/en/destination/katra), and the complete route profile is on the [Vaishno Devi pilgrimage page](/en/pilgrimage/vaishno-devi).',
  '2026-10-01 03:45:00+00'::timestamptz, NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- matheran-ghumne-ka-kharcha
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'matheran-cost-hindi',
  'matheran-ghumne-ka-kharcha',
  'माथेरान घूमने का खर्च — सीज़न के हिसाब से असली आंकड़े',
  'गाड़ी-मुक्त हिल स्टेशन, जहां हर चीज़ टॉय ट्रेन या घोड़े पर आती है — इसलिए खर्च का हिसाब भी थोड़ा अलग है।',
  'guide',
  'brief',
  3,
  '/images/destinations/matheran.jpg',
  ARRAY['cost', 'matheran', 'hindi', 'budget', 'maharashtra'],
  ARRAY['matheran'],
  'माथेरान घूमने का खर्च — होटल, खाना, टैक्सी के सीज़न-वार आंकड़े',
  'माथेरान घूमने का खर्च कितना है? पीक सीज़न (अक्टूबर-मार्च) में मिड-रेंज होटल ₹6,100/रात, खाना ₹1,300/दिन। गाड़ी-मुक्त हिल स्टेशन का पूरा हिसाब, और मॉनसून में क्यों पूरी तरह बंद रहता है।',
  'माथेरान में पीक सीज़न (अक्टूबर से मार्च) का मिड-रेंज होटल ₹6,100/रात के आसपास बैठता है। गाड़ी-मुक्त हिल स्टेशन का पूरा सीज़न-वार हिसाब, और जून-अगस्त में टॉय ट्रेन बंद होने की असली वजह।',
  '# माथेरान घूमने का खर्च — सीज़न के हिसाब से असली आंकड़े

माथेरान भारत के उन चंद हिल स्टेशनों में है जहां गाड़ियां अंदर नहीं जातीं — हर सामान या तो नेरल से टॉय ट्रेन में आता है या दस्तूरी से घोड़े पर। इसी वजह से यहां का खर्च बाक़ी हिल स्टेशनों से थोड़ा अलग ढंग से बनता है। नीचे के आंकड़े हमारे रेट-लेज़र से हैं, वही जो [माथेरान के कॉस्ट पेज](/hi/cost/matheran) पर चलता है।

## पहले सीज़न समझिए

- **पीक:** अक्टूबर, नवंबर, दिसंबर, जनवरी, फरवरी — ये पांचों महीने हमारे स्कोर में **8–10/10** पर बैठते हैं (अक्टूबर-दिसंबर तीनों 10/10)।
- **शोल्डर:** मार्च में स्कोर गिरकर 6/10 पर आ जाता है — मौसम अभी भी ठीक है, पर गर्मी शुरू हो रही है।
- **बंद:** जून, जुलाई, अगस्त — हमारे लेज़र पर यह सीधे **स्कोर 0** है, "बंद" नहीं "स्किप"। टॉय ट्रेन रुक जाती है, रास्ते फिसलन-भरे और लैंडस्लाइड के ख़तरे वाले हो जाते हैं। सितंबर में भी स्कोर सिर्फ़ 2/10 रहता है — टॉय ट्रेन महीने के आख़िर में ही दोबारा शुरू होती है।

यानी अप्रैल-मई (स्कोर 4/10) को छोड़ भी दें, मॉनसून के तीन महीने माथेरान जाने लायक ही नहीं हैं — यह सीज़न-चॉइस नहीं, सेफ़्टी की बात है।

## ठहरने का खर्च (प्रति रात)

| श्रेणी | पीक सीज़न | लो सीज़न |
| --- | --- | --- |
| होस्टल डॉर्म | ₹900 (₹550–1,850) | ₹460 |
| होमस्टे | ₹3,500 (₹1,600–7,200) | ₹1,550 |
| मिड-रेंज होटल | ₹6,100 (₹3,500–10,500) | ₹2,700 |
| लग्ज़री | ₹19,000 (₹11,000–48,000) | ₹8,600 |

## रोज़ का खर्च

| मद | पीक सीज़न | लो सीज़न |
| --- | --- | --- |
| खाना (प्रति व्यक्ति, प्रति दिन) | ₹1,300 | ₹550 |
| पूरे दिन की टैक्सी* | ₹4,800 | ₹2,150 |
| इंटरसिटी किराया (स्लीपर बस / 2nd AC, एक तरफ़) | ₹1,550 | ₹1,000 |
| एक्टिविटी (सैंपल) | ₹2,400 | ₹1,050 |

*माथेरान के अंदर गाड़ी नहीं चलती — टैक्सी का यह खर्च नेरल तक/से है। अंदर घूमना टॉय ट्रेन (₹75 सेकंड क्लास से ₹300 फ़र्स्ट क्लास) या दस्तूरी से घोड़े पर (₹500–800) होता है। हर चीज़ घोड़े पर ऊपर आती है, इसलिए बाक़ी हिल स्टेशनों से थोड़ी महंगी भी पड़ती है।

## 3 दिन की ट्रिप — दो असली अनुमान

**कपल, मिड-रेंज, दिसंबर (पीक), 2 दिन / 1 रात:** होटल ₹6,100 + खाना ₹2,600 + टॉय ट्रेन (दोनों, 1st class) ₹1,200 + घोड़ा/सामान ₹1,200 + नेरल तक-से टैक्सी ₹4,800 = **लगभग ₹16,000**।

**अकेले, बजट, जनवरी (पीक), 1 दिन / 1 रात:** डॉर्म ₹900 + किफ़ायती खाना ₹650 + टॉय ट्रेन (2nd class, दोनों तरफ़) ₹150 + शेयर्ड टैक्सी नेरल तक ₹300 = **लगभग ₹2,000**।

(यह मॉडल किराया मुख्य हब से है — नज़दीकी रेलवे स्टेशन नेरल जंक्शन है, वहां से टॉय ट्रेन; नज़दीकी एयरपोर्ट मुंबई (BOM) क़रीब 80 किमी दूर है।)

## पैसा बचाने के तीन ईमानदार तरीके

1. **जून-अगस्त का सोचें ही नहीं** — रेट सवाल नहीं है, टॉय ट्रेन पूरी तरह बंद रहती है और रास्ते असुरक्षित हो जाते हैं। हमारा लेज़र इन तीन महीनों को स्कोर ही नहीं देता।
2. **जनवरी-फ़रवरी पकड़िए** — पीक सीज़न में ही आते हैं (8/10), पर अक्टूबर-दिसंबर जैसी भीड़ नहीं मिलती।
3. **सामान कम रखें** — घोड़े और कुली का खर्च वज़न के हिसाब से बढ़ता है; हल्का बैग सीधा पैसा बचाता है।

पूरा सीज़न-वार कैलकुलेटर [माथेरान के कॉस्ट पेज](/hi/cost/matheran) पर है, और महीने-दर-महीने की रेटिंग [माथेरान के डेस्टिनेशन पेज](/hi/destination/matheran) पर।',
  '2026-10-02 06:15:00+00'::timestamptz, NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- taragarh-fort-trek-distance-ajmer
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'taragarh-fort-trek-distance-ajmer',
  'taragarh-fort-trek-distance-ajmer',
  'Taragarh Fort trek distance: how far is it from Ajmer Dargah?',
  '6km, one day, 870m at the top — the real numbers behind the climb above the Dargah Sharif.',
  'guide',
  'brief',
  2,
  '/images/destinations/ajmer.jpg',
  ARRAY['guide', 'ajmer', 'taragarh-fort', 'trek', 'rajasthan'],
  ARRAY['ajmer'],
  'Taragarh Fort trek distance from Ajmer — 6km, and when to walk it',
  'The Taragarh Fort trek from Ajmer''s Dargah Sharif is a verified 6km route to 870m, done in a single day at moderate difficulty. Here is the honest distance, and the months worth climbing it in.',
  'The Taragarh Fort trek above Ajmer''s Dargah Sharif is a verified 6km, single-day climb to 870m — moderate difficulty, not a multi-day undertaking. Here is the real number, and when the climb is worth the heat.',
  '# Taragarh Fort trek distance: how far is it from Ajmer Dargah?

Short answer: **6km**, done in a single day, reaching **870m** at the fort — rated moderate difficulty on our dataset. It''s a half-day climb above the city, not the multi-day trek some searches seem to expect.

## The numbers

Our trek dataset logs Taragarh Fort as a 6km route with a 1-day duration and a moderate difficulty rating, topping out at 870m. Ajmer itself sits at 486m elevation, which puts the fort roughly 384m above the city — most of that gain comes in the second half of the climb, once the trail leaves the built-up area near the Dargah.

The walk starts close to Dargah Sharif, which is why most searches frame it as "Dargah to Taragarh" rather than naming a separate trailhead — there isn''t a meaningfully different starting point to account for.

## When to actually climb it

Ajmer''s own month-by-month data makes the seasonal call straightforward. October through March score **4-5/5 (8-10/10)**: temperatures sit in a manageable 8-32°C range across those months, with November and December both hitting the clean 10/10 ("ideal... dry, clear skies" and "cool... crisp mornings"). February is specifically called out as "perfect walking weather for the Taragarh Fort hike."

April through August drop to **1-3/5 (2-6/10)** — the dataset is blunt about why: by April, the dargah courtyard marble "burns feet by noon" and there''s "limited shade on the Taragarh trek," with a recommendation to carry at least 3 litres of water if you go anyway. May and June are worse still, with midday temperatures reaching 43°C and outdoor exploration flagged as dangerous. August adds a different problem — monsoon rain leaves "muddy trails to Taragarh Fort." September sits at a middling 3/5 (6/10) as the heat eases but humidity lingers.

## What it costs

Ajmer''s peak season (October, November, December, February, March) runs a mid-range hotel at a typical **₹6,100/night** (range ₹3,500-10,500), food at about ₹1,300 a day, and a full-day taxi at ₹4,800. The shoulder months (January, April, September) drop to roughly ₹4,200/night mid-range; the low months (May-August) fall further to around ₹2,700/night. Full breakdown on the [cost page](/en/cost/ajmer).

## Getting there

Ajmer''s nearest airport is Jaipur (135km); the city has its own railhead at Ajmer Junction. Most trips run 1-2 days — enough to combine the Taragarh climb with the Dargah Sharif and Ana Sagar Lake, or extend into a Pushkar day trip.

## The one-line answer

6km, one day, 870m at the summit — climb it October through March, and specifically avoid the midday window if you''re there April through August.

Full month-by-month scoring for Ajmer is on the [destination page](/en/destination/ajmer).',
  '2026-10-03 03:00:00+00'::timestamptz, NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

COMMIT;
