-- Generated by scripts/build-blog-inserts.mjs on 2026-08-01
-- Run in Supabase Dashboard SQL Editor. One transaction covers all posts.

BEGIN;

-- is-kedarnath-in-september-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'kedarnath-september-verdict',
  'is-kedarnath-in-september-worth-it',
  'Is Kedarnath in September worth it?',
  'Post-monsoon reveal — clear air, thin queues, and a temple closing by mid-November.',
  'best-time',
  'brief',
  2,
  '/images/destinations/kedarnath.jpg',
  ARRAY['verdict', 'kedarnath', 'september', 'pilgrimage', 'uttarakhand'],
  ARRAY['kedarnath'],
  'Is Kedarnath in September worth it? Post-monsoon weather and darshan times',
  'Kedarnath in September scores 8/10 on our ledger — post-monsoon, 2-10°C, 30-minute darshan instead of 6-hour queues. Here is what changes after the rains retreat.',
  'September is when Kedarnath''s monsoon crowds thin out and the queues collapse from six hours to thirty minutes. Our ledger scores it 8/10 — go.',
  '# Is Kedarnath in September worth it?

Short answer: our ledger scores [Kedarnath in September](/en/destination/kedarnath/september) at **8/10 — go**. The monsoon is retreating, the trek route is stabilising, and the crowds that define peak season have thinned out.

## What September actually looks like

Temperatures sit at 2–10°C, cold enough for real mountain layers but well short of the winter closure. Rain is retreating rather than gone — expect a mix of clear and cloudy days rather than a guaranteed run of blue sky. Two things stand out on our ledger:

- **Darshan queues collapse.** Instead of the multi-hour waits of peak season, September''s thinner pilgrim flow means something closer to a 30-minute darshan.
- **The trek stabilises.** The route from Gaurikund is still recovering footing from the monsoon but is passable and improving through the month.

The trade-off is straightforward: fewer people, a quieter shrine, but weather that can still turn.

## Getting there and what it costs

There''s no road to Kedarnath — it''s a 22km trek from Gaurikund, or a helicopter (₹2,500–7,000 one-way) for those skipping the walk. Stays are dharamshala-style, and food is basic and priced up near the top. Our ledger puts a budget day around ₹1,200, mid-range near ₹3,400, and a helicopter-and-comfort trip closer to ₹6,500 — full detail on the [Kedarnath cost page](/en/cost/kedarnath). Nearest airport is Dehradun''s Jolly Grant; nearest railheads are Rishikesh or Haridwar.

Plan 2–4 days for the round trip including the trek. This isn''t a kids'' trip — it scores low on our family-suitability read, better suited to a Panch Kedar-style pilgrimage circuit than a family holiday.

## If your dates are flexible

September isn''t the only strong month here. [May](/en/destination/kedarnath/may) — when the season opens — scores 10/10, though it comes with pilgrim surges and mule-booking pressure. [October](/en/destination/kedarnath/october) also scores 10/10 and is arguably the best month for a peaceful darshan: clear skies, snow-dusted peaks, and the smallest queues of the season, right up until the temple closes for winter in mid-November.

If your goal is quiet, October edges out September. If your window is fixed to September, you''re still getting a real post-monsoon reveal — just with slightly more weather risk.

## Verdict

- **Fixed September dates:** go — post-monsoon conditions, thin crowds, a functioning trek.
- **Flexible dates, want the quietest darshan:** push to October.
- **Flexible dates, don''t mind the surge:** May opens the season at full pilgrim energy.

Our full month-by-month scoring for Kedarnath is on the [destination page](/en/destination/kedarnath).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-darjeeling-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'darjeeling-august-verdict',
  'is-darjeeling-in-august-worth-it',
  'Is Darjeeling in August worth it?',
  'Peak monsoon in the hills — closed tea gardens, treacherous roads, and why October is the real answer.',
  'best-time',
  'brief',
  2,
  '/images/destinations/darjeeling.jpg',
  ARRAY['verdict', 'darjeeling', 'august', 'monsoon', 'tea'],
  ARRAY['darjeeling'],
  'Is Darjeeling in August worth it? Monsoon weather and the October case',
  'Darjeeling in August scores 2/10 on our ledger — peak monsoon, tea gardens shut, roads treacherous. Here is why October and November change everything.',
  'August is peak monsoon in Darjeeling — our ledger scores it 2/10 and says skip. Tea gardens close for the season and roads turn treacherous. Here is the honest read.',
  '# Is Darjeeling in August worth it?

Short answer: our ledger scores [Darjeeling in August](/en/destination/darjeeling/august) at **2/10 — skip**. This is peak monsoon in the hills, and it shows in almost everything that makes Darjeeling worth the trip.

## What August actually looks like

The monsoon here isn''t a passing shower pattern — it''s relentless. On our ledger:

- **Outdoor activities are effectively cancelled.** Viewpoints, ridge walks, and the toy train''s scenic runs all depend on visibility and dry track, neither of which August reliably delivers.
- **Roads turn treacherous.** Hill roads in and around Darjeeling are landslide-prone through the monsoon.
- **Tea gardens close for their monsoon break.** If a tea-estate visit was the point of the trip, August removes it.

The one thing in August''s favour is price — accommodation runs at its lowest rates of the year, since this is the off-season by every other measure.

## Who this still works for

Realistically: almost no one whose plans depend on being outdoors. If you''re passing through for a specific indoor reason — a stay at altitude to escape plains heat, work you can do from a hill-town cafe — August is cheap and quiet. Everyone else should expect a trip built around waiting out weather rather than seeing anything.

Getting here: nearest airport is Bagdogra (67km), nearest railhead is New Jalpaiguri (74km). Plan 3–4 days if you''re committing to the season regardless — our ledger puts a budget day near ₹1,250, mid-range near ₹4,000, and a full heritage-tea-town trip near ₹10,800; see the [Darjeeling cost page](/en/cost/darjeeling) for the breakdown.

## The October and November case

This is the part worth reading before booking. [Darjeeling in October](/en/destination/darjeeling/october) scores a full **10/10 — go**: 10–18°C, crystal-clear post-monsoon air, Kanchenjunga visible from Tiger Hill at sunrise, the toy train running, and second-flush tea in season. [November](/en/destination/darjeeling/november) holds at the same **10/10**, with clear skies continuing, autumn-flush tea, and the Singalila Ridge trek at its best.

Both months sit inside Darjeeling''s own best-months window on our data (March–May and October–November) — August and the surrounding monsoon months are the ones the ledger flags to avoid.

## Verdict

- **Fixed August dates:** skip unless your trip is entirely indoors — the outdoor product Darjeeling sells isn''t available.
- **Flexible dates:** wait for October or November. Both score 10/10 against August''s 2/10 — this isn''t a close call.

Our full month-by-month scoring for Darjeeling is on the [destination page](/en/destination/darjeeling).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-jaipur-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'jaipur-august-verdict',
  'is-jaipur-in-august-worth-it',
  'Is Jaipur in August worth it?',
  'Still hot, now humid — why the Golden Triangle waits for October.',
  'best-time',
  'brief',
  2,
  '/images/destinations/jaipur.jpg',
  ARRAY['verdict', 'jaipur', 'august', 'golden-triangle', 'rajasthan'],
  ARRAY['jaipur'],
  'Is Jaipur in August worth it? Monsoon heat and the case for winter',
  'Jaipur in August scores 4/10 on our ledger — still hot with unpredictable monsoon showers. Here is why the Golden Triangle season really starts in October.',
  'August in Jaipur is monsoon season, but the heat isn''t broken enough to make it comfortable. Our ledger scores it 4/10 — skip, and here is what to do instead.',
  '# Is Jaipur in August worth it?

Short answer: our ledger scores [Jaipur in August](/en/destination/jaipur/august) at **4/10 — skip**. The monsoon has arrived, but it hasn''t done the one job that would make this worth it: breaking the heat.

## What August actually looks like

Rain continues through the month, and it can be genuinely atmospheric — forts and havelis photograph differently under monsoon cloud. But our ledger is blunt about the trade-off: it''s mostly still hot, showers are unpredictable, and neither the heat nor the rain fully commits. You get the discomfort of both seasons without the clear benefit of either.

Fort visits suffer most — stone courtyards and open ramparts at Amer or Nahargarh don''t hold up well to sudden downpours, and there''s no reliable way to plan a full day around them.

## What still works

Indoor-first sightseeing survives: City Palace''s covered sections, museums, and the shopping lanes of the old city don''t depend on clear skies. Hotel rates are also at their lowest point of the year, which is the honest upside of an off-season month. Nearest airport is Jaipur International; nearest railhead is Jaipur Junction, so logistics aren''t the obstacle — comfort is.

Budget for 2–3 days. Our ledger puts a budget day near ₹1,300, mid-range near ₹4,500, and a heritage-hotel trip near ₹13,000 — heritage stays start around ₹2,000/night, and a composite ticket covers multiple forts more cheaply than paying per site. Full breakdown on the [Jaipur cost page](/en/cost/jaipur).

## The winter case

Jaipur''s own best-months data points squarely at October through February, and two of those months are fully scored. [November](/en/destination/jaipur/november) hits **10/10 — go**: 12–28°C, clear skies, Diwali lights on Nahargarh Fort, and the Jaipur Jewellery Show. [December](/en/destination/jaipur/december) holds the same **10/10**: 8–24°C, comfortable all-day fort visits at Amer, Jantar Mantar, and Hawa Mahal, plus New Year events at the palace hotels.

Against August''s 4/10, that''s not a marginal gap — it''s the difference between a compromised trip and the city working the way it''s meant to.

## Verdict

- **Fixed August dates:** skip the forts, keep it indoor and cheap, or reconsider the timing.
- **Flexible dates:** book October–February. November and December both score 10/10.

Our full month-by-month scoring for Jaipur is on the [destination page](/en/destination/jaipur).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-dharmasthala-worth-visiting-for-lakshadeepotsava
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'dharmasthala-lakshadeepotsava-verdict',
  'is-dharmasthala-worth-visiting-for-lakshadeepotsava',
  'Is Dharmasthala worth visiting for Lakshadeepotsava?',
  'The temple town''s peak season builds around a mid-November lamp festival — and a kitchen that feeds 30,000 people a day, every day.',
  'best-time',
  'brief',
  2,
  '/images/destinations/dharmasthala.jpg',
  ARRAY['verdict', 'dharmasthala', 'november', 'pilgrimage', 'karnataka', 'festival'],
  ARRAY['dharmasthala'],
  'Is Dharmasthala worth visiting for Lakshadeepotsava? November scoring and cost',
  'Dharmasthala scores 10/10 in November on our ledger, when Lakshadeepotsava preparations build through the month. Here is what''s verified, and what it costs.',
  'Dharmasthala''s Lakshadeepotsava lamp festival builds through November, our ledger''s single highest-scoring month for the temple town. Here is what''s verified, and what to plan around.',
  '# Is Dharmasthala worth visiting for Lakshadeepotsava?

Short answer: our ledger scores [Dharmasthala in November](/en/destination/dharmasthala/november) at **10/10 — go**. November is when Lakshadeepotsava preparations build through the temple complex, alongside Karnataka Rajyotsava on November 1 — and it''s the single highest-scoring month we have for this destination.

## What November actually looks like

Weather cooperates: 19–30°C with rainfall under 50mm, dry enough that outdoor queues and the temple approach stay comfortable. Our data notes pilgrim flow building through the month as Lakshadeepotsava preparations get underway mid-November — we don''t have an exact festival date on record, so if you''re planning around the lamp-lighting itself, confirm the specific day with the temple administration before booking travel.

What is verified: the annadana — Dharmasthala''s free community kitchen — runs at full capacity regardless of season, serving in the tens of thousands daily. It''s one of the few places in the country where a pilgrimage stay can be genuinely free: temple accommodation and meals are available at no cost, alongside private hotels for anyone who wants more comfort.

## What it costs

This is a rare destination where the honest budget answer is "as little as you want." Our ledger''s budget-tier estimate is around ₹200/day (transport only — food and stay through the temple can run free), mid-range sits near ₹1,800/day, and a full private-hotel trip is closer to ₹3,800/day. Full detail on the [Dharmasthala cost page](/en/cost/dharmasthala).

Plan for a single day — our data marks Dharmasthala as a 1-day destination, not a multi-night base. Nearest airport is Mangalore (IXE), 75km out; nearest railhead is Subramanya Road, 55km.

## What to avoid

April and May are the two months our ledger flags to skip — pre-monsoon heat pushes temperatures into the low-to-mid 30s and pilgrim queues collapse by midday. Everything else on the calendar, including the monsoon months, scores workable or better: Dharmasthala''s mostly-indoor, temple-and-meal-hall shape holds up through rain in a way an outdoor hill station doesn''t.

## Verdict

- **Planning around Lakshadeepotsava specifically:** November is the right month on our data, but confirm the exact festival date with the temple — we don''t have it verified.
- **Flexible dates, want peak season generally:** October through March all score 10/10 or close to it.
- **On a tight budget:** this may be the cheapest verified pilgrimage trip in our entire dataset.

Our full month-by-month scoring for Dharmasthala is on the [destination page](/en/destination/dharmasthala).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-nelliyampathy-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'nelliyampathy-august-verdict',
  'is-nelliyampathy-in-august-worth-it',
  'Is Nelliyampathy in August worth it?',
  'Monsoon still running the show — landslide-prone roads, shut plantation walks, and an Onam closure on top.',
  'best-time',
  'brief',
  2,
  '/images/destinations/nelliyampathy.jpg',
  ARRAY['verdict', 'nelliyampathy', 'august', 'kerala', 'monsoon'],
  ARRAY['nelliyampathy'],
  'Is Nelliyampathy in August worth it? Monsoon road conditions and Onam closures',
  'Nelliyampathy in August scores 2/10 on our ledger — 700-900mm rainfall, the access road landslide-prone, Onam shutting most operations for days. Here is when to go instead.',
  'August in Nelliyampathy holds the same monsoon pattern as July — heavy rain, an unreliable access road, and an Onam closure layered on top. Our ledger scores it 2/10.',
  '# Is Nelliyampathy in August worth it?

Short answer: our ledger scores [Nelliyampathy in August](/en/destination/nelliyampathy/august) at **2/10 — skip**. This small Kerala hill station holds onto its July monsoon pattern through August, with a festival closure layered on top.

## What August actually looks like

Rainfall runs 700–900mm for the month, and the effects compound: the 12-hairpin-bend approach road is landslide-prone, plantation walks suspend, and visibility from the viewpoints that make Nelliyampathy worth the drive is unreliable. Temperatures stay mild, 20–26°C, but that''s cold comfort when the roads and trails aren''t cooperating.

Onam — Kerala''s harvest festival, which falls in August or September depending on the year — adds a second complication on our ledger: it shuts most local operations for three to four days, on top of the weather.

## Why this destination is different from most monsoon skips

Nelliyampathy has essentially no resort infrastructure — that''s part of its appeal in season, when the silence and empty estates are the draw. But it means there''s no indoor-first fallback the way a bigger hill station might offer. Off-season here isn''t "quieter but workable" — the destination''s whole product depends on functioning roads and open trails, and August takes both away.

Getting here: nearest airport is Coimbatore (100km), nearest railhead is Palakkad Junction (55km). Our ledger estimates a budget day near ₹1,000 and a mid-range day near ₹2,500 — see the [Nelliyampathy cost page](/en/cost/nelliyampathy). Plan 2–3 days for a proper visit, but not in August.

## When to actually go

The ledger is consistent here: September is a "wait" month at 3/10 as the monsoon withdraws and the road stabilises mid-month, but [October](/en/destination/nelliyampathy/october) jumps to **8/10 — go** as the season opens fully, plantation walks turn their greenest, and the road settles. [November](/en/destination/nelliyampathy/november) and [December](/en/destination/nelliyampathy/december) both score **10/10**, dry and clear, though hotel rates climb toward Christmas and New Year.

If you can only travel in the monsoon months, the honest answer is to pick a different Kerala hill station with better road infrastructure — Nelliyampathy''s single access road is the whole bottleneck.

## Verdict

- **Fixed August dates:** skip — the road and trails are the product, and both are compromised.
- **Flexible dates:** October through March is the real season, peaking November–December.

Our full month-by-month scoring for Nelliyampathy is on the [destination page](/en/destination/nelliyampathy).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

COMMIT;
