-- Generated by scripts/build-blog-inserts.mjs on 2026-07-26
-- Run in Supabase Dashboard SQL Editor. One transaction covers all posts.

BEGIN;

-- is-kolkata-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'kolkata-august-verdict',
  'is-kolkata-in-august-worth-it',
  'Is Kolkata in August worth it?',
  'Peak monsoon in the cultural capital — what the rain closes, what it opens, and why October changes everything.',
  'best-time',
  'brief',
  2,
  '/images/destinations/kolkata.jpg',
  ARRAY['verdict', 'kolkata', 'august', 'monsoon', 'durga-puja'],
  ARRAY['kolkata'],
  'Is Kolkata in August worth it? Weather, monsoon reality, and the October case',
  'Kolkata in August scores 4/10 on our ledger — peak monsoon, Sundarbans closed. Here is what still works, and why waiting for October''s Durga Puja is the better trip.',
  'August is peak monsoon in Kolkata — our ledger scores it 4/10 and says skip. But the city doesn''t shut the way a beach does. Here is the honest read, and the case for October.',
  '# Is Kolkata in August worth it?

Short answer: our ledger scores [Kolkata in August](/en/destination/kolkata/august) at **4/10 — skip**. It''s peak monsoon. But Kolkata is not a beach town; rain doesn''t switch the city off the way it switches off Goa. So the real question is what you''re coming for.

## What August actually looks like

August sits in the heart of the monsoon here. Two things on our ledger close or shrink because of it:

- **The Sundarbans are closed.** If mangroves and river safaris were part of the plan, August removes them entirely.
- **Darjeeling as a side trip becomes weather-dependent.** The hills are reachable only on good-weather days — you can''t plan a fixed itinerary around them.

What the rain gives back: the city turns lush and green, and the cultural calendar starts moving again — talks, theatre, the indoor Kolkata of College Street coffee houses and museum halls that never needed sunshine in the first place.

## Who should still come

If your Kolkata is entirely indoors — bookshops, galleries, old-club dining rooms, long afternoons over coffee — August works at a discount in crowds and doesn''t ruin the product. Plan 3–5 days, arrive via Netaji Subhas Chandra Bose International Airport or Howrah Junction, and accept that every outdoor plan needs a same-day weather check.

If your Kolkata includes river ghats at golden hour, day trips, or the Sundarbans: don''t force it.

## The October case

This is the honest part. [Kolkata in October](/en/destination/kolkata/october) scores **10/10 — go** on our ledger, and the note is three words long: Durga Puja — the greatest show. The city rebuilds itself into an open-air art festival, and it is the single best reason to be here all year.

[September](/en/destination/kolkata/september) is the in-between month — 6/10, wait — monsoon retreating while the Puja pandals go up. If your dates flex even slightly, that''s the direction to push them.

## Verdict

- **Fixed August dates, indoor-first trip:** come, it''s workable.
- **Fixed August dates, outdoor-first trip:** skip — Sundarbans closed, hills unreliable.
- **Flexible dates:** wait for October. It isn''t close.

Our full month-by-month scoring for the city is on the [Kolkata destination page](/en/destination/kolkata).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-doodhpathri-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'doodhpathri-august-verdict',
  'is-doodhpathri-in-august-worth-it',
  'Is Doodhpathri in August worth it?',
  'The Meadow of Milk in late monsoon — lush, soggy, and four weeks short of its best month.',
  'best-time',
  'brief',
  2,
  '/images/destinations/doodhpathri.jpg',
  ARRAY['verdict', 'doodhpathri', 'august', 'kashmir', 'monsoon'],
  ARRAY['doodhpathri'],
  'Is Doodhpathri in August worth it? Weather, road conditions, and the September case',
  'Doodhpathri in August — 13-23°C, lush but soggy meadows, a muddy road from Budgam. Our ledger says wait (6/10). September scores a perfect 10. Here is the honest call.',
  'August at Doodhpathri is green, atmospheric, and wet underfoot — 6/10 on our ledger. September is a 10. If your dates can move four weeks, move them.',
  '# Is Doodhpathri in August worth it?

Our ledger scores [Doodhpathri in August](/en/destination/doodhpathri/august) at **6/10 — wait**. Not a skip: the meadow works in August. But it sits four weeks short of the best month of its year, so the answer depends entirely on whether your dates can move.

## What August looks like at 2,730 m

Monsoon showers continue through August, with days running **13–23°C**. The meadows are at their most lush — green, low cloud, atmospheric — but sometimes soggy underfoot. The road up from Budgam can get muddy after rain, so build slack into the day rather than timing it tight.

If you don''t mind wet feet, it''s a genuinely pretty version of the meadow. Kashmir also sits in a partial rain shadow compared to the outer Himalayan ranges, which is why August here is a "wait" and not the hard "skip" it is in Manali or Garhwal — worth knowing if you''re choosing between mountain regions with fixed August dates.

## The practical shape of the trip

Doodhpathri is a **day trip, not a stay**: 42 km from Srinagar, with our ideal-duration data saying half a day to one day. On our cost ledger a budget day runs about **₹1,150** (midrange ~₹3,700), and pony rides on the meadow go for **₹300–800**. Overnight options are limited — most visitors base in Srinagar and come up for the day.

## The September case

[September at Doodhpathri](/en/destination/doodhpathri/september) scores **10/10 — go**, and the ledger note reads like a different place: post-monsoon perfection at 8–20°C, crystal-clear air, meadows green with the first autumn tinge, snow peaks visible, the stream running clear. It''s the best photography month of the year here.

[October](/en/destination/doodhpathri/october) holds at **8/10** — golden meadows, chinar season nearby, early snow on the peaks — but it cools fast (5–15°C) and it''s the last good month before winter closes things down.

## Verdict

- **Dates fixed in August:** go — accept soggy meadows and a possibly muddy road, and you''ll still get value from it.
- **Dates can move even four weeks:** wait for September. The gap between 6/10 and 10/10 is the gap between a decent day out and the meadow at its absolute best.

Month-by-month scoring is on the [Doodhpathri destination page](/en/destination/doodhpathri).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- landour-in-september-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'landour-september-verdict',
  'landour-in-september-worth-it',
  'Landour in September — the post-monsoon reveal',
  'The month the rain stops, the air rinses clean, and the quietest ridge above Mussoorie starts its autumn turn.',
  'best-time',
  'brief',
  2,
  '/images/destinations/landour.jpg',
  ARRAY['verdict', 'landour', 'september', 'uttarakhand', 'weather'],
  ARRAY['landour', 'mussoorie'],
  'Landour in September — weather, why it scores 10/10, and how it compares to Mussoorie',
  'September is when the monsoon recedes from Landour and the autumn transition begins — a 10/10 month on our ledger. What the weather does, who it suits, and the Mussoorie comparison.',
  'September at Landour scores a perfect 10 on our ledger — monsoon receding, air rinsed clean, mountains at their most photographically alive. Here is what that actually means for a trip.',
  '# Landour in September — the post-monsoon reveal

If you''re asking about Landour weather in September, here''s the ledger answer first: [Landour in September](/en/destination/landour/september) scores **10/10 — go**. It''s one of the two best months of the year on this ridge, and the reasons are specific.

## What September does to the weather

September is when the monsoon recedes from Landour and the spectacular autumn transition begins. The practical effect, from our ledger: the air is rinsed clean by three months of rain, the long Himalayan views are at their most photographically alive, and everything on the hill — cafés, walks, homestays — is fully running rather than half-shuttered the way it can be in the wet months.

At **2,270 m**, Landour sits a couple of hundred metres above Mussoorie, which is exactly why the post-monsoon clarity lands harder here: the viewpoints at Lal Tibba and the walks around the loop face straight out at the ranges the rain has just unveiled.

## Who September at Landour suits

Our data flags this month as built for the slow trip — the writers''-retreat pattern of long mornings at Char Dukan and afternoons on empty walking loops. It also rates **8/10 for families**. This is not an activity destination in any month; September just makes the core product (quiet, views, walks) as good as it gets.

Plan **2–3 days**. The railhead is Dehradun (35 km); the airport is Dehradun Jolly Grant (60 km).

## The Mussoorie comparison

Worth being honest about the neighbour one ridge down. [Mussoorie in September](/en/destination/mussoorie/september) scores **8/10** — the monsoon''s slow retreat — against Landour''s 10. By [October](/en/destination/mussoorie/october) both hit 10/10 as the season fully opens. If your trip is Mall Road, Kempty Falls and the classic circuit, Mussoorie is the base; if the point is silence and long views, September belongs to Landour.

## Verdict

Go. September and [October](/en/destination/landour/october) are the window this place is built around — book for it, don''t drift into it. Month-by-month scoring is on the [Landour destination page](/en/destination/landour).',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- mussoorie-ghumne-ka-kharcha
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'mussoorie-cost-hindi',
  'mussoorie-ghumne-ka-kharcha',
  'मसूरी घूमने का खर्च — सीज़न के हिसाब से असली आंकड़े',
  'होस्टल से लग्ज़री तक हर बजट का हिसाब, और यह भी कि कौन से महीने में जाना पैसा वसूल है।',
  'guide',
  'brief',
  2,
  '/images/destinations/mussoorie.jpg',
  ARRAY['cost', 'mussoorie', 'hindi', 'budget', 'uttarakhand'],
  ARRAY['mussoorie'],
  'मसूरी घूमने का खर्च — होटल, खाना, टैक्सी के सीज़न-वार आंकड़े',
  'मसूरी घूमने का खर्च कितना है? पीक सीज़न में मिड-रेंज होटल ₹6,300/रात, खाना ₹1,300/दिन, डे-टैक्सी ₹5,000। बजट से लग्ज़री तक पूरा हिसाब और 3 दिन की ट्रिप का अनुमान।',
  'मसूरी में पीक सीज़न का मिड-रेंज होटल ₹6,300/रात और खाना ₹1,300/दिन के आसपास बैठता है। बजट डॉर्म से लग्ज़री तक पूरा सीज़न-वार हिसाब, और 3 दिन की ट्रिप का असली अनुमान।',
  '# मसूरी घूमने का खर्च — सीज़न के हिसाब से असली आंकड़े

मसूरी का खर्च एक संख्या नहीं है — सीज़न के साथ रेट लगभग दोगुने तक घटते-बढ़ते हैं। नीचे के आंकड़े हमारे रेट-लेज़र से हैं, वही जो [मसूरी के कॉस्ट पेज](/hi/cost/mussoorie) पर चलता है।

## पहले सीज़न समझिए

- **पीक:** मार्च–अप्रैल और सितंबर–नवंबर — सबसे अच्छा मौसम, सबसे ऊंचे रेट।
- **शोल्डर:** फरवरी, मई, अगस्त, दिसंबर — बीच का रास्ता।
- **लो:** जनवरी, जून, जुलाई — सबसे सस्ता, पर जुलाई–अगस्त हमारे लेज़र पर **2/10 — स्किप** है (मॉनसून में पहुंच वाली सड़कों पर लैंडस्लाइड का जोखिम)। सस्ता तभी सही है जब मौसम साथ दे।

घूमने के लिहाज़ से [सितंबर](/hi/destination/mussoorie/september) **8/10** और [अक्टूबर](/hi/destination/mussoorie/october) **10/10** है — यानी सबसे अच्छा मौसम पीक रेट पर ही मिलता है।

## ठहरने का खर्च (प्रति रात)

| श्रेणी | पीक सीज़न | लो सीज़न |
| --- | --- | --- |
| होस्टल डॉर्म | ₹1,000 (₹600–2,050) | ₹500 |
| होमस्टे | ₹3,600 (₹1,650–7,400) | ₹1,550 |
| मिड-रेंज होटल | ₹6,300 (₹3,600–10,500) | ₹2,700 |
| लग्ज़री | ₹22,000 (₹12,500–54,500) | ₹9,400 |

## रोज़ का खर्च

| मद | पीक सीज़न | लो सीज़न |
| --- | --- | --- |
| खाना (प्रति व्यक्ति, प्रति दिन) | ₹1,300 | ₹550 |
| पूरे दिन की टैक्सी | ₹5,000 | ₹2,150 |
| इंटरसिटी किराया (स्लीपर बस / 2nd AC, एक तरफ़) | ₹1,800 | ₹1,200 |
| एक्टिविटी (सैंपल) | ₹2,500 | ₹1,050 |

## 3 दिन की ट्रिप — दो असली अनुमान

**कपल, मिड-रेंज, अक्टूबर (पीक), 3 दिन / 2 रातें:** होटल ₹12,600 + खाना ₹7,800 + दो दिन टैक्सी ₹10,000 + आना-जाना (2 लोग, दोनों तरफ़) ₹7,200 = **लगभग ₹37,000–40,000**।

**अकेले, बजट, पीक सीज़न, 3 दिन / 2 रातें:** डॉर्म ₹2,000 + किफ़ायती खाना ₹2,000–2,500 + आना-जाना ₹3,600 + पैदल/शेयर्ड लोकल = **लगभग ₹8,000–10,000**।

(खर्च के ये आंकड़े मुख्य हब से मॉडल किराए पर आधारित हैं — दिल्ली से आ रहे हैं तो देहरादून तक ट्रेन और आगे 35 किमी सड़क जोड़ लीजिए।)

## पैसा बचाने के तीन ईमानदार तरीके

1. **शोल्डर सीज़न पकड़िए** — फरवरी या दिसंबर में मिड-रेंज होटल ₹4,200 के आसपास आ जाता है और मौसम काम चलाऊ रहता है।
2. **जनवरी सबसे सस्ता महीना है** — रेट लो-सीज़न के, और जुलाई वाला लैंडस्लाइड जोखिम नहीं।
3. **टैक्सी का दिन घटाइए** — मसूरी का असली प्रोडक्ट पैदल घूमना है; हर दिन ₹5,000 की टैक्सी ज़रूरी नहीं।

पूरा सीज़न-वार कैलकुलेटर [मसूरी के कॉस्ट पेज](/hi/cost/mussoorie) पर है, और महीने-दर-महीने की रेटिंग [मसूरी के डेस्टिनेशन पेज](/hi/destination/mussoorie) पर।',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- ayodhya-ghumne-ka-kharcha
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, updated_at, featured, callouts
) VALUES (
  'ayodhya-cost-hindi',
  'ayodhya-ghumne-ka-kharcha',
  'अयोध्या घूमने का खर्च — राम मंदिर यात्रा का पूरा बजट',
  'धर्मशाला से होटल तक हर विकल्प का सीज़न-वार हिसाब, और दर्शन के लिए सबसे सही महीने।',
  'guide',
  'brief',
  2,
  '/images/destinations/ayodhya.jpg',
  ARRAY['cost', 'ayodhya', 'hindi', 'budget', 'ram-mandir'],
  ARRAY['ayodhya'],
  'अयोध्या घूमने का खर्च — होटल, खाना, दर्शन का सीज़न-वार बजट',
  'अयोध्या घूमने का खर्च कितना है? धर्मशाला ₹200 से, मिड-रेंज होटल ₹5,200/रात (पीक), खाना ₹1,100/दिन। 2 दिन की यात्रा का पूरा हिसाब और जाने का सबसे सही महीना।',
  'अयोध्या में धर्मशाला ₹200 से शुरू होती है और पीक सीज़न का मिड-रेंज होटल ₹5,200/रात बैठता है। 2 दिन की यात्रा का पूरा हिसाब, और यह भी कि जुलाई-अगस्त में क्यों नहीं जाना चाहिए।',
  '# अयोध्या घूमने का खर्च — राम मंदिर यात्रा का पूरा बजट

अयोध्या बजट यात्रा के लिए बना शहर है — ठहरना सस्ता है, दूरियां छोटी हैं, और **1–2 दिन** में यात्रा पूरी हो जाती है। नीचे के आंकड़े हमारे रेट-लेज़र से हैं, वही जो [अयोध्या के कॉस्ट पेज](/hi/cost/ayodhya) पर चलता है।

## पहले सीज़न समझिए

- **पीक:** अक्टूबर–दिसंबर और फरवरी–मार्च — दर्शन का सबसे अच्छा मौसम।
- **शोल्डर:** जनवरी, अप्रैल, सितंबर।
- **लो:** मई–अगस्त — सबसे सस्ता, पर हमारे लेज़र पर [जुलाई](/hi/destination/ayodhya/july) और [अगस्त](/hi/destination/ayodhya/august) **4/10 — स्किप** हैं: सरयू उफान पर, घाटों तक पहुंच सीमित, गलियों में जलभराव, उमस भारी। सस्ते का यह सौदा घाटे का है।

[अक्टूबर](/hi/destination/ayodhya/october) **10/10** है — 20–32°C, मानसून के बाद की ताज़गी, वीकडे पर राम मंदिर की कतारें छोटी। [नवंबर](/hi/destination/ayodhya/november) भी **10/10** — अयोध्या का दीपोत्सव, सरयू घाटों पर लाखों दीये — पर बुकिंग महीनों पहले करनी पड़ती है।

## ठहरने का खर्च (प्रति रात)

| श्रेणी | पीक सीज़न | लो सीज़न |
| --- | --- | --- |
| धर्मशाला | ₹200 से | ₹200 से |
| होस्टल डॉर्म | ₹700 | ₹340 |
| होमस्टे | ₹3,000 (₹1,400–6,200) | ₹1,350 |
| मिड-रेंज होटल | ₹5,200 (₹3,000–9,000) | ₹2,350 |
| लग्ज़री | ₹14,000 (₹8,200–35,000) | ₹6,300 |

राम मंदिर के आसपास का इलाका तेज़ी से बन रहा है — नए होटल हर सीज़न जुड़ रहे हैं।

## रोज़ का खर्च

| मद | पीक सीज़न | लो सीज़न |
| --- | --- | --- |
| खाना (प्रति व्यक्ति, प्रति दिन) | ₹1,100 | ₹490 |
| पूरे दिन की टैक्सी | ₹4,100 | ₹1,850 |
| इंटरसिटी किराया (स्लीपर बस / 2nd AC, एक तरफ़) | ₹1,250 | ₹850 |

## 2 दिन की यात्रा — दो असली अनुमान

**कपल, मिड-रेंज, अक्टूबर (पीक), 2 दिन / 1 रात:** होटल ₹5,200 + खाना ₹4,400 + एक दिन टैक्सी (मंदिर + घाट + हनुमानगढ़ी) ₹4,100 + आना-जाना (2 लोग, दोनों तरफ़) ₹5,000 = **लगभग ₹18,000–20,000**।

**अकेले, बजट/तीर्थयात्री, पीक सीज़न, 2 दिन / 1 रात:** धर्मशाला या डॉर्म ₹200–700 + किफ़ायती खाना ₹1,100–1,500 + पैदल दर्शन + आना-जाना ₹2,500 = **लगभग ₹4,000–5,000**।

## पहुंचना

रेल सबसे सीधा रास्ता है — **अयोध्या जंक्शन** शहर में ही है। हवाई रास्ते से नज़दीकी बड़ा विकल्प **लखनऊ (135 किमी)** है; अयोध्या का नया एयरपोर्ट भी चालू है।

पूरा सीज़न-वार कैलकुलेटर [अयोध्या के कॉस्ट पेज](/hi/cost/ayodhya) पर है, और महीने-दर-महीने की रेटिंग [अयोध्या के डेस्टिनेशन पेज](/hi/destination/ayodhya) पर।',
  NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

COMMIT;
