-- Generated by scripts/build-blog-inserts.mjs on 2026-04-21
-- Run in Supabase Dashboard SQL Editor. One transaction covers all posts.

BEGIN;

-- is-manali-in-june-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, created_at, updated_at, featured, callouts
) VALUES (
  'manali-june-verdict',
  'is-manali-in-june-worth-it',
  'Is Manali in June worth it? The honest answer',
  '3/5 score. Rohtang permit lottery. Hotel rates 3× off-season. Shift your dates by four weeks.',
  'guide',
  'brief',
  4,
  '/images/destinations/manali.jpg',
  ARRAY['verdict', 'himachal', 'manali', 'june', 'road-safety'],
  '["manali"]'::jsonb,
  'Is Manali in June Worth It? The NakshIQ Verdict (2026)',
  'Manali is on every family''s June list. NakshIQ''s data-scored verdict: wait. Road, crowd, and budget math in one paragraph.',
  'Manali is on every family''s June list. The NakshIQ score says wait — 3/5 for the month, and every one of the three reasons is fixable if you shift your dates by four weeks. Go in mid-May or the last week of September.',
  '# Is Manali in June worth it? The honest answer

Manali is on every family''s June list. The NakshIQ score says wait — 3/5 for the month, and every one of the three reasons is fixable if you shift your dates by four weeks.

**Verdict: Wait.** Go in mid-May or the last week of September. Both score higher and cost less.

---

## The three-line summary

- **June score: 3/5.** Weather is genuinely pleasant (18–28°C), but the dataset marks it Fair, not Good.
- **Mall Road is packed** and hotels are billing 3× their off-season rate. Two nights that cost ₹1,800 in late April run ₹5,400 in mid-June.
- **Rohtang Pass requires a permit** issued through a daily lottery. Most days you do not get one.

## Why the score isn''t Skip

Manali in June is not unsafe. The road from Chandigarh is open, the hotels are not cutting corners, and the 18–28°C window is exactly what the families chasing summer relief came for. That is why the score stays at 3 instead of dropping lower. The problem is the gap between what you are paying and what you are getting.

## Where the June booking pile-up hits

Three costs compound.

- **Hotel rate.** The same 3-star double you can get for ₹1,800 in late April runs ₹5,400 for three nights in mid-June. Multiply by the number of nights, then add peak-season taxi surcharges.
- **Mall Road.** The core strip from Mall Road to Manu Market is visibly crowded between 11 am and 9 pm across all 30 days of June. Photographs you have seen of empty Manali are from April or October.
- **Rohtang Pass.** The pass itself is the reason many families come. The Himachal Pradesh government caps daily vehicle counts and runs a permit lottery at [himachalonline.gov.in](https://himachalonline.gov.in/). Most applicants don''t get one on their intended date. Atal Tunnel stays open without a permit — but that bypasses Rohtang, which means you don''t actually see the pass.

## What scores higher in the same state

NakshIQ scored 5/5 in June for seven Himachal destinations that are less crowded and less expensive than Manali. They include high-altitude options (Spiti''s passes have just opened), moderate hill stations (Tirthan Valley, Jibhi), and quiet villages (Bir, Barot). Every one of them has June data marking it Peak, not Fair.

If Manali is the anchor, consider it as a launchpad — one night there to break the drive, then push on to Spiti or the Parvati Valley.

## The cleanest fix: shift the dates

- **Mid-May:** similar weather, 45% cheaper, no Rohtang lottery (pass just opened; try your luck), Mall Road still breathable.
- **Late September:** weather is crisper (10–22°C), crowds are gone, and the autumn light on the Kullu Valley is the photography window Manali is actually remembered for.

Either of those windows is a Go verdict on the same Manali row, not a Wait.

---

**The one-line answer.** If June is the only window you have, go — and spend two days in Manali, not five. If you can move your dates, don''t.',
  NOW(), NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-goa-in-august-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, created_at, updated_at, featured, callouts
) VALUES (
  'goa-august-verdict',
  'is-goa-in-august-worth-it',
  'Is Goa in August worth it? What actually works in monsoon',
  'Every coastal Goa destination scores 0/5 in August. The interior — Dudhsagar, Mollem, Old Goa — is at its annual peak.',
  'guide',
  'brief',
  4,
  '/images/destinations/dudhsagar-falls.jpg',
  ARRAY['verdict', 'goa', 'august', 'monsoon', 'interior'],
  '["calangute-baga","dudhsagar-falls","old-goa","mollem","reis-magos"]'::jsonb,
  'Is Goa in August Worth It? Skip the Beach, Here''s What Works',
  'Goa in August scores 0/5 for beach — shacks shut, sea is closed. But Dudhsagar, Mollem, and Old Goa are at their annual peak. The data call, inside.',
  'Goa in August is sold as the contrarian traveller''s secret. NakshIQ scores every coastal destination 0/5 for August. But three interior destinations hit their annual peak in monsoon. Skip the beach; visit the interior.',
  '# Is Goa in August worth it? What actually works in monsoon

Goa in August is sold as the contrarian traveller''s secret. The NakshIQ score says no — 0/5 for every major beach on our ledger, because beach activity is the entire product and beach activity is shut.

**Verdict: Skip Goa''s beaches. Visit the interior.** There are three destinations in Goa''s interior that score higher in August than most of the coast scores in December.

---

## The three-line summary

- **Every coastal destination scores 0/5.** Calangute-Baga, Palolem, Anjuna, Arambol, Agonda — the dataset marks all of them "No Data" for August because the beach product is not operating.
- **Shack ban is official.** The Goa government removes beach shacks each monsoon (late May through September). Water sports are shut by coast guard notice.
- **Interior scores hold.** Dudhsagar Falls, Mollem sanctuary, Old Goa''s Portuguese churches are all at their photographic peak.

## Why the beaches actually don''t work in August

This is not a "rain is inconvenient" argument. This is structural.

- **No shacks.** The beach-shack ecosystem — the food, the sunbeds, the beer, the beachside dhaba — is dismantled by order before June 1 and does not return until October. You can reach the beach. There is nothing on it.
- **Sea closed.** Coast guard flags ban swimming, water sports, and boat hire. The undertow in monsoon Goa kills people every year. Lifeguards remove themselves because there is no job to do.
- **Hotel math.** Rates drop 30–50%, not 70%. You are paying mid-season prices for a product that is 10% of its December self.

If the point of Goa is the beach, the beach is closed.

## What actually scores high

Three interior destinations are at their annual peak in August. The NakshIQ dataset does not flag them down the way it does the coast.

- **Dudhsagar Falls** — 310 metres. In August the waterfall is at full volume. It is one of the five tallest in India, and the only month of the year it looks like the photographs is monsoon. The trek from Castle Rock is open to trained groups; the Collem railway approach runs daily.
- **Mollem (Bhagwan Mahavir Sanctuary)** — 240 km² of Western Ghats. The canopy is saturated green, Tambdi Surla temple is quiet, wildlife activity is up because heat has broken. Very few visitors in August because they assume the whole state is shut.
- **Old Goa** — UNESCO Portuguese churches (Basilica of Bom Jesus, Se Cathedral). Indoor-weighted itinerary. Rain does not disrupt it.

A three-day trip built around these three plus Panaji lunches (Ritz Classic, Vinayak in Assagao for Goan fish thali) gets you the Goa the tourism board doesn''t market. Keep it to three days. Don''t try to extend into the beaches.

## Where to stay

Skip Calangute-Baga and the north-coast beach strip. Stay in Panaji or Margao. Both are river-adjacent, both are walkable, both give you a 40-minute drive to Dudhsagar and a 20-minute drive to Old Goa. Hotels in both cities hold their standards through monsoon. Expect ₹2,500–5,000/night for a decent mid-range room.

## The counterfactual

If the only reason you want Goa is a beach chair and a Kingfisher, wait until late October. The coast is back by then, the post-monsoon light is better than December''s haze, and hotel rates are 20% under Christmas peak.

---

**The one-line answer.** August is the wrong month to visit beach Goa and the right month to visit the Goa nobody writes about. Do the interior, do it in three days, and come back to the coast in October.',
  NOW(), NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- is-agra-day-trip-worth-it
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, created_at, updated_at, featured, callouts
) VALUES (
  'agra-day-trip-verdict',
  'is-agra-day-trip-worth-it',
  'Is an Agra day trip worth it? The cleanest failure mode',
  'Agra scores 5/5 in October and November. The day-trip from Delhi removes exactly the three things that make the score.',
  'guide',
  'brief',
  5,
  '/images/destinations/agra.jpg',
  ARRAY['verdict', 'agra', 'day-trip', 'taj-mahal', 'delhi'],
  '["agra"]'::jsonb,
  'Is an Agra Day Trip Worth It? Don''t Do It — Here''s Why',
  'Agra''s 5/5 score is predicated on sunrise, Mehtab Bagh at dusk, and Fatehpur Sikri. A Delhi day trip misses all three. One night flips the math entirely.',
  'Agra in October and November scores 5/5. The day-trip version from Delhi scores near zero — not because Agra is wrong, but because the day-trip structure removes the three things that make Agra the monument everyone claims it is.',
  '# Is an Agra day trip worth it? The cleanest failure mode

Agra in October and November scores 5/5. The day-trip version from Delhi scores near zero — not because Agra is wrong, but because the day-trip structure removes the three things that make Agra the monument everyone claims it is.

**Verdict: Skip the day trip. Stay one night.** The marginal cost is ₹2,000 and two hours. The marginal payoff is the entire reason you came.

---

## The three-line summary

- **Agra''s score is a month score, not a day-trip score.** 5/5 in October and November assumes you see the Taj at sunrise and again at sunset.
- **A typical Delhi day trip lands you at the Taj between 11 am and 1 pm.** That is the exact two-hour window the marble reflects hardest and photographs flattest.
- **Mehtab Bagh at sunset**, which locals will tell you is when the Taj stops being a monument and starts being something else, closes by 6 pm and is across the river. You cannot fit it into a day trip.

## What the "Agra in a day" tour actually delivers

The standard Delhi-Agra-Delhi package looks efficient on paper. Leave Delhi 6 am, back by 9 pm. 215 km each way on the Yamuna Expressway. You pay ₹4,500–7,000 and you get:

- **The Taj Mahal between 11 am and 1 pm.** Direct overhead light, maximum glare, maximum heat off the marble. The white dome looks grey in your phone photos. Every Instagram you have seen of the Taj was not shot then.
- **Agra Fort for 45 minutes** before the group herds you to a buffet lunch. The fort is UNESCO-level good. You don''t have time.
- **Back on the bus by 2:30 pm.** The sun is still high.
- **Arrival at the Delhi drop-off at 9 pm.** You were in a vehicle for 9 hours to spend 4 hours in Agra.

## What you actually miss

- **Sunrise at the Taj.** Gate opens 30 minutes before sunrise. In October the marble turns pink at 6:12 am. The tour bus is still on the expressway.
- **Mehtab Bagh at dusk.** The "moonlight garden" across the Yamuna is the view that made Shah Jahan''s Taj Mahal the Taj Mahal in the commissioning drawings. Opens 6 am, closes 6 pm. ₹300 entry. Empty.
- **Fatehpur Sikri.** 40 km west of Agra. Empty Mughal capital in red sandstone. Needs three hours and cannot be clipped onto the day trip.
- **The 20 minutes between 5:45 and 6:05 pm** when the Taj''s east wall turns amber, the crowds have left, and the complex is nearly silent. A day trip will never buy you this.

## The alternative

One night in Agra. Any decent hotel under ₹3,500 works. Oberoi Amarvilas has the view; Trident Agra is the value pick; ITC Mughal is older but walkable. Book the cheapest room you are willing to sleep in.

Day one — arrive by Gatimaan Express (1 hr 40 min, ₹750 chair car, ₹1,505 EC from Hazrat Nizamuddin) around noon. Check in. Walk to Agra Fort for the 3–5 pm window when the sun hits the Khas Mahal. Dinner at Peshawri or Esphahan. Sleep.

Day two — sunrise at the Taj. East gate. Be in the queue by 5:30 am. You will be out by 8 am. Breakfast. Train back to Delhi by 11 am, or push on to Fatehpur Sikri and Delhi by evening.

Total cost added over the day-trip version: ₹2,000–3,000 per person. Hours actually inside Agra''s monuments: 8, not 4. Sunrise: included. Mehtab Bagh: possible.

## The Agra month score only works if you stay

The 5/5 rating on NakshIQ''s October and November rows is predicated on the golden-light window. The skip-reason for a day trip is structural, not seasonal: the day-trip product does not include the golden-light window by design. That is the failure mode.

---

**The one-line answer.** Agra is worth every word written about it. The day-trip version is not.',
  NOW(), NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- hampi-when-the-heat-is-kind
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, created_at, updated_at, featured, callouts
) VALUES (
  'hampi-when-heat-is-kind',
  'hampi-when-the-heat-is-kind',
  'Hampi: when the heat is kind',
  'January + February score 5/5. April onward the ruins turn oven. October is the underrated twin.',
  'best-time',
  'brief',
  5,
  '/images/destinations/hampi.jpg',
  ARRAY['best-time', 'hampi', 'karnataka', 'february', 'ruins', 'unesco'],
  '["hampi"]'::jsonb,
  'Best Month to Visit Hampi — When the Heat Actually Works',
  'Hampi scores 5/5 in February and October — cool Matanga sunrise, dry boulders, empty ghats. April to June the data says skip. One data-led call.',
  'Hampi is the classic case of a destination whose reputation outran its calendar. NakshIQ scores 5/5 in January and February, 4/5 in March, and falls off a cliff from April onward. There is exactly one four-month window where the ruins are not hostile.',
  '# Hampi: when the heat is kind

Hampi is the classic case of a destination whose reputation outran its calendar. The NakshIQ score says 5/5 in January and February, 4/5 in March, and falls off a cliff from April onward. There is exactly one four-month window where the ruins are not hostile. The rest of the year, the 4,100 hectares of exposed Vijayanagara stone turn oven.

**Verdict: Go — in February.** Or the last week of January through the first week of March. Outside that arc, the score drops and the math stops working.

---

## The three-line summary

- **January + February score 5/5.** 18–28°C, cool Matanga sunrise, dry boulders, the ghats at Virupaksha before 9 am are the photographs you have seen.
- **April hits 38°C in the shade.** The ruins have no shade. May and June push past 42°C. The score drops to 2 and then 1.
- **October and November recover.** 5/5 again. Post-monsoon Tungabhadra is high, Matanga Hill sunsets are hazy but clearing, and the crowds are lighter than February.

## Why the score peaks when it does

The Vijayanagara ruins cover ~4,100 hectares of granite boulder field, exposed temple complexes, and raised causeways. There is no tree cover on the climb to Matanga Hill. The bouldering around Tungabhadra is directly on granite that stores heat for hours after sundown. Anything above 32°C is not sightseeing — it is endurance.

February delivers 10–24°C. Mornings are cool enough for the Matanga Hill sunrise climb (3 km return, starts from Virupaksha). Afternoons on the Royal Enclosure side are warm but walkable. Evenings at the Tungabhadra bouldering area are soft.

## Where the February score earns its 5

- **Matanga Hill sunrise.** Gate opens at 5:30 am. The viewpoint tops out at 250m. In February the haze lifts by 6:45, which is when the first light hits Virupaksha''s gopuram. 20 minutes later, the Achyutaraya temple emerges.
- **Bouldering on the south side.** Dry granite, 22–28°C midday, grip holds. The northern Badami style routes at Hemakuta are also dry.
- **Pattabhirama to Vitthala walk.** 4.2 km flat. The iconic stone chariot is best between 8 and 10 am — soft light on sandstone red.
- **Tungabhadra coracle ride.** ₹400–600 per person, 30 minutes. Water levels are mid-drop but the river is still wide enough for the boulders on the far bank to show.
- **Night at Hampi Bazaar.** Cool enough to sit on the ghat steps after 7 pm. In April that is impossible.

## Why April through June is Skip

- **April.** Score 2. The ruins surface at 38°C midday — ground temperature on the granite paths hits 46°C. There is no shade between Hemakuta and Vitthala.
- **May.** Score 1. Score drops because heat is structurally dangerous, not just uncomfortable. Dehydration cases are reported annually. Do not go.
- **June.** Score 2. Monsoon brings some relief but the Tungabhadra rises and the far-side routes (Anegundi across the river) become inaccessible by coracle. The ruins themselves are walkable in shorter morning windows.

The "Hampi is hot but manageable" framing is wrong. Below 5/5 in April–June is a data signal, not a caveat.

## The October–November recovery

Post-monsoon October scores 5/5 again. The Tungabhadra is at annual peak volume. Post-monsoon air is cleaner than February''s (dust from dry lakebeds starts by late January). November holds the score through the first week before the weekend tour buses come back.

If February and March are booked out, October is the underrated twin. Fewer foreign backpackers, lower hut prices at Hampi Bazaar (₹400–800 vs ₹800–1,500 in February), and the same 5/5 on the NakshIQ ledger.

## Getting there

- **Hospet railhead** is 13 km from Hampi. Hampi Express from Bangalore (KSR Bengaluru) arrives 7:10 am, ₹310 sleeper / ₹1,400 2A. Autos at Hospet charge ₹300–400 for the 25-minute drive.
- **Hubballi airport (HBX)** is 160 km, 3 hours by cab. ₹2,500 one-way, ₹3,500 return.
- **Stay on the south bank** (Hampi Bazaar) for ruins access, north bank (Anegundi / Sanapur) for the bouldering + rural stay experience.

## What to carry

Cotton layers, a wide-brim hat, at least 2 litres of water per person for the mid-day stretches. Good trail shoes for Matanga Hill. Cash — most Hampi Bazaar huts are cash-preferred.

---

**The one-line answer.** February is the window the ruins were built to be seen in. October is the alternative. The rest of the year, the data tells you not to bother.',
  NOW(), NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

-- pushkar-in-october-scored
INSERT INTO articles (
  id, slug, title, subtitle, category, depth, reading_time,
  cover_image_url, tags, destinations, seo_title, seo_description,
  excerpt, content, published_at, created_at, updated_at, featured, callouts
) VALUES (
  'pushkar-october-scored',
  'pushkar-in-october-scored',
  'Despite the camel-fair reputation, Pushkar in October is better than November',
  'Both months score 5/5. One shares the ghats with 50,000 people. The other shares them with nobody.',
  'best-time',
  'brief',
  5,
  '/images/destinations/pushkar.jpg',
  ARRAY['best-time', 'pushkar', 'rajasthan', 'october', 'camel-fair', 'lake'],
  '["pushkar"]'::jsonb,
  'Pushkar in October vs November — When to Actually Go (Data)',
  'Pushkar is a November destination in everyone''s head. NakshIQ data says October is a cleaner 5/5 — same weather, full lake, zero fair crowds, 40% cheaper rooms.',
  'Pushkar is sold as a November destination — the Camel Fair, 50,000 camels. The NakshIQ score says October earns an identical 5/5 and gives you the version of Pushkar that existed before the fair. Same weather, fuller lake, a fraction of the crowd.',
  '# Despite the camel-fair reputation, Pushkar in October is better than November

Pushkar is sold as a November destination — the Camel Fair, 50,000 camels, the one week every year that ends up on every travel magazine''s homepage. The NakshIQ score says October earns an identical 5/5 and gives you the version of Pushkar that existed before the fair. Same weather, fuller lake, a fraction of the crowd, 40% cheaper rooms.

**Verdict: Go in October — unless the fair is specifically what you came for.** Both months score 5/5. One has you sharing the ghats with 50,000 people. The other has you sharing them with nobody.

---

## The three-line summary

- **October score: 5/5.** 18–30°C, post-monsoon lake at full volume, all ghats accessible, clear skies.
- **November score: 5/5.** Same temperature band. Plus the Camel Fair. Plus the crowd.
- **Room rates.** Mid-October budget dorm: ₹400–600. Fair week November: ₹1,800–3,500 for the same bed.

## Why the score ties

Pushkar''s weather window is defined by two things: the Thar Desert heat curve breaking in late September, and the winter dry air beginning in December. Everything between those two points is Pushkar at its best. October sits at the leading edge of the window — the monsoon has just finished filling Pushkar Lake back up, the air is cleanest, and the evening aarti at Varah Ghat is atmospheric without being staged for tourists.

November is climatically identical. The fair is what separates them. If the fair is your draw, go. If it isn''t, October is the same destination without the distortion.

## What October buys you that November takes away

- **The lake is full.** September and October rains top Pushkar Lake back up after summer evaporation. By late November the ghats are starting to show exposed stone at the waterline.
- **Camera access at ghats.** In November the fair overflows off the dunes into the lake''s ghats. You cannot get unobstructed shots at Varah Ghat or Brahma Ghat between November 5 and November 20.
- **Brahma Temple queue.** October afternoon: walk in. Fair week November: 40-minute queue.
- **Cafes on the Main Bazaar strip** (Honey & Spice, Sunset Cafe, the rooftop at Seventh Heaven) are running at 60% capacity in October and 130% in November. Food is the same. Wait times are not.
- **Room rates.** October budget double: ₹700–1,200. November fair week: ₹2,500–6,000. The same ₹1,500/night Inn Seventh Heaven room triples.

## What November buys you that October cannot

- **The Camel Fair itself.** 50,000+ camels, traditional dress, rajput musicians, cricket matches between Pushkar locals and international visitors, the balloon-release opening ceremony. If this is the photograph you want, October cannot give it to you.
- **The ritual bath on Kartik Purnima.** Full moon day. Hindu pilgrims come in the tens of thousands. It is the most Pushkar thing Pushkar does.

These are specific payoffs — real, in the data, unreplicable in October. If they are on your list, book November by July.

## Where to stay in October

- **Budget (₹500–1,000/night):** Moustache Hostel, Zostel Pushkar. Walking distance to Brahma Temple.
- **Mid (₹2,000–4,000/night):** Inn Seventh Heaven, Pushkar Fort. Rooftops with lake views.
- **Upper (₹6,000+):** Ananta Spa, Dera Masuda. Resort-style with pool, 1–2 km from the lake.

Book 3–4 weeks ahead. October is quiet enough that walk-in is feasible but the good rooftops fill on weekends.

## How to get to Pushkar

- **Ajmer railhead** is 15 km from Pushkar. Jaipur to Ajmer 2 hours by Shatabdi (₹480 CC, ₹1,000 EC). Ajmer to Pushkar autos ₹250–400.
- **Jaipur airport (JAI)** is 140 km, 2.5 hours by cab. ₹2,800 one-way.
- **From Delhi** Double Decker train to Ajmer 5.5 hours, or drive 7 hours (410 km via NH48).

## What October does not give you

Pushkar is a small town. The main strip — Brahma Temple to Pap Mochini ghat — is 1.6 km end to end. You cover it in a day. October does not extend what is actually there; it only removes the November crowd. Plan two nights, three at most. Day three works best as an Ajmer day trip (Dargah Sharif, Ana Sagar) or a Rajasthan-series next stop (Jodhpur, 5 hours) rather than another Pushkar day.

---

**The one-line answer.** November is the famous month. October is the better one — same score, different Pushkar. Unless the fair is the point, pick October.',
  NOW(), NOW(), NOW(), FALSE, '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  cover_image_url = EXCLUDED.cover_image_url,
  tags = EXCLUDED.tags,
  destinations = EXCLUDED.destinations,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = NOW();

COMMIT;
