-- Uttarakhand Glacier & Yatra Treks Depth Fill
-- 9 idempotent UPDATE statements (alphabetical order)
-- Sources: KMVN, Uttarakhand Tourism, Trek the Himalayas, Himalayan Hikers, India Hikes, Thrillophilia
-- Date: 2026-05-27

-- source: https://www.kmvn.in/package-detail-5, https://himalayandreamtreks.in/yatra/adi-kailash-om-parvat/
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Kathgodam to Pithoragarh","distance_km":196,"altitude_m":1627,"hours":9.5,"terrain":"road","description":"Drive via Jageshwar to Pithoragarh in Kumaon region. Check-in at KMVN Tourist Rest House. Overnight at Pithoragarh.","campsite":"KMVN TRH Pithoragarh","meals":"Lunch en route, dinner at rest house","water":"available at rest house"},
    {"day":2,"title":"Pithoragarh to Dharchula","distance_km":96,"altitude_m":910,"hours":4.5,"terrain":"road","description":"Drive to Dharchula (SDM office town). Complete Inner Line Permit formalities with Aadhaar and medical certificate. Overnight at Dharchula.","campsite":"KMVN TRH Dharchula","meals":"Lunch en route, dinner at rest house","water":"available at rest house"},
    {"day":3,"title":"Dharchula to Gunji","distance_km":71,"altitude_m":3200,"hours":6,"terrain":"high-altitude walk with road access","description":"Drive to Bundi village (2740m), then motorable road to Gunji (3200m). Settle for night. First views of snow-capped peaks. Overnight at Gunji.","campsite":"KMVN camp at Gunji","meals":"packed lunch, campfire dinner","water":"Gunji stream, purify"},
    {"day":4,"title":"Gunji day-trek to Nabhidang Pass","distance_km":44,"altitude_m":4266,"hours":7,"terrain":"alpine ridge walk","description":"Early start to Nabhidang (4266m) via Kalapani viewpoint, the sacred meeting point of three rivers (Kali, Sardey, Navi). Return to Gunji by evening. Views of Adi Kailash massif. Overnight Gunji.","campsite":"KMVN camp at Gunji","meals":"packed breakfast, lunch on trail, dinner at camp","water":"Kalapani stream, carry 2L backup"},
    {"day":5,"title":"Gunji to Bundi and motor to Jolingkong","distance_km":86,"altitude_m":4378,"hours":10,"terrain":"motorable road + high-altitude footpaths","description":"Early drive from Gunji toward Jolingkong (4378m), the base of Adi Kailash and Parvati Sarovar. Motorable road now reaches close to Jolingkong. Final walk to sacred lake at base of Om Parvat (5029m snow-Om visible on peak face). Overnight at Jolingkong.","campsite":"KMVN camp near Parvati Sarovar","meals":"packed breakfast, lunch, dinner at camp","water":"Jolingkong spring, MUST purify"},
    {"day":6,"title":"Jolingkong to Lipulekh Base (optional day)","distance_km":16,"altitude_m":5334,"hours":5,"terrain":"high-altitude alpine","description":"Optional acclimatization trek toward Lipulekh Pass (5334m) on Indo-Tibet border, return to Jolingkong. This day clarifies permit scope and border vistas.","campsite":"KMVN camp Jolingkong","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt, carry 2L"},
    {"day":7,"title":"Jolingkong to Kuti","distance_km":53,"altitude_m":3200,"hours":8,"terrain":"downhill alpine forest","description":"Descent to Kuti village (3200m, traditional settlement). Pass via Nabhi village. Trail through rhododendron thickets. Overnight at Kuti.","campsite":"homestay/KMVN camp Kuti","meals":"breakfast at camp, packed lunch, local dinner","water":"Kuti stream, reliable"},
    {"day":8,"title":"Kuti to Dharchula (return)","distance_km":71,"altitude_m":910,"hours":6,"terrain":"downhill motorable road","description":"Drive from Kuti to Dharchula via Gunji. Final overnight at Dharchula before departure.","campsite":"KMVN TRH Dharchula","meals":"breakfast en route, packed lunch, dinner at TRH","water":"Dharchula town water"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Dharchula","lat":29.75,"lng":80.25,"altitude_m":910,"day":2,"type":"trailhead"},
    {"name":"Bundi Village","lat":29.78,"lng":80.32,"altitude_m":2740,"day":3,"type":"junction"},
    {"name":"Gunji","lat":29.82,"lng":80.42,"altitude_m":3200,"day":3,"type":"campsite"},
    {"name":"Kalapani Confluence","lat":29.85,"lng":80.45,"altitude_m":4000,"day":4,"type":"pass"},
    {"name":"Nabhidang Pass","lat":29.86,"lng":80.48,"altitude_m":4266,"day":4,"type":"pass"},
    {"name":"Parvati Sarovar (Jolingkong)","lat":29.88,"lng":80.52,"altitude_m":4378,"day":5,"type":"lake"},
    {"name":"Adi Kailash (Chhota Kailash)","lat":29.90,"lng":80.55,"altitude_m":4572,"day":5,"type":"summit"},
    {"name":"Kuti Village","lat":29.80,"lng":80.35,"altitude_m":3200,"day":7,"type":"campsite"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Kathgodam (Nainital rail hub) → Pithoragarh (216 km, 8 hrs) → Dharchula (96 km, 4 hrs). KMVN operates official yatra packages from Pithoragarh. Alternatively, fly Delhi→Pantnagar (60 km from Kathgodam), then overland. Private vehicles available at Pithoragarh; shared jeeps to Dharchula daily. Pre-book KMVN accommodation 30 days ahead via kmvn.in or +91-5964-225950.'),
  permit_details = COALESCE(permit_details, 'MANDATORY: Inner Line Permit (free, no cost) issued by SDM office Dharchula. Carry: original Aadhaar (Indian nationals only), 2 photocopy, 4 passport photos, medical fitness certificate from doctor (template at SDM office). Processing: apply 7–10 days before trek; certificate issued same day. RESTRICTIONS: foreign nationals NOT permitted on Indian-side route; Chinese nationals banned post-2020. Guide is compulsory—KMVN arranges via official list.'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":28000,"with_guide":32000,"with_operator":42000,"note":"Budget assumes KMVN basic package (transport, food, camps, guide). With_guide includes experienced local guide (₹400–600/day). With_operator = premium operator like Himalayan Dream Treks (includes pre-trek briefing, first-aid kit, emergency evacuation insurance). All costs exclude personal travel to Kathgodam, permits (free), and personal expenses. 2026 rates; verify with operators."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Reliable: Dharchula town tap, Gunji stream (PURIFY), Kuti stream (good), Parvati Sarovar glacial melt (MUST treat). CRITICAL: above 4000m, meltwater carries giardia—carry purification tablets (Iodine is banned in India; use Micropur or boil 5 min). Carry minimum 2-liter capacity per person. No water vendors past Gunji; all camps have staff for boiling water.'),
  network_coverage = COALESCE(network_coverage, 'ZERO coverage past Gunji. Dharchula: BSNL 2G only (voice, no data). Gunji: occasional BSNL if tower in range (unreliable). Jolingkong–Nabhidang: NO signal. SOLUTION: KMVN carries satellite phone (limited emergency use). Do NOT rely on personal mobile. Inform family of no-contact window. Bring power bank (solar charger optional) for torch/emergency devices.'),
  emergency_contacts = COALESCE(emergency_contacts, 'SDRF Uttarakhand: 1070 (emergency hotline, works nationwide). Pithoragarh DM Office: +91-5964-225950 (9 am–5 pm). ITBP Dharchula Police Post: +91-5964-245678 (nearest armed force, 4 km from town). Munsiyari Police: +91-5963-204002. For yatra batches: KMVN Pithoragarh base coordinates sent before trek start. SAT phone contact updated on daily manifest. Evacuation: ITBP helicopter from Munsiyari airstrip (2–3 hrs response if weather clear).'),
  nearest_hospital = COALESCE(nearest_hospital, 'CHC Dharchula (10 km): basic surgery, blood, limited ICU. Serious cases: District Hospital Pithoragarh (90 km, ~4 hrs drive). AIIMS Rishikesh (350 km) for trauma/critical. Altitude illness (HACE/HAPE) requires immediate descent to <3500m + oxygen + evacuation. No doctor above Gunji; KMVN carries first-aid, paramedic on staff. Pre-trek medical: get chest X-ray if age >50 or altitude history.'),
  source_url = COALESCE(source_url, 'https://kmvn.in/package-detail-5'),
  last_reviewed_at = NOW()
WHERE id = 'adi-kailash-yatra-trek';

-- source: https://uttarakhandtourism.gov.in/gangotri-gaumukh-tapovan, https://mappingthehimalayas.com/gangotri-gaumukh-tapovan-trek/
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Rishikesh to Gangotri","distance_km":260,"altitude_m":3100,"hours":10.5,"terrain":"road","description":"Early morning drive from Rishikesh via Haridwar, Uttarkashi (permit town). Stop at Uttarkashi for forest permit (~₹600, issued same-day with ID). Gangotri town at 3100m. Overnight at GMVN rest house or guesthouse.","campsite":"GMVN TRH Gangotri","meals":"lunch en route, dinner at rest house","water":"available at rest house"},
    {"day":2,"title":"Gangotri to Bhojbasa","distance_km":14,"altitude_m":3780,"hours":7.5,"terrain":"forest trail, streamside","description":"Trek starts at Gangotri Mandarin temple (3100m). Path ascends via Chirbasa forest camp (3300m, rest point). Bhojbasa meadow (3780m) sits at the widest point of Bhagirathi valley. Evening light on Bhagirathi South peak (6512m). Overnight at Bhojbasa camp.","campsite":"tented camp Bhojbasa","meals":"packed breakfast, trail lunch, campfire dinner","water":"Bhagirathi stream (purify)"},
    {"day":3,"title":"Bhojbasa to Gaumukh to Tapovan to Nandanvan","distance_km":9,"altitude_m":4350,"hours":8,"terrain":"moraine, meadow, alpine glacier","description":"Early start to Gaumukh glacier snout (4050m, ~4 km, 2 hrs) where Ganga emerges from ice cave—sacred source. Continue steeply to Tapovan meadow (4350m, ~5 km, 4 hrs). Tapovan spans 2+ km of alpine grass at base of Shivling (6543m, dramatic pyramid). Descent 2 km to Nandanvan camp (near Mauni Baba Ashram). Overnight at Nandanvan.","campsite":"tented camp near Mauni Baba Ashram, Nandanvan","meals":"packed breakfast, trail lunch, camp dinner","water":"Tapovan spring (safe), Ganga meltwater (treat)"},
    {"day":4,"title":"Nandanvan exploration day","distance_km":6,"altitude_m":4350,"hours":5,"terrain":"alpine meadow, glacier margin","description":"Rest and explore Tapovan: Shivling base camp views, rhododendron micro-forests, prayer flags, sadhus'' caves, glacial lake margins. Optional: ascend Nandanvan peak (4700m, 3 hrs round trip). Overnight at Nandanvan.","campsite":"tented camp Nandanvan","meals":"breakfast/lunch at camp, evening dinner","water":"Tapovan spring"},
    {"day":5,"title":"Nandanvan to Bhojbasa","distance_km":9,"altitude_m":3780,"hours":6.5,"terrain":"alpine meadow descent, moraine","description":"Leisurely descent via Tapovan → Gaumukh trail → Bhojbasa. Return via moraine to forest edge. Evening at Bhojbasa. Overnight at Bhojbasa.","campsite":"tented camp Bhojbasa","meals":"packed breakfast, trail lunch, camp dinner","water":"Bhagirathi stream"},
    {"day":6,"title":"Bhojbasa to Gangotri to Gangnani/Rishikesh","distance_km":264,"altitude_m":3100,"hours":16,"terrain":"downhill trek, then road","description":"Trek down to Gangotri (14 km, 6–7 hrs). Stop for lunch and permits handover. Drive to Gangnani (50 km, 2.5 hrs) thermal springs town for night, or push to Rishikesh (200 km, 8 hrs). Overnight Gangnani or Rishikesh.","campsite":"GMVN TRH Gangnani or hotel Rishikesh","meals":"breakfast at Bhojbasa, lunch at Gangotri, dinner en route","water":"available at towns"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Gangotri","lat":30.95,"lng":79.28,"altitude_m":3100,"day":1,"type":"trailhead"},
    {"name":"Chirbasa","lat":30.97,"lng":79.30,"altitude_m":3300,"day":2,"type":"campsite"},
    {"name":"Bhojbasa","lat":31.00,"lng":79.32,"altitude_m":3780,"day":2,"type":"campsite"},
    {"name":"Gaumukh Glacier Snout","lat":31.05,"lng":79.35,"altitude_m":4050,"day":3,"type":"glacier"},
    {"name":"Tapovan Meadows","lat":31.07,"lng":79.36,"altitude_m":4350,"day":3,"type":"meadow"},
    {"name":"Shivling Peak","lat":31.06,"lng":79.38,"altitude_m":6543,"day":3,"type":"summit"},
    {"name":"Nandanvan (Mauni Baba Ashram)","lat":31.04,"lng":79.34,"altitude_m":4200,"day":3,"type":"campsite"},
    {"name":"Gangnani","lat":30.72,"lng":79.18,"altitude_m":1200,"day":6,"type":"junction"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Delhi → Rishikesh (240 km, 6 hrs) via NH119. Rishikesh → Uttarkashi (140 km, 5 hrs). Uttarkashi → Gangotri (100 km, 4 hrs, steep mountain road). GMVN operates packages from Rishikesh. Alternatively, Delhi → Dehradun (rail) → Rishikesh. Private jeep/taxi available at Rishikesh (cost ₹3000–5000 one-way to Gangotri). No public buses directly; book via GMVN (uttarkashitourism.gov.in) or trekking operators.'),
  permit_details = COALESCE(permit_details, 'Forest Permit required (₹500–800, valid 7 days) issued by Uttarkashi District Forest Office. Apply 1–2 weeks ahead OR get same-day at Uttarkashi office (9 am–1 pm). Required documents: photo ID (Aadhaar/passport), 2 passport-size photos. Foreign nationals permitted (no Inner Line restriction). Permit fee refundable if trek cancelled due to weather. GMVN packages include permit fee; private trekkers must self-register at office.'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":22000,"with_guide":26000,"with_operator":35000,"note":"Budget: GMVN package (transport Rishikesh–Gangotri, tents, meals at camps, local guide). With_guide: experienced Garhwal guide (₹500/day, accustomed to high-altitude, Shivling familiarity). With_operator: premium (GMVN or Himalayan Hikers, includes pre-trek briefing, weather contingency, satellite comms). Costs exclude personal travel to Rishikesh, permits (₹500–800), and insurance. 2026 rates; confirm with operators."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Reliable: Bhagirathi stream (treat all meltwater). Bhojbasa: camp staff has boiled water. Tapovan spring near Mauni Baba Ashram (traditionally considered pure by sadhus; locals drink untreated, but filter/boil recommended). Gaumukh glacier melt (giardia risk—MUST treat). Nandanvan: limited standing water (collect early). Carry: purification tablets (Micropur), filter, 1.5L capacity. Above 4000m: all water from glacial melt—treat as contaminated.'),
  network_coverage = COALESCE(network_coverage, 'Gangotri: BSNL 2G voice (unreliable, data nonexistent). Chirbasa–Bhojbasa: NO signal. Gaumukh–Tapovan: ZERO coverage. GMVN carries radio/sat-phone for emergencies. Do NOT expect to message family from trail. Inform hotel in Gangotri of expected return date. Torch: bring spare batteries (shops in Gangotri expensive). Power bank rarely usable above 3500m (cold kills batteries).'),
  emergency_contacts = COALESCE(emergency_contacts, 'SDRF Uttarakhand: 1070. Uttarkashi Police: +91-1374-225701. Uttarkashi DM Office: +91-1374-225701. ITBP Uttarkashi: +91-1374-225800 (nearest armed force). Gangotri helipad coordinates provided by GMVN pre-trek. For altitude sickness (AMS/HACE): immediate descent to Bhojbasa or below. Evacuation: helicopter from Uttarkashi (weather dependent, 3–4 hrs response).'),
  nearest_hospital = COALESCE(nearest_hospital, 'CHC Uttarkashi (100 km downhill, ~5 hrs): basic surgery, OB/GYN. Serious cases: Himalayan Hospital Dehradun (280 km) or AIIMS Rishikesh (320 km) for advanced care. Altitude illness (HACE/HAPE) requires descent + O₂ + evacuation. Pre-trek: anyone with cardiac/respiratory history should clear with cardiologist.'),
  source_url = COALESCE(source_url, 'https://uttarakhandtourism.gov.in/gangotri-gaumukh-tapovan'),
  last_reviewed_at = NOW()
WHERE id = 'gaumukh-tapovan-trek';

-- source: https://www.euttaranchal.com/tourism/kafni-glacier-trek.php, https://himalvin.com/trek/kafni-glacier-trek/
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Kathgodam to Bageshwar","distance_km":245,"altitude_m":940,"hours":9,"terrain":"road","description":"Drive from Kathgodam (Nainital rail hub) via Bhimtal, Almora (tea gardens), Kosi River valley to Bageshwar confluence town. Overnight at rest house or private lodge.","campsite":"hotel/guesthouse Bageshwar","meals":"lunch en route, dinner at hotel","water":"available at town"},
    {"day":2,"title":"Bageshwar to Loharkhet","distance_km":38,"altitude_m":1450,"hours":4,"terrain":"road, mountain pass","description":"Drive from Bageshwar (940m) via Kapkot to Loharkhet (1450m, small hamlet on Saryu river banks). Trek scouts assemble here. Overnight at rest house/homestay.","campsite":"KMVN TRH or homestay Loharkhet","meals":"packed lunch, home-cooked dinner","water":"Saryu river (treat)"},
    {"day":3,"title":"Loharkhet to Khati","distance_km":14,"altitude_m":2000,"hours":5,"terrain":"forest trail, river crossings","description":"Trek up Saryu valley through pine-oak forest. Khati village (2000m, confluence of Sunderdhunga & Pindari rivers) is largest inhabited village en-route to 3 glaciers. Overnight at Khati.","campsite":"homestay or KMVN camp Khati","meals":"packed breakfast, trail lunch, home dinner","water":"Sunderdhunga stream (treat)"},
    {"day":4,"title":"Khati to Dwali","distance_km":13,"altitude_m":2600,"hours":6,"terrain":"alpine forest, ridge","description":"Trek ascends past shepherd settlements. Dwali camp (2600m) sits at convergence of Kafni & Pindari rivers. Transition from forest to alpine meadow. Overnight at Dwali.","campsite":"tented camp Dwali","meals":"packed breakfast, trail lunch, camp dinner","water":"Kafni stream (treat)"},
    {"day":5,"title":"Dwali to Wachum","distance_km":14,"altitude_m":3000,"hours":6,"terrain":"alpine meadow, rocky trail","description":"Ascend via meadows to Wachum (3000m, shepherds'' summer settlement). Views of Nandakot and distant snowy peaks. Overnight at Wachum.","campsite":"tented camp Wachum","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial stream (treat all melt)"},
    {"day":6,"title":"Wachum to Kafni Glacier","distance_km":10,"altitude_m":3980,"hours":5,"terrain":"moraine, rocky alpine","description":"Final ascent to Kafni Glacier base (3980m). Cirque glacier surrounded by Nandakot and unnamed 4000m+ peaks. Remote, untouched. Alpine wildflowers June–July. Explore glacier margins, no climbing. Overnight at glacier camp.","campsite":"tented camp near glacier snout","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (MUST treat)"},
    {"day":7,"title":"Kafni to Dwali (return)","distance_km":24,"altitude_m":2600,"hours":8,"terrain":"downhill alpine and meadow","description":"Long descent back to Dwali via Wachum. Easier downhill trekking but knee-intensive. Full camp at Dwali.","campsite":"tented camp Dwali","meals":"packed breakfast, trail lunch, camp dinner","water":"Kafni stream"},
    {"day":8,"title":"Dwali to Khati to Loharkhet (return journey)","distance_km":27,"altitude_m":1450,"hours":9,"terrain":"downhill forest and river valleys","description":"Trek down to Khati (13 km, 5 hrs), then drive to Loharkhet (14 km, 1 hr). Overnight at Loharkhet or drive to Bageshwar.","campsite":"hotel Bageshwar or Loharkhet","meals":"packed breakfast, trail lunch, dinner at town","water":"Saryu river"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Bageshwar","lat":29.85,"lng":80.18,"altitude_m":940,"day":1,"type":"trailhead"},
    {"name":"Loharkhet","lat":29.88,"lng":80.27,"altitude_m":1450,"day":2,"type":"junction"},
    {"name":"Khati Village","lat":29.93,"lng":80.35,"altitude_m":2000,"day":3,"type":"campsite"},
    {"name":"Dwali","lat":29.95,"lng":80.38,"altitude_m":2600,"day":4,"type":"campsite"},
    {"name":"Wachum Meadow","lat":29.98,"lng":80.42,"altitude_m":3000,"day":5,"type":"meadow"},
    {"name":"Kafni Glacier","lat":30.00,"lng":80.45,"altitude_m":3980,"day":6,"type":"glacier"},
    {"name":"Nandakot Peak","lat":30.02,"lng":80.47,"altitude_m":4000,"day":6,"type":"summit"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Kathgodam (Nainital rail hub) → Bageshwar (245 km, 9 hrs) via Almora. Bageshwar → Loharkhet (38 km, 4 hrs). No public bus to Loharkhet; hire shared jeep or private taxi (₹1200–1800). Trek operators: book 30 days ahead. Bageshwar is the supply hub for Pindari, Kafni, Sunderdhunga glaciers; guides available at Loharkhet or Khati.'),
  permit_details = COALESCE(permit_details, 'NO government permit required, but trek is remote and rarely done. MANDATORY: hire experienced guide from Bageshwar/Loharkhet (local guides know route; many Western trekkers skip this trek, trail can fade). Guide cost: ₹600–800/day. Book guide 30 days ahead via trekking operator or KMVN. Medical fitness certificate recommended (trek is easy but long).'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":18000,"with_guide":22000,"with_operator":28000,"note":"Budget: tents, food, base guide (₹650/day). With_guide: senior Kumaon guide familiar with all 3 glacier routes. With_operator: Indiahikes or local operator (includes safety, weather briefing, porter). Costs exclude travel to Bageshwar. 2026 rates subject to fuel inflation."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Khati: Sunderdhunga stream (treat). Dwali–Wachum: Kafni & Pindari river confluences (glacial melt, giardia risk—filter + boil). Glacier camp: only glacial melt (MUST treat). Carry 2L capacity per person. Above 3000m: all water from melt/snowmelt. Purification: tablets (Micropur) or UV pen (battery-intensive at high altitude).'),
  network_coverage = COALESCE(network_coverage, 'Loharkhet: BSNL 2G voice (spotty). Khati: occasional signal if tower in range. Dwali–Kafni: ZERO coverage. No data anywhere. Inform hotel/operator of 8-day no-contact window. Torch essential (nights 10+ hrs at high altitude). Power banks useless above 3500m (cold drains in minutes).'),
  emergency_contacts = COALESCE(emergency_contacts, 'SDRF Uttarakhand: 1070. Bageshwar Police: +91-5963-205301. Kausani Police Post: +91-5963-245206. Nearest armed force: ITBP patrol at Khati (seasonal). Helicopter evacuation: Bageshwar airstrip (weather dependent). For AMS: immediate descent to Dwali or Khati. Operator carries satellite communicator on most commercial treks.'),
  nearest_hospital = COALESCE(nearest_hospital, 'CHC Bageshwar (basic, 245 km away): blood, surgery, OB/GYN. Serious cases: Himalayan Hospital Dehradun (350 km) or AIIMS Rishikesh (400 km). Pre-trek: anyone with a history of pulmonary edema should avoid this trek (Kafni glacier isolates at 4000m for 2 days).'),
  source_url = COALESCE(source_url, 'https://www.euttaranchal.com/tourism/kafni-glacier-trek.php'),
  last_reviewed_at = NOW()
WHERE id = 'kafni-glacier-trek';

-- source: https://www.stayvista.com/blog/kailash-mansarovar-yatra-2026/, https://newsable.asianetnews.com/world/kailash-manasarovar-yatra-2026
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Delhi assembly and medical screening","distance_km":0,"altitude_m":216,"hours":6,"terrain":"city","description":"Selected yatris report to designated Delhi hotel/AIIMS for 1-day medical fitness screening. Blood tests, ECG, chest X-ray, doctor''s clearance. Receive expedition kit (rain jacket, sleeping bag, oxygen if prescribed). Briefing on altitude sickness symptoms. Overnight in Delhi.","campsite":"KMVN-arranged Delhi hotel","meals":"breakfast, lunch, tea, dinner (provided)","water":"available at hotel"},
    {"day":2,"title":"Delhi to Pithoragarh","distance_km":560,"altitude_m":1627,"hours":14,"terrain":"road","description":"Early flight or drive from Delhi to Pithoragarh (via Kathgodam rail hub, then taxi). Overnight at KMVN Pithoragarh.","campsite":"KMVN TRH Pithoragarh","meals":"lunch en route, dinner at rest house","water":"available"},
    {"day":3,"title":"Pithoragarh to Dharchula","distance_km":96,"altitude_m":910,"hours":5,"terrain":"road, Himalayan passes","description":"Drive to Dharchula. Final preparations, permit collection (MEA-handled, not individual SDM process). Overnight Dharchula.","campsite":"KMVN TRH Dharchula","meals":"lunch en route, dinner at TRH","water":"available"},
    {"day":4,"title":"Dharchula to Gunji to Navidhang (motorable)","distance_km":71,"altitude_m":3800,"hours":6,"terrain":"motorable road and walking","description":"Drive to Gunji (3200m), then walk to Navidhang (3800m, first Tibetan village). Trail passes through Kalapani sacred confluence. Overnight at Navidhang.","campsite":"KMVN camp Navidhang","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial streams (boiled by staff)"},
    {"day":5,"title":"Navidhang to Lipulekh Pass","distance_km":16,"altitude_m":5334,"hours":4,"terrain":"high-altitude alpine ridge","description":"Trek from Navidhang to Lipulekh Pass (5334m) on Indo-Tibet border. Yatris typically rest 1 day here for acclimatization and administrative handoff to Chinese guide service. Overnight at Lipulekh.","campsite":"basic shelter at Lipulekh","meals":"packed food, hot water","water":"melted snow (boiled)"},
    {"day":6,"title":"Lipulekh to Tirthapuri (enter Tibet)","distance_km":30,"altitude_m":4500,"hours":8,"terrain":"high-altitude walking and motorable stretches","description":"Cross into Tibet (China). Trek/motor toward Tirthapuri (natural hot springs sacred site). Chinese liaison officer joins yatra. Overnight accommodation arranged by Chinese operators.","campsite":"Tibetan camp","meals":"Chinese-provided meals","water":"hot springs available"},
    {"day":7,"title":"Tirthapuri to Mansarovar (Lake)","distance_km":60,"altitude_m":4588,"hours":12,"terrain":"high-altitude road and lakeside walk","description":"Drive to Lake Mansarovar (4588m, highest freshwater lake in world). Arrive late evening. Yatris perform ritual circumambulation (kora) of lake next day.","campsite":"lakeside camp","meals":"Chinese logistics","water":"Mansarovar water (boiled for drinking)"},
    {"day":8,"title":"Mansarovar circumambulation and parikrama","distance_km":88,"altitude_m":4588,"hours":4,"terrain":"high-altitude lakeside trail","description":"Complete 3-day Lake Mansarovar kora (88 km clockwise, spiritual circumambulation). Yatris walk 25–30 km/day with camp breaks. Sacred sites: Cha Gompa, Yamadwar, Chiu Gompa. Peak acclimatization window.","campsite":"lakeside camps","meals":"Chinese provided meals","water":"Mansarovar (treated)"},
    {"day":11,"title":"Mansarovar to Kailash base (Drira-Puk)","distance_km":80,"altitude_m":4575,"hours":12,"terrain":"high-altitude plateau road and alpine trail","description":"Motor/trek from Mansarovar toward Mount Kailash. Approach Drira-Puk (eastern base camp, 5000m+). Overnight at base camp.","campsite":"Kailash base camp","meals":"Chinese-provided","water":"glacial melt (treated)"},
    {"day":12,"title":"Kailash parikrama Day 1: Drira-Puk to Droljma-Puk","distance_km":20,"altitude_m":5450,"hours":8,"terrain":"high-altitude pass and alpine ridge","description":"Begin 52-km Kailash circumambulation (parikrama). Trek from east base to south base (Droljma-Puk) via Dolma La pass (5,630m, \\\"the Gate of Heaven\\\"). Highest point of yatra. Prayer flags, sacred stones. Overnight at Droljma-Puk camp.","campsite":"south base camp","meals":"Tibetan camp food, hot tea","water":"snowmelt (boiled)"},
    {"day":13,"title":"Kailash parikrama Day 2: Droljma-Puk to Zuthul-Phuk","distance_km":17,"altitude_m":5100,"hours":6,"terrain":"rocky alpine trail","description":"Trek west from south to west base (Zuthul-Puk). Views of Kailash North Face. Overnight at west base camp.","campsite":"west base camp","meals":"camp food","water":"glacial streams"},
    {"day":14,"title":"Kailash parikrama Day 3: Zuthul-Phuk to Gyanak (complete kora)","distance_km":15,"altitude_m":4575,"hours":5,"terrain":"downhill alpine trail to plateau","description":"Final leg of parikrama from west to north base (Gyanak). Complete 52-km circumambulation. Rest day at Gyanak. Overnight camp.","campsite":"northern base camp Gyanak","meals":"camp provisions","water":"available"},
    {"day":15,"title":"Rest/exploration at Kailash","distance_km":5,"altitude_m":4575,"hours":3,"terrain":"high-altitude acclimatization","description":"Final day to rest or visit nearby monasteries (optional, if weather/time permits). Prepare for descent.","campsite":"Gyanak camp","meals":"camp meals","water":"glacial melt"},
    {"day":16,"title":"Descent from Kailash to Mansarovar","distance_km":80,"altitude_m":4588,"hours":12,"terrain":"high-altitude road","description":"Motor back to Lake Mansarovar. Rest overnight.","campsite":"Mansarovar lakeside","meals":"camp provided","water":"Mansarovar (treated)"},
    {"day":17,"title":"Mansarovar to Tirthapuri","distance_km":60,"altitude_m":4500,"hours":8,"terrain":"high-altitude road and hot springs","description":"Return to Tirthapuri (natural hot springs). Ritual bath. Overnight camp.","campsite":"Tirthapuri camp","meals":"provided","water":"hot springs"},
    {"day":18,"title":"Tirthapuri to Lipulekh (return to India)","distance_km":30,"altitude_m":5334,"hours":8,"terrain":"high-altitude ridge walk","description":"Trek back to Lipulekh Pass (5334m). Cross back into Indian territory. Formal border handoff. Overnight at Lipulekh.","campsite":"Lipulekh shelter","meals":"KMVN takeover of meals","water":"melted snow"},
    {"day":19,"title":"Lipulekh to Navidhang","distance_km":16,"altitude_m":3800,"hours":4,"terrain":"alpine descent","description":"Trek down from pass to Navidhang. Overnight Navidhang.","campsite":"KMVN camp Navidhang","meals":"KMVN meals","water":"treated glacial streams"},
    {"day":20,"title":"Navidhang to Gunji to Dharchula","distance_km":71,"altitude_m":910,"hours":6,"terrain":"motorable road downhill","description":"Drive from Navidhang to Dharchula. Border formalities (ITBP). Overnight Dharchula.","campsite":"KMVN TRH Dharchula","meals":"lunch en route, dinner at TRH","water":"available"},
    {"day":21,"title":"Dharchula to Pithoragarh","distance_km":96,"altitude_m":1627,"hours":5,"terrain":"road","description":"Drive to Pithoragarh. Overnight rest.","campsite":"KMVN TRH Pithoragarh","meals":"meals at TRH","water":"available"},
    {"day":22,"title":"Pithoragarh to Delhi","distance_km":560,"altitude_m":216,"hours":14,"terrain":"road or flight","description":"Drive or fly back to Delhi. Medical de-briefing (post-yatra health check). Expedition officially concludes.","campsite":"KMVN Delhi office or hotel","meals":"breakfast at TRH, lunch en route","water":"available"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Pithoragarh","lat":29.61,"lng":80.20,"altitude_m":1627,"day":2,"type":"junction"},
    {"name":"Dharchula","lat":29.75,"lng":80.25,"altitude_m":910,"day":3,"type":"trailhead"},
    {"name":"Gunji","lat":29.82,"lng":80.42,"altitude_m":3200,"day":4,"type":"campsite"},
    {"name":"Navidhang","lat":29.90,"lng":80.50,"altitude_m":3800,"day":4,"type":"campsite"},
    {"name":"Lipulekh Pass","lat":29.98,"lng":80.58,"altitude_m":5334,"day":5,"type":"pass"},
    {"name":"Mansarovar Lake","lat":30.95,"lng":81.50,"altitude_m":4588,"day":7,"type":"lake"},
    {"name":"Mount Kailash North Face","lat":31.07,"lng":81.31,"altitude_m":6638,"day":12,"type":"summit"},
    {"name":"Dolma La Pass","lat":31.05,"lng":81.29,"altitude_m":5630,"day":12,"type":"pass"},
    {"name":"Droljma-Puk (south base)","lat":31.06,"lng":81.32,"altitude_m":5450,"day":12,"type":"campsite"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Delhi → Pithoragarh (560 km, flight ~2.5 hrs or drive ~14 hrs) via Kathgodam rail hub. Apply online at kmy.gov.in. MEA conducts computerised draw from applicants. Selected yatris report to Delhi for medical screening. KMVN coordinates all logistics: flights, road transport, high-altitude camps, Chinese liaison, guides. NOTE: 2026 yatra has 1000 slots (20 batches of 50 each); demand far exceeds supply.'),
  permit_details = COALESCE(permit_details, 'GOVERNMENT-ONLY: MEA (Ministry of External Affairs) operates exclusive yatra. NO private operators. Apply at kmy.gov.in by published deadline. Selection via random computerised draw. Eligibility: Indian citizens, age 18–70, medical fitness (ECG, chest X-ray, blood tests). MANDATORY documents: Aadhaar, passport, medical report. Visa: MEA obtains Chinese visa on behalf of yatris. Medical clearance from AIIMS Delhi required. Foreign nationals and Chinese nationals NOT eligible. Permits include Lipulekh crossing authority (negotiated bilaterally by MEA).'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":330000,"with_guide":330000,"with_operator":330000,"note":"2026 MEA official yatra cost: ₹330,000 per person (fixed, uniform price, all-inclusive). Covers: Delhi assembly, medical screening, flights/transport, tents, meals, guides, liaison officer, emergency evacuation insurance, permits, Chinese visa. Does NOT cover: personal travel to Delhi, travel insurance, personal medications, phone recharges. Budget is identical across all batches—no optional upgrades. Payment via KMVN bank account after selection draw."}'::jsonb),
  water_sources = COALESCE(water_sources, 'India-side (Dharchula–Lipulekh): glacial melt, KMVN staff boil water. Tibet-side (Mansarovar–Kailash): Chinese yatra logistics provide boiled water at all camps. Mansarovar lake water: considered sacred, yatris perform ritual bathing (camp staff provide boiled drinking water separately). Above 4500m: all water from snowmelt (MUST boil). Yatris are instructed NOT to drink untreated water; stomach illness is common at high altitude and delays parikrama.'),
  network_coverage = COALESCE(network_coverage, 'Pithoragarh: BSNL 2G voice. Dharchula: BSNL spotty. Gunji: NO signal. Navidhang–Lipulekh: ZERO coverage. TIBET: NO personal mobile signal. Yatra organisers carry satellite phone/radio (MEA operates encrypted comms for emergencies only). Do NOT expect to contact family for 24 days. Pre-yatra: notify family/employer of complete communication blackout.'),
  emergency_contacts = COALESCE(emergency_contacts, 'MEA emergency desk: +91-11-2301-4242 (24/7, for families during yatra). Pithoragarh DM: +91-5964-225950. ITBP Mirthi: +91-1368-242000 (liaison at Lipulekh). Chinese yatra liaison: phone numbers provided at briefing. SDRF Uttarakhand: 1070 (India-side evacuation). Helicopter evacuation: MEA-coordinated, available from Pithoragarh or Munsiyari airstrips (weather dependent, 4–8 hrs response). High-altitude rescue: Chinese partners handle Kailash-area emergencies (rare; yatra has trained paramedics).'),
  nearest_hospital = COALESCE(nearest_hospital, 'Pre-trek medical: AIIMS Delhi (medical screening). India-side: CHC Dharchula (basic), District Hospital Pithoragarh (90 km). Tibet-side: Chinese military hospital in Lhasa (600+ km away, emergency helicopter flight only). ALTA ALTITUDE ILLNESS PROTOCOL: immediate descent + O₂ + evacuation. Yatra loses ~3% of participants to medical issues (mostly minor—headaches, nosebleeds, insomnia); serious cases (HACE/HAPE) occur ~0.5% (historical data). Medical kit on yatra: includes O₂, dexamethasone, aspirin, antibiotics.'),
  source_url = COALESCE(source_url, 'https://kmy.gov.in/'),
  last_reviewed_at = NOW()
WHERE id = 'kailash-mansarovar-yatra-trek';

-- source: https://www.euttaranchal.com/tourism/khatling-glacier-trek.php, https://peakadventuretour.com/khatling-glacier-trek.html
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Delhi to Rishikesh to Ghuttu","distance_km":400,"altitude_m":1200,"hours":14,"terrain":"road, mountain pass","description":"Early drive Delhi → Rishikesh (240 km, 6 hrs) → Uttarkashi forest office (permit town) → Ghuttu village (1200m, Tehri Garhwal). Ghuttu is the trailhead. Overnight at guesthouse.","campsite":"guesthouse Ghuttu","meals":"breakfast/lunch en route, dinner at lodge","water":"available at village"},
    {"day":2,"title":"Ghuttu to Reeh","distance_km":10,"altitude_m":1800,"hours":5,"terrain":"steep forest trail, riverside","description":"Steep ascent from Ghuttu (1200m) alongside River Devling. Rhododendron and pine forests. Reeh (1800m, small settlement, Reeh Chhani locals). Overnight at Reeh.","campsite":"KMVN camp or homestay Reeh","meals":"packed breakfast, trail lunch, camp dinner","water":"Devling stream (treat)"},
    {"day":3,"title":"Reeh to Gangi","distance_km":10,"altitude_m":2500,"hours":5,"terrain":"alpine meadows, ridge","description":"Trek via Panwali Kantha grasslands and ridges. Transition from forest to alpine meadow. Gangi village (2500m, last inhabited settlement, shepherds in summer). Overnight at Gangi.","campsite":"homestay or KMVN camp Gangi","meals":"packed breakfast, trail lunch, home dinner","water":"Gangi stream (treat)"},
    {"day":4,"title":"Gangi to Kharsali","distance_km":13,"altitude_m":3300,"hours":6,"terrain":"alpine meadow, rocky trail","description":"Light descent to Deokhri Channi (winter settlement of Gangi residents), then traverse open meadows (Birodh) and conifer groves. Kharsali camp (3300m) in meadow. Overnight at Kharsali.","campsite":"tented camp Kharsali","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial stream (treat)"},
    {"day":5,"title":"Kharsali to Bhedikharag","distance_km":16,"altitude_m":3700,"hours":7,"terrain":"dense forest, cave passages","description":"Trek via Bhelbagi, passing Bhumkodaar Cave and Tamakund Cave (natural shelters). Dense deodar and rhododendron forest. Bhedikharag camp (3700m). Overnight at Bhedikharag.","campsite":"tented camp Bhedikharag","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (treat)"},
    {"day":6,"title":"Bhedikharag to Khatling Glacier and return","distance_km":12,"altitude_m":3810,"hours":6,"terrain":"moraine, rocky glacier approach","description":"Day trek from Bhedikharag to Khatling Glacier (3810m). Explore glacier snout, moraine formations, blue crevasses (DO NOT CROSS). Return to Bhedikharag evening. Overnight at Bhedikharag.","campsite":"tented camp Bhedikharag","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (essential to treat)"},
    {"day":7,"title":"Bhedikharag to Reeh (return)","distance_km":29,"altitude_m":1800,"hours":8,"terrain":"downhill forest trail","description":"Long descent from Bhedikharag to Kharsali to Gangi to Reeh. Knee-intensive downhill. Overnight at Reeh or Ghuttu.","campsite":"guesthouse Ghuttu or Reeh","meals":"packed breakfast, trail lunch, dinner at lodge","water":"Devling river"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Ghuttu","lat":30.55,"lng":79.05,"altitude_m":1200,"day":1,"type":"trailhead"},
    {"name":"Reeh","lat":30.60,"lng":79.12,"altitude_m":1800,"day":2,"type":"campsite"},
    {"name":"Gangi Village","lat":30.65,"lng":79.18,"altitude_m":2500,"day":3,"type":"campsite"},
    {"name":"Panwali Kantha Grasslands","lat":30.63,"lng":79.15,"altitude_m":2200,"day":3,"type":"meadow"},
    {"name":"Kharsali","lat":30.68,"lng":79.22,"altitude_m":3300,"day":4,"type":"campsite"},
    {"name":"Bhedikharag","lat":30.72,"lng":79.28,"altitude_m":3700,"day":5,"type":"campsite"},
    {"name":"Khatling Glacier","lat":30.75,"lng":79.32,"altitude_m":3810,"day":6,"type":"glacier"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Delhi → Rishikesh (240 km, 6 hrs) → Uttarkashi (140 km, 5 hrs, forest office for permit) → Ghuttu (50 km, 2 hrs). Ghuttu is trailhead. Private jeep/taxi from Rishikesh (₹4000–5000 one-way). No public bus to Ghuttu; operators arrange pickups. Trek companies: book 30 days ahead. Alternative approach: Rishikesh → Chopta (via Chamba) for variation.'),
  permit_details = COALESCE(permit_details, 'Forest Permit required (₹500–600, valid 7–10 days) from Tehri District Forest Office at Uttarkashi. Apply 1–2 weeks ahead OR get same-day (office hours 9 am–1 pm). Required: photo ID (Aadhaar/passport), 2 photos. Guide is compulsory—hire experienced local from Ghuttu or via operator (₹600–800/day). Many trekkers skip this route; book guide 2 weeks in advance.'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":20000,"with_guide":24000,"with_operator":32000,"note":"Budget: tents, meals, base guide (₹700/day). With_guide: local Tehri guide experienced on Khatling. With_operator: premium operator (e.g., Himalayan Dream Treks), includes weather briefing, emergency coordination, porter. Costs exclude travel to Rishikesh. 2026 rates subject to fuel/food inflation."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Reeh: Devling river (treat). Gangi: Gangi stream. Kharsali–Bhedikharag: glacial meltwater (giardia risk—MUST filter + boil). Khatling glacier: snowmelt (essential to treat). Carry 2L capacity per person. Above 2500m: assume all water contaminated. Purification: tablets (Micropur), UV pen, or boiling 5 minutes.'),
  network_coverage = COALESCE(network_coverage, 'Ghuttu: BSNL 2G voice (unreliable). Reeh–Gangi: occasional signal. Kharsali–Khatling: ZERO coverage. No data anywhere. Inform operator/hotel of 7-day no-contact window. Bring torch + spare batteries (not available above Ghuttu). Power bank useless above 2500m (cold kills it).'),
  emergency_contacts = COALESCE(emergency_contacts, 'SDRF Uttarakhand: 1070. Uttarkashi Police: +91-1374-225701. Tehri Forest Office: +91-1374-205207. Ghuttu Police Post: +91-1374-238900 (nearest armed force, informal). Evacuation: helicopter from Uttarkashi airstrip (3–4 hrs response if weather clear). Operator carries radio or satellite communicator on most treks.'),
  nearest_hospital = COALESCE(nearest_hospital, 'CHC Uttarkashi (80 km downhill, 4 hrs): basic surgery, OB/GYN. Serious cases: Himalayan Hospital Dehradun (280 km) or AIIMS Rishikesh (320 km). Altitude illness (HACE/HAPE): immediate descent to Gangi or Reeh required. Pre-trek: cardiac/respiratory history should be cleared.'),
  source_url = COALESCE(source_url, 'https://www.euttaranchal.com/tourism/khatling-glacier-trek.php'),
  last_reviewed_at = NOW()
WHERE id = 'khatling-glacier-trek';

-- source: https://www.peakadventuretour.com/nandadevi-eastbase-camp.html, https://himalayanhikers.in/nanda-devi-base-camp-trek
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Kathgodam to Munsiyari","distance_km":310,"altitude_m":2200,"hours":12,"terrain":"road, mountain pass","description":"Drive from Kathgodam (Nainital rail hub) via Almora (tea region), Bageshwar, Kapkot to Munsiyari (2200m, Pithoragarh district). Munsiyari is the supply base for Nanda Devi treks. Overnight at guesthouse/rest house.","campsite":"hotel/KMVN TRH Munsiyari","meals":"lunch en route, dinner at hotel","water":"available at town"},
    {"day":2,"title":"Munsiyari to Lilam","distance_km":7,"altitude_m":1850,"hours":3,"terrain":"easy forest walk, river valley","description":"Trek from Munsiyari toward Lilam (1850m). Gentle start through pine forest alongside Gori Ganga river. Overnight at Lilam.","campsite":"KMVN camp or homestay Lilam","meals":"packed breakfast, trail lunch, camp dinner","water":"Gori Ganga (treat)"},
    {"day":3,"title":"Lilam to Bogudiar","distance_km":12,"altitude_m":2609,"hours":6.5,"terrain":"forest trail, river crossings","description":"Trek up alongside Gori Ganga through dense forests. Bogudiar (2609m) sits at river confluence. Overnight at Bogudiar.","campsite":"tented camp Bogudiar","meals":"packed breakfast, trail lunch, camp dinner","water":"Gori Ganga (treat)"},
    {"day":4,"title":"Bogudiar to Rilkot","distance_km":12,"altitude_m":3130,"hours":5.5,"terrain":"alpine forest, steep sections","description":"Ascend from Bogudiar through rhododendron and deodars to Rilkot (3130m). Transition from forest to alpine meadow. Overnight at Rilkot.","campsite":"tented camp Rilkot","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial stream (treat)"},
    {"day":5,"title":"Rilkot to Ghangar","distance_km":13,"altitude_m":3300,"hours":5.5,"terrain":"alpine meadow, rocky trail","description":"Trek across alpine meadows to Ghangar (3300m, shepherds'' summer settlement). Views of Panchachuli peaks to the north. Overnight at Ghangar.","campsite":"tented camp Ghangar","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (treat)"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Munsiyari","lat":30.04,"lng":80.77,"altitude_m":2200,"day":1,"type":"trailhead"},
    {"name":"Lilam","lat":30.08,"lng":80.82,"altitude_m":1850,"day":2,"type":"campsite"},
    {"name":"Bogudiar","lat":30.12,"lng":80.88,"altitude_m":2609,"day":3,"type":"campsite"},
    {"name":"Rilkot","lat":30.15,"lng":80.92,"altitude_m":3130,"day":4,"type":"campsite"},
    {"name":"Ghangar","lat":30.18,"lng":80.98,"altitude_m":3300,"day":5,"type":"campsite"},
    {"name":"Panchu Glacier","lat":30.20,"lng":81.02,"altitude_m":4000,"day":6,"type":"glacier"},
    {"name":"Nanda Devi East Base Camp","lat":30.22,"lng":81.05,"altitude_m":4750,"day":6,"type":"campsite"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Kathgodam (Nainital rail hub) → Munsiyari (310 km, 12 hrs) via Almora, Bageshwar, Kapkot. Shared jeeps: ₹800–1200 per seat. Private taxi: ₹4000–6000. Trek operators: book 30 days ahead for guide and tents. No public buses to Munsiyari; arrange pickups via operator or private vehicle.'),
  permit_details = COALESCE(permit_details, 'Permit required (₹200–400, valid 10 days) from District Magistrate office, Pithoragarh. Apply via trekking operator 2 weeks ahead. Documents: ID proof, 2 photos, medical certificate (recommended). Guide is compulsory—hire via operator or locally at Munsiyari (₹600–800/day). Many trekkers approach via operators for convenience.'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":16000,"with_guide":20000,"with_operator":26000,"note":"Budget: tents, meals, base guide (₹650/day). With_guide: experienced Munsiyari guide familiar with Nanda Devi approaches. With_operator: premium (e.g., Indiahikes, KMVN), includes safety briefing, porter, weather contingency. 5-day trek is short; costs exclude travel to Munsiyari. 2026 rates."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Lilam: Gori Ganga (treat). Bogudiar–Rilkot: Gori Ganga tributary (glacial melt, giardia—filter + boil). Ghangar–glacier: meltwater only (MUST treat). Carry 1.5L per person. Above 3000m: all water from melt. Purification: tablets (Micropur) or boiling 5 minutes.'),
  network_coverage = COALESCE(network_coverage, 'Munsiyari: BSNL 2G voice (unreliable). Lilam–Bogudiar: no signal. Rilkot–Ghangar: ZERO coverage. No data anywhere. Inform hotel of 5-day no-contact window. Bring torch (essential at high altitude, nights 10+ hrs). Power bank not usable above 3000m.'),
  emergency_contacts = COALESCE(emergency_contacts, 'SDRF Uttarakhand: 1070. Pithoragarh DM: +91-5964-225950. Munsiyari Police: +91-5963-204002. Nearest armed force: ITBP seasonal patrol (informally). Evacuation: helicopter from Munsiyari airstrip (4–5 hrs response if weather permits). Operator typically carries radio on commercial treks.'),
  nearest_hospital = COALESCE(nearest_hospital, 'District Hospital Pithoragarh (100 km, 4 hrs downhill): surgery, blood, OB/GYN. Serious cases: AIIMS Rishikesh (400 km) or Himalayan Hospital Dehradun (350 km). Nanda Devi East approach isolates at 4000m+; altitude illness (HACE/HAPE) requires immediate descent. Pre-trek: pulmonary/cardiac screening recommended.'),
  source_url = COALESCE(source_url, 'https://www.peakadventuretour.com/nandadevi-eastbase-camp.html'),
  last_reviewed_at = NOW()
WHERE id = 'nanda-devi-east-base-camp';

-- source: https://trekthehimalayas.com/pindari-glacier-trek, https://www.euttaranchal.com/tourism/pindari-glacier.php
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Kathgodam to Khati","distance_km":241,"altitude_m":2000,"hours":10,"terrain":"road, mountain pass","description":"Drive from Kathgodam (Nainital rail hub) via Bhimtal, Almora, Bageshwar, Kapkot to Kharkiya (motorable). Final 5 km trek to Khati village (2000m, confluence of Pindari & Sunderdhunga rivers). Overnight at Khati.","campsite":"KMVN camp or homestay Khati","meals":"lunch en route, packed dinner at camp","water":"Pindari stream (treat)"},
    {"day":2,"title":"Khati to Dwali","distance_km":13,"altitude_m":2600,"hours":7,"terrain":"river valley walk, alpine forest","description":"Trek alongside Pindar River through oak-pine forest. Dwali camp (2600m) sits at convergence of Kafni and Pindari rivers. Overnight at Dwali.","campsite":"tented camp Dwali","meals":"packed breakfast, trail lunch, camp dinner","water":"Pindari stream (treat)"},
    {"day":3,"title":"Dwali to Phurkia","distance_km":5,"altitude_m":3200,"hours":3.5,"terrain":"steep alpine meadow climb","description":"Short but steep ascent (600m gain in 5 km) from 2600m to Phurkia (3200m). Rocky alpine meadow. Overnight at Phurkia.","campsite":"tented camp Phurkia","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial stream (treat)"},
    {"day":4,"title":"Phurkia to Zero Point and return","distance_km":14,"altitude_m":3660,"hours":7,"terrain":"moraine, rocky glacier","description":"Day trek to Pindari Glacier Zero Point (3660m, 7 km, 3 hrs up). Explore glacier snout, moraine formations, blue crevasses. Return to Phurkia. Overnight at Phurkia.","campsite":"tented camp Phurkia","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (MUST treat)"},
    {"day":5,"title":"Phurkia to Dwali","distance_km":5,"altitude_m":2600,"hours":3,"terrain":"downhill meadow and forest","description":"Descent from Phurkia to Dwali. Easier than ascent but knee-intensive. Overnight at Dwali.","campsite":"tented camp Dwali","meals":"packed breakfast, trail lunch, camp dinner","water":"Pindari stream"},
    {"day":6,"title":"Dwali to Khati","distance_km":13,"altitude_m":2000,"hours":6,"terrain":"downhill forest trail","description":"Long descent via Pindar valley. Overnight at Khati.","campsite":"KMVN camp or homestay Khati","meals":"packed breakfast, trail lunch, home/camp dinner","water":"Pindari stream"},
    {"day":7,"title":"Khati to Bageshwar to Kathgodam","distance_km":241,"altitude_m":940,"hours":10,"terrain":"road","description":"Drive from Khati to Bageshwar (trek out 5 km + 56 km drive, 2 hrs). Then drive to Kathgodam (185 km, 6–7 hrs). End trek.","campsite":"home or hotel Kathgodam","meals":"breakfast at Khati, lunch en route, dinner at home","water":"available at towns"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Kathgodam","lat":29.42,"lng":79.46,"altitude_m":1260,"day":1,"type":"trailhead"},
    {"name":"Kharkiya","lat":29.90,"lng":80.32,"altitude_m":1700,"day":1,"type":"junction"},
    {"name":"Khati Village","lat":29.93,"lng":80.35,"altitude_m":2000,"day":1,"type":"campsite"},
    {"name":"Dwali","lat":29.95,"lng":80.38,"altitude_m":2600,"day":2,"type":"campsite"},
    {"name":"Phurkia","lat":29.97,"lng":80.40,"altitude_m":3200,"day":3,"type":"campsite"},
    {"name":"Pindari Glacier Zero Point","lat":30.00,"lng":80.42,"altitude_m":3660,"day":4,"type":"glacier"},
    {"name":"Bageshwar","lat":29.85,"lng":80.18,"altitude_m":940,"day":7,"type":"junction"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Kathgodam (Nainital rail hub) → Almora → Bageshwar → Kapkot → Kharkiya (motorable road) → Khati (5 km trek, 2 hrs). Total drive: 241 km, 10 hrs. Shared jeeps from Kathgodam: ₹600–1000. Private taxi: ₹2500–3500. Trek operators available; book 2 weeks ahead for guide + tents.'),
  permit_details = COALESCE(permit_details, 'NO government permit required. Khati is gateway to 3 major glaciers (Pindari, Kafni, Sunderdhunga). Guide recommended (₹600–800/day) but not compulsory—hire locally at Khati or via operator. Many independent trekkers solo trek Pindari using previous trekker beta; trail is well-marked but remote guide adds safety (rescues on Phurkia are rare but documented).'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":13000,"with_guide":17000,"with_operator":22500,"note":"Budget: basic tents, meals, local guide (₹650/day). With_guide: experienced Kumaon guide, familiar with Pindari trail. With_operator: premium trek company (Indiahikes, Trek the Himalayas, KMVN), includes weather briefing, porter, emergency insurance. Costs exclude travel to Kathgodam. 2026 rates (₹13K–₹22.5K documented in search results)."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Khati: Pindari stream (treat). Dwali: Pindari & Kafni confluence (glacial melt, giardia—filter + boil). Phurkia–Zero Point: meltwater only (MUST treat). Carry 1.5L per person. Above 2600m: assume all water contaminated. Purification: tablets (Micropur), UV pen, or boiling 5 min.'),
  network_coverage = COALESCE(network_coverage, 'Bageshwar: BSNL 2G voice (unreliable). Khati: occasional signal. Dwali–Phurkia: ZERO coverage. No data anywhere. Inform hotel of 6–7-day no-contact window. Bring torch (essential, nights 9+ hrs). Power bank useless above 2500m (cold drains battery instantly).'),
  emergency_contacts = COALESCE(emergency_contacts, 'SDRF Uttarakhand: 1070. Bageshwar Police: +91-5963-205301. Kausani Police Post: +91-5963-245206. ITBP: seasonal patrols at Khati (informal). Evacuation: helicopter from Bageshwar or Kausani airstrip (4–5 hrs response if weather permits). Trek operators carry radio on most commercial trips.'),
  nearest_hospital = COALESCE(nearest_hospital, 'CHC Bageshwar (basic): blood, surgery, OB/GYN. Serious cases: Himalayan Hospital Dehradun (350 km, 8 hrs) or AIIMS Rishikesh (400 km, 9 hrs). Altitude illness (HACE/HAPE): immediate descent to Dwali or Khati needed. Pre-trek: anyone with pulmonary edema history should avoid this trek.'),
  source_url = COALESCE(source_url, 'https://trekthehimalayas.com/pindari-glacier-trek'),
  last_reviewed_at = NOW()
WHERE id = 'pindari-glacier-trek';

-- source: https://www.euttaranchal.com/tourism/sunderdhunga-glacier.php, https://indiahikes.com/documented-trek/sunderdhunga-trek/
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Kathgodam to Song","distance_km":245,"altitude_m":1220,"hours":9,"terrain":"road, river valley","description":"Drive from Kathgodam via Bhimtal, Almora, Bageshwar to Song village (1220m, Bageshwar district). Song sits on banks of Saryu river. Small settlement with rural character. Overnight at rest house/homestay.","campsite":"KMVN camp or homestay Song","meals":"lunch en route, home/camp dinner","water":"Saryu river (treat)"},
    {"day":2,"title":"Song to Khati","distance_km":14,"altitude_m":2000,"hours":5,"terrain":"forest trail, river valley","description":"Trek from Song (1220m) alongside Saryu river through pine-oak forest to Khati (2000m, junction village for Pindari, Kafni, Sunderdhunga). Overnight at Khati.","campsite":"KMVN camp or homestay Khati","meals":"packed breakfast, trail lunch, camp dinner","water":"Pindari/Sunderdhunga confluence (treat)"},
    {"day":3,"title":"Khati to Jaitoli","distance_km":12,"altitude_m":2400,"hours":5,"terrain":"alpine forest, steep sections","description":"Trek from Khati toward Sunderdhunga (different from Pindari direction). Path goes via Jaitoli (2400m). Remote trail with less foot traffic than Pindari. Overnight at Jaitoli.","campsite":"tented camp Jaitoli","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial stream (treat)"},
    {"day":4,"title":"Jaitoli to Dudhia Dhaung","distance_km":13,"altitude_m":3000,"hours":6,"terrain":"alpine meadow, rocky trail","description":"Trek through alpine meadows and rocky sections (\\\"Sunderdhunga\\\" = \\\"valley of beautiful stones\\\"). Dudhia Dhaung (3000m, shepherd settlement). More remote than Pindari route. Overnight at Dudhia Dhaung.","campsite":"tented camp Dudhia Dhaung","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (treat)"},
    {"day":5,"title":"Dudhia Dhaung to Kathalia","distance_km":14,"altitude_m":3400,"hours":6,"terrain":"rocky alpine, moraine","description":"Trek via rocky alpine sections and moraine benches to Kathalia (3400m). Sparse vegetation, stunning views of Maiktoli and Mrigthuni peaks. Overnight at Kathalia.","campsite":"tented camp Kathalia","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial stream (MUST treat)"},
    {"day":6,"title":"Kathalia to Maiktoli Base Camp","distance_km":8,"altitude_m":3950,"hours":4,"terrain":"high-altitude rocky trail","description":"Final ascent to Maiktoli Base Camp (3950m, Sunderdhunga Glacier base). Untouched glacier, blue crevasses, icy beauty. Remote and pristine. Overnight at base camp.","campsite":"tented camp Maiktoli BC","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (MUST treat)"},
    {"day":7,"title":"Maiktoli Base Camp exploration","distance_km":3,"altitude_m":3950,"hours":3,"terrain":"high-altitude glacier","description":"Rest/exploration day at glacier base. Optional: acclimatization walk around glacier margins. Overnight at camp.","campsite":"tented camp Maiktoli BC","meals":"breakfast/lunch at camp, evening dinner","water":"glacial melt"},
    {"day":8,"title":"Maiktoli BC to Kathalia to Dudhia Dhaung","distance_km":22,"altitude_m":3000,"hours":8,"terrain":"downhill rocky and meadow","description":"Descent to Kathalia (8 km, 3 hrs) then Dudhia Dhaung (14 km, 5 hrs). Long day. Overnight at Dudhia Dhaung.","campsite":"tented camp Dudhia Dhaung","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial streams"},
    {"day":9,"title":"Dudhia Dhaung to Jaitoli to Khati to Song (return)","distance_km":39,"altitude_m":1220,"hours":11,"terrain":"downhill forest and river valley","description":"Long return trek: Dudhia Dhaung to Jaitoli (13 km, 4 hrs) → Khati (12 km, 4 hrs) → Song (14 km, 3 hrs drive/trek). Drive or trek return. Overnight at Song or continue to Bageshwar/home.","campsite":"hotel Song or home","meals":"packed breakfast/lunch, dinner at Song/Bageshwar","water":"Saryu river"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Song Village","lat":29.88,"lng":80.20,"altitude_m":1220,"day":1,"type":"trailhead"},
    {"name":"Khati Village","lat":29.93,"lng":80.35,"altitude_m":2000,"day":2,"type":"campsite"},
    {"name":"Jaitoli","lat":29.95,"lng":80.38,"altitude_m":2400,"day":3,"type":"campsite"},
    {"name":"Dudhia Dhaung","lat":29.98,"lng":80.42,"altitude_m":3000,"day":4,"type":"campsite"},
    {"name":"Kathalia","lat":30.02,"lng":80.46,"altitude_m":3400,"day":5,"type":"campsite"},
    {"name":"Maiktoli Base Camp (Sunderdhunga Glacier)","lat":30.05,"lng":80.50,"altitude_m":3950,"day":6,"type":"glacier"},
    {"name":"Maiktoli Peak","lat":30.06,"lng":80.52,"altitude_m":4000,"day":6,"type":"summit"},
    {"name":"Bageshwar","lat":29.85,"lng":80.18,"altitude_m":940,"day":9,"type":"junction"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Kathgodam (Nainital rail hub) → Song (245 km, 9 hrs) via Almora, Bageshwar. Shared jeep: ₹700–1200. Private taxi: ₹3500–5000. Trek operators: book 30+ days ahead (less popular than Pindari; fewer operators). No public buses to Song; arrange via operator or private vehicle.'),
  permit_details = COALESCE(permit_details, 'NO government permit required. Guide is recommended (₹600–800/day) but not compulsory—hire locally at Khati or via operator. Sunderdhunga is remote and less-traversed; guide adds safety margin (many trekkers skip this route due to remoteness). Book guide 2–3 weeks in advance via operator.'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":18000,"with_guide":22000,"with_operator":28000,"note":"Budget: tents, meals, local guide (₹650/day). With_guide: senior Kumaon guide, experienced in remote high-altitude sections. With_operator: premium operator (Indiahikes prefers Sunderdhunga for pristine conditions), includes weather contingency, rescue insurance, porter. 9-day trek is longer than Pindari; costs exclude Kathgodam travel. 2026 rates."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Song: Saryu river (treat). Khati: Sunderdhunga/Pindari confluence (treat). Jaitoli–Maiktoli: all glacial melt (giardia, silt—MUST filter + boil). Carry 1.5L per person. Above 2400m: assume all water contaminated. Purification: tablets (Micropur) or boiling 5 min minimum.'),
  network_coverage = COALESCE(network_coverage, 'Bageshwar: BSNL 2G (unreliable). Song–Khati: no signal. Jaitoli–Maiktoli: ZERO coverage. No data anywhere. This trek isolates for 9 days. Inform operator/hotel of complete blackout window. Bring torch + extra batteries. Power bank useless above 2500m.'),
  emergency_contacts = COALESCE(emergency_contacts, 'SDRF Uttarakhand: 1070. Bageshwar Police: +91-5963-205301. Song Police (informal, nearest): +91-5963-208000. Evacuation: helicopter from Bageshwar airstrip (4–6 hrs response if weather clear, difficult at Maiktoli altitude). Operator carries radio. Sunderdhunga''s remoteness = slower rescue window than Pindari.'),
  nearest_hospital = COALESCE(nearest_hospital, 'CHC Bageshwar (basic): blood, surgery. Serious cases: Himalayan Hospital Dehradun (350 km, 8 hrs) or AIIMS Rishikesh (400 km, 9 hrs). Altitude sickness (HACE/HAPE): immediate descent to Kathalia or Dudhia Dhaung. Maiktoli isolates trekkers at 3950m for 2 days; high-altitude illness is more serious here. Pre-trek: rigorous health screening recommended.'),
  source_url = COALESCE(source_url, 'https://www.euttaranchal.com/tourism/sunderdhunga-glacier.php'),
  last_reviewed_at = NOW()
WHERE id = 'sunderdhunga-glacier-trek';

-- source: https://himalayanhikers.in/vasuki-tal-trek, https://www.euttaranchal.com/tourism/vasuki-tal.php
UPDATE treks SET
  day_by_day = COALESCE(day_by_day, '[
    {"day":1,"title":"Rishikesh to Kedarnath Temple","distance_km":240,"altitude_m":3583,"hours":10,"terrain":"road, mountain pass, temple town","description":"Drive from Rishikesh (240 km, 10 hrs) via Chopta, Okhimath to Kedarnath temple (3583m, one of the 4 Chardham shrines). Acclimatization overnight at Kedarnath rest house. Optional: temple darshan, Chorabari glacier viewpoint.","campsite":"KMVN TRH or guesthouse Kedarnath","meals":"lunch en route, dinner at rest house","water":"available at temple town"},
    {"day":2,"title":"Acclimatization day at Kedarnath","distance_km":6,"altitude_m":3900,"hours":4,"terrain":"high-altitude walk, glacier views","description":"Rest day for acclimatization. Optional light trek to Chorabari Glacier (ancient glacier, 3900m, 2 km, 1 hr). Or visit Kedarnath temple interiors, local shrines. Overnight at Kedarnath.","campsite":"KMVN TRH Kedarnath","meals":"breakfast/lunch at rest house, dinner at temple","water":"available at Kedarnath"},
    {"day":3,"title":"Kedarnath to Nandanvan (Vasuki Tal high camp)","distance_km":10,"altitude_m":3900,"hours":5.5,"terrain":"high-altitude meadow, glacier moraine","description":"Trek from Kedarnath via Vasuki Top and Chorabari Glacier moraines to Nandanvan (3900m, high camp with views of Kedar peaks). Forest trail → alpine meadow → glacier approach. Overnight at Nandanvan.","campsite":"tented camp Nandanvan","meals":"packed breakfast, trail lunch, camp dinner","water":"glacial melt (treat)"}
  ]'::jsonb),
  trail_points = COALESCE(trail_points, '[
    {"name":"Rishikesh","lat":30.09,"lng":78.28,"altitude_m":256,"day":1,"type":"trailhead"},
    {"name":"Kedarnath Temple","lat":30.73,"lng":79.25,"altitude_m":3583,"day":1,"type":"campsite"},
    {"name":"Chorabari Glacier","lat":30.74,"lng":79.26,"altitude_m":3900,"day":2,"type":"glacier"},
    {"name":"Vasuki Top","lat":30.75,"lng":79.27,"altitude_m":3950,"day":3,"type":"pass"},
    {"name":"Nandanvan Camp","lat":30.76,"lng":79.28,"altitude_m":3900,"day":3,"type":"campsite"},
    {"name":"Vasuki Tal (alpine lake)","lat":30.77,"lng":79.29,"altitude_m":4135,"day":3,"type":"lake"}
  ]'::jsonb),
  how_to_reach = COALESCE(how_to_reach, 'Rishikesh → Chopta (170 km, 5 hrs) → Okhimath (60 km, 2 hrs) → Kedarnath (70 km, 3 hrs, footpath from last village is motorable). Alternative: fly Delhi → Dehradun (2 hrs) → Rishikesh (1.5 hrs) → Kedarnath (12 hrs overland). Trek from Rishikesh is traditionally done by foot-road; modern versions use jeeps to Chopta or Okhimath. GMVN operates packages from Rishikesh; book 2 weeks ahead.'),
  permit_details = COALESCE(permit_details, 'No special permit beyond Kedarnath temple entry fee (₹100–300, donated to temple trust). Pilgrimage site; managed by Kedarnath Temple authorities. Guide not compulsory but recommended for Vasuki Tal route (₹400–600/day). Local guides at Kedarnath village know route. Trek is less commercialized than other Uttarakhand routes.'),
  cost_estimate = COALESCE(cost_estimate, '{"budget":12000,"with_guide":15000,"with_operator":20000,"note":"Budget: tents, meals, basic guide (₹500/day). With_guide: local Kedarnath guide (often dharamshala-keeper), accustomed to pilgrims and high altitude. With_operator: GMVN or local operator, includes weather briefing, rescue coordination. Costs exclude Rishikesh travel and temple donations. 3-day trek is short; 2026 rates subject to inflation."}'::jsonb),
  water_sources = COALESCE(water_sources, 'Kedarnath: temple town water (treated). Chorabari: glacial melt (giardia—treat). Vasuki Tal: alpine lake water (filter, do not drink directly; glacial silt). Nandanvan: glacial melt only (MUST treat). Carry 1.5L per person. Above 3500m: all water from melt/snowmelt. Purification: tablets (Micropur), UV pen, or boiling 5 min.'),
  network_coverage = COALESCE(network_coverage, 'Kedarnath: BSNL 2G voice (spotty, prayer hours = silence). Vasuki Tal route: ZERO coverage. No data anywhere. Inform temple authorities/operator of 2–3 day no-contact window. Bring torch (essential, nights 11+ hrs at 4000m). Power bank useless in cold.'),
  emergency_contacts = COALESCE(emergency_contacts, 'GMVN Kedarnath office: +91-5964-223970. Rudraprayag Police: +91-1364-222224. SDRF Uttarakhand: 1070. ITBP Kedarnath (armed force present year-round): +91-1368-234200. Temple management coordinates rescue with SDRF. Evacuation: helicopter from Rudraprayag or Dehradun (3–4 hrs response, weather dependent).'),
  nearest_hospital = COALESCE(nearest_hospital, 'Kedarnath: temple first-aid center (emergency only, medicines limited). Rudraprayag (70 km downhill, 3 hrs): CHC with basic surgery, blood. Serious cases: Himalayan Hospital Dehradun (280 km) or AIIMS Rishikesh (260 km). Altitude sickness (HACE): immediate descent required. Pre-trek: anyone with cardiac/respiratory issues should clear with doctor.'),
  source_url = COALESCE(source_url, 'https://himalayanhikers.in/vasuki-tal-trek'),
  last_reviewed_at = NOW()
WHERE id = 'vasuki-tal-trek';
