#!/usr/bin/env node
/**
 * Upload videos from local videos/ folder to Cloudflare R2 bucket.
 * Run: node scripts/upload-videos.mjs
 * Requires: R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY in apps/web/.env.local
 */
import { S3Client, HeadObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import { readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join } from "path";

// --force re-uploads every file regardless of R2 state.
// Default: re-upload only when local byte size differs from R2 (catches
// replacement-in-place where the local file changed but R2 wasn't refreshed
// — agartala.mp4 showing Taj Mahal was exactly this on 2026-04-22).
const FORCE = process.argv.includes("--force");

// Load env from apps/web/.env.local
const envPath = "apps/web/.env.local";
const envContent = readFileSync(envPath, "utf-8");
const env = {};
for (const line of envContent.split("\n")) {
  const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.+)$/);
  if (m) env[m[1]] = m[2].trim();
}

const accountId = env.R2_ACCOUNT_ID;
const accessKeyId = env.R2_ACCESS_KEY_ID;
const secretAccessKey = env.R2_SECRET_ACCESS_KEY;
if (!accountId || !accessKeyId || !secretAccessKey) {
  console.error("Missing R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, or R2_SECRET_ACCESS_KEY in apps/web/.env.local");
  process.exit(1);
}

const client = new S3Client({
  region: "auto",
  endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
  credentials: { accessKeyId, secretAccessKey },
});

const BUCKET = "nakshiq-videos";
const LOCAL_DIR = "videos";

async function head(key) {
  try {
    return await client.send(new HeadObjectCommand({ Bucket: BUCKET, Key: key }));
  } catch {
    return null;
  }
}

async function main() {
  const localFiles = readdirSync(LOCAL_DIR).filter(
    (f) => f.endsWith(".mp4") && !f.includes(" 2") // skip duplicates
  );
  console.log(`Found ${localFiles.length} unique videos locally`);

  let uploaded = 0;
  let replaced = 0;
  let skipped = 0;
  let failed = 0;

  for (const f of localFiles) {
    // Strip VIDEO_ or ARTICLE_ prefix for bucket name
    const bucketName = f.replace(/^(VIDEO_|ARTICLE_)/, "");
    const filePath = join(LOCAL_DIR, f);
    const localSize = statSync(filePath).size;

    const r2 = await head(bucketName);
    let action = null;
    if (!r2) action = "new";
    else if (FORCE) action = "forced";
    else if (r2.ContentLength !== localSize) action = "replace";

    if (!action) { skipped++; continue; }

    const fileBuffer = readFileSync(filePath);
    const sizeLabel = `${(fileBuffer.length / 1024 / 1024).toFixed(1)}MB`;
    const prefix = action === "replace" ? `Replacing ${bucketName} (R2 had ${(r2.ContentLength/1024/1024).toFixed(1)}MB from ${r2.LastModified?.toISOString().slice(0,10)}, local ${sizeLabel})`
                 : action === "forced" ? `Forcing ${bucketName} (${sizeLabel})`
                 : `Uploading ${bucketName} (${sizeLabel})`;
    process.stdout.write(`${prefix}... `);

    try {
      await client.send(
        new PutObjectCommand({
          Bucket: BUCKET,
          Key: bucketName,
          Body: fileBuffer,
          ContentType: "video/mp4",
          CacheControl: "public, max-age=31536000, immutable",
        })
      );
      console.log("OK");
      if (action === "replace") replaced++;
      else uploaded++;
    } catch (err) {
      console.log(`FAILED: ${err.message}`);
      failed++;
    }
  }

  console.log(`\nDone: ${uploaded} new, ${replaced} replaced (size-mismatch), ${skipped} unchanged, ${failed} failed`);

  // If any video was new or replaced, bump the VIDEO_CACHE_VERSION constant
  // so the frontend appends a fresh ?v= query string — browsers with the
  // stale video cached re-fetch. YYYYMMDD is enough resolution for our
  // upload cadence; collisions within the same day are fine because the
  // set of replaced files is usually scoped to one session.
  if (uploaded + replaced > 0) {
    const versionPath = "apps/web/src/lib/video-version.ts";
    const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
    const contents = `// Auto-generated by scripts/upload-videos.mjs — do not edit by hand.
// Bumped every time at least one video is uploaded or replaced on R2, so
// browsers with a cached copy of a replaced file re-fetch on next view.
//
// The value is a YYYYMMDD date stamp; collisions within the same day are
// fine since we only care that the cache key changes between replacement
// batches. Older clients see the new URL, old URL stays valid.
export const VIDEO_CACHE_VERSION = "${stamp}";
`;
    writeFileSync(versionPath, contents);
    console.log(`Bumped VIDEO_CACHE_VERSION → ${stamp} (wrote ${versionPath})`);
  }
}

main();
