-- APPLIED 2026-10-09 (~21:45 AEDT) via scripts/run-sql-file.mjs. Not in schema_migrations. Idempotent (computed from the backup).
-- 086: stay rows still tagged by 080, corrected for season anchoring AND Diwali-week prices (2026-10-09).
-- Generated by scripts/build-stay-anchor-correction.mjs on 2026-10-09. Supersedes 084; idempotent (from backup).
--
-- Why: 080's 33 observed medians were priced for a 12-13 Nov 2026 stay. November is PEAK for most plains, coast and
-- Goa places (080 treated it as shoulder: ~35% high), and 12-13 Nov is Diwali holiday week (Lakshmi Puja 8 Nov 2026),
-- so 3-star and homestay prices are divided by the measured same-hotel Diwali premium (2026-10-09-diwali-week-premium-north.json, 2026-10-09-diwali-week-premium-west.json, 2026-10-09-diwali-week-premium-west2.json).
-- Observed rows: the season containing November gets the observed value; the others follow the model shape.
-- Low-November places (Ladakh, Kaza, Gulmarg...) are left as they are until a peak price is measured.
-- Calibrated rows where November is peak: shoulder = model shoulder x factor, peak/low keep 080's shape.
-- Factors (season for season, Diwali-deflated, 19 peak-November places): {"hotel-mid":0.722,"homestay":0.731,"hostel-dorm":0.634,"hotel-splurge":0.722}.
-- Rollback: UPDATE ... FROM backups.destination_costs_20261009 b WHERE id = b.id (restores pre-080).

BEGIN;

WITH obs(d, cat, shoulder, obs_v, diwali_ratio) AS (VALUES
('jaipur','hotel-mid',2185.43,2955,1.015),
('jaipur','homestay',2144.75,2912,1.015),
('jaipur','hostel-dorm',389.41,502,1),
('udaipur','hotel-mid',3502.56,4892,1.000),
('udaipur','homestay',1057.00,1476,1.000),
('udaipur','hostel-dorm',349.07,450,1),
('manali','hotel-mid',2062.34,2062,1.000),
('manali','homestay',2956.80,2957,1.000),
('manali','hostel-dorm',410.00,410,1),
('rishikesh','hotel-mid',2805.26,3780,1.000),
('rishikesh','homestay',1826.92,2474,1.000),
('rishikesh','hostel-dorm',312.62,403,1),
('darjeeling','hotel-mid',2889.72,3901,1.017),
('darjeeling','homestay',2044.75,2731,1.017),
('darjeeling','hostel-dorm',465.43,600,1),
('munnar','hotel-mid',3310.69,4469,1.017),
('munnar','homestay',2349.53,3234,1.017),
('munnar','hostel-dorm',426.65,550,1),
('varanasi','hotel-mid',2665.82,3585,1.008),
('varanasi','homestay',1997.37,2657,1.008),
('varanasi','hostel-dorm',300.74,400,1),
('ooty','hotel-mid',3615.82,4881,1.017),
('ooty','homestay',2925.31,3908,1.017),
('ooty','hostel-dorm',515.08,664,1),
('hampi','hotel-mid',3212.10,4328,1.017),
('hampi','homestay',1768.92,2396,1.017),
('hampi','hostel-dorm',569.26,742,1),
('pushkar','hotel-mid',1977.85,2938,1.065),
('pushkar','homestay',943.35,1427,1.065),
('pushkar','hostel-dorm',214.14,319,1),
('shimla','hotel-mid',2067.94,2888,1.036),
('shimla','homestay',1565.03,2171,1.036),
('shimla','hostel-dorm',365.43,499,1),
('amritsar','hotel-mid',2092.46,2820,1.000),
('amritsar','homestay',1166.95,1580,1.000),
('amritsar','hostel-dorm',292.30,381,1),
('ajmer','hotel-mid',1737.60,2350,1.065),
('ajmer','homestay',972.93,1321,1.065),
('mandu','hotel-mid',2624.83,3594,1.017),
('mandu','homestay',1498.43,1988,1.017),
('khajuraho','hotel-mid',2628.85,3599,1.017),
('khajuraho','homestay',842.61,1118,1.017),
('khajuraho','hostel-dorm',281.19,357,1),
('gokarna','hotel-mid',2434.82,3281,1.017),
('gokarna','homestay',1608.70,2179,1.017),
('gokarna','hostel-dorm',392.04,511,1),
('kasol','hotel-mid',4237.40,4237,1.018),
('kasol','homestay',1324.81,1325,1.018),
('kasol','hostel-dorm',575.00,575,1),
('chopta','hotel-mid',4898.47,4898,1.075),
('chopta','homestay',1537.29,1537,1.075),
('kalpa','hotel-mid',3883.09,3883,1.018),
('kalpa','homestay',1966.30,1966,1.018),
('kalpa','hostel-dorm',757.00,757,1),
('chitkul','hotel-mid',3370.33,3370,1.018),
('chitkul','homestay',1526.17,1526,1.018),
('chitkul','hostel-dorm',604.00,604,1),
('puri','hotel-mid',1577.03,2157,1.017),
('puri','homestay',711.67,967,1.017),
('puri','hostel-dorm',417.21,542,1),
('bodh-gaya','hotel-mid',2492.00,3408,1.017),
('bodh-gaya','homestay',880.26,1196,1.017),
('bodh-gaya','hostel-dorm',393.34,511,1),
('kaziranga','hotel-mid',2361.12,3175,1.017),
('kaziranga','homestay',1456.60,1937,1.017),
('calangute-baga','hotel-mid',1924.87,3575,1.259),
('calangute-baga','homestay',1506.58,2802,1.259),
('calangute-baga','hostel-dorm',473.81,918,1),
('palolem','hotel-mid',1983.24,3602,1.259),
('palolem','homestay',1382.76,2474,1.259),
('palolem','hostel-dorm',338.67,635,1),
('tawang','hotel-mid',2492.90,3407,1.017),
('tawang','homestay',2644.49,3556,1.017),
('tawang','hostel-dorm',741.73,945,1),
('pahalgam','hotel-mid',2907.67,2908,1.017),
('pahalgam','homestay',2578.35,2578,1.017),
('pahalgam','hostel-dorm',1172.00,1172,1),
('srinagar','hotel-mid',3612.56,3613,1.017),
('srinagar','homestay',1734.69,1735,1.017),
('srinagar','hostel-dorm',986.00,986,1)
),
base AS (
  SELECT c.id, c.destination_id d, c.category cat, c.season, c.source_ref,
    b.typical_inr t, b.range_low_inr lo, b.range_high_inr hi,
    max(b.typical_inr) FILTER (WHERE b.season = 'shoulder') OVER w AS sh,
    bool_or(c.season = 'peak' AND 11 = ANY(c.months)) OVER w AS nov_peak,
    (dest.state_id = 'goa') goa
  FROM destination_costs c
  JOIN backups.destination_costs_20261009 b ON b.id = c.id
  JOIN destinations dest ON dest.id = c.destination_id
  WHERE c.category IN ('hotel-mid','hotel-splurge','homestay','hostel-dorm')
    AND c.source_ref IN ('observed_listings_2026_10','calibrated_model_2026_10')
  WINDOW w AS (PARTITION BY c.destination_id, c.category)
),
j AS (
  SELECT base.*, o.shoulder obs_sh, o.obs_v, o.diwali_ratio,
    CASE base.season WHEN 'shoulder' THEN 1
      WHEN 'peak' THEN CASE WHEN goa THEN t::numeric / NULLIF(sh, 0) ELSE t::numeric / NULLIF(sh, 0) * (1.35 / 1.45) END
      ELSE t::numeric / NULLIF(sh, 0) END shape,
    CASE base.cat WHEN 'hotel-mid' THEN 0.722 WHEN 'hotel-splurge' THEN 0.722 WHEN 'homestay' THEN 0.731 ELSE 0.634 END f,
    CASE WHEN base.cat = 'hostel-dorm' THEN 10 ELSE 50 END q
  FROM base LEFT JOIN obs o ON o.d = base.d AND o.cat = base.cat
  WHERE sh IS NOT NULL
),
n AS (
  SELECT j.*,
    CASE WHEN source_ref = 'observed_listings_2026_10' THEN obs_sh * shape
         WHEN nov_peak THEN sh * f * shape END nt
  FROM j
  WHERE (source_ref = 'observed_listings_2026_10' AND obs_sh IS NOT NULL) OR (source_ref = 'calibrated_model_2026_10' AND nov_peak)
),
n2 AS (SELECT n.*, GREATEST(round(nt / q) * q, q)::int new_t, nt / NULLIF(t, 0) ratio FROM n WHERE nt IS NOT NULL)
UPDATE destination_costs c SET
  typical_inr = n2.new_t,
  range_low_inr = GREATEST(round(n2.lo * n2.ratio / n2.q) * n2.q, n2.q)::int,
  range_high_inr = GREATEST(round(n2.hi * n2.ratio / n2.q) * n2.q, n2.new_t)::int,
  notes = CASE WHEN n2.source_ref = 'observed_listings_2026_10'
    THEN 'Median of listed prices for a 12-13 Nov 2026 stay (Cleartrip/Kayak/Booking/Hostelworld, fetched 2026-10-08) x1.12 GST est. (dorm: as listed), divided by ' || n2.diwali_ratio || ' for Diwali holiday week (measured same-hotel premium). Anchored to the season that contains November here; other seasons by the model shape (2026-10-09).'
    ELSE 'Modelled, not observed. Base rates scaled to observed listing prices season for season, Diwali-week prices deflated (2026-10-09: November is peak here, factor ' || n2.f || '); peak = shoulder x1.35. Place-by-place research pending.' END,
  recorded_at = now()
FROM n2 WHERE c.id = n2.id;

COMMIT;
