-- APPLIED 2026-10-10 via scripts/run-sql-file.mjs. Not in schema_migrations.
-- 098: budget-room sentences rewritten to the measured budget tier (097, 2026-10-10). These quoted a generic room
-- range below the measured budget-room median for that place and season; the range becomes 'around <median>'.
-- 52 other held sentences already contained the measured figure and are unchanged. 7 sentences in 7 rows. Old values: backups.prose_cost_20261010.
BEGIN;
CREATE TABLE IF NOT EXISTS backups.prose_cost_20261010 (tbl text, col text, key text, old_value text, saved_at timestamptz default now());
INSERT INTO backups.prose_cost_20261010 (tbl, col, key, old_value) VALUES
('destination_months', 'prose_payoff', 'chakrata/6', $cst$This is the month for people who genuinely love rain — not the Instagram version, the actual experience of being soaked through by 11am. The forests turn impossibly green, every rock grows a moss beard, and waterfalls multiply across every hillside. Tiger Falls becomes a thundering wall of white water. Birdwatching peaks as breeding season brings out territorial displays and calls. Rooms drop to ₹600-1,000/night because most tourists avoid monsoon hills. If you bring waterproof boots, leech socks, and a sense of humour, June rewards you with a Chakrata that postcard photographers never capture.$cst$),
('destination_months', 'prose_payoff', 'chamba/11', $cst$This is architectural month. Without crowds, without heat, without rain, the Lakshmi Narayan, Chamunda Devi, and Hari Rai temple complexes reveal their details. The stone carving quality at these 10th-century sites genuinely rivals Khajuraho, though nobody says this because Chamba lacks a PR department. The Bhuri Singh Museum feels personal — the attendant might walk you through the Pahari paintings collection one-on-one. Evening walks to the Chaugan with a shawl and chai in hand are as close to timeless India as tourism gets. Rooms: ₹600-1,200/night.$cst$),
('destination_months', 'prose_payoff', 'chakrata/8', $cst$The forests are at their most alive — orchids bloom on tree trunks, butterflies appear in clouds along sunny trail sections, and the air carries the deep petrichor scent that synthetic candles try to imitate. Tiger Falls is still formidable. The Deoban trail is muddy but passable for experienced hikers. This is when you start seeing early autumn mushrooms — locals forage chanterelles and morels along the forest floor. Homestay hosts cook with whatever the forest provides. Rates stay low (₹600-1,000/night) and the experience stays raw. August is the quiet before Chakrata remembers it has a tourist season.$cst$),
('destination_months', 'prose_payoff', 'chamba/9', $cst$This is an underrated window. The temples have been washed clean by three months of rain and the afternoon light on the Lakshmi Narayan complex is gallery-quality. Khajjiar meadow is at peak green without peak crowds. The Bharmaur road is clear and the drive through September-green valleys justifies the trip alone. Kalatop forest walks are leech-free again, and the Himalayan bird migration has begun — warblers, flycatchers, and raptors move through the Ravi valley in numbers. Rooms: ₹800-1,500/night. September is when Chamba trusts you with its best angle.$cst$),
('destination_months', 'prose_payoff', 'yamunotri/10', $cst$October Yamunotri is farewell and ceremony. The temple closing — the deity carried in procession from the temple to Kharsali, with priests chanting, devotees following, and the mountain watching — is one of Hinduism's most poignant rituals. The admission that winter is beyond human control, the trust that the deity will return in spring, the village accepting six months of dormancy. The closing ceremony draws devoted pilgrims who understand this is the end, not the beginning, and find meaning in it. The autumn colours along the gorge are beautiful. The hot springs in October cold (0-10°C) steam dramatically. The last trek of the season has a bittersweet quality. Hotels at ₹600-1,500. If you want to understand Yamunotri beyond the Char Dham checklist, come for the closing.$cst$),
('destination_months', 'prose_payoff', 'yamunotri/9', $cst$Late September Yamunotri is the reward for patience. The monsoon retreats, the trail dries, and the gorge in autumn light is beautiful — the Yamuna settling to clear flow, the rock faces catching warm light, the surrounding forest holding monsoon green while the sky clears blue. The hot springs in cool, clear air produce their most photogenic steam columns. The temple in September has its last active-season energy. The trek (6km) in September conditions is at its most pleasant: cool air, dry trail, fewer pilgrims. The Saptrishi Kund trek to the Yamuna's actual source is most viable in late September — weather stable, trail dry. Hotels at ₹600-1,500 with easy availability. September Yamunotri: the connoisseur's Char Dham.$cst$),
('destination_months', 'prose_payoff', 'devprayag/11', $cst$November sangam is when photographers make the trip. The Bhagirathi runs emerald, the Alaknanda runs jade, and the boundary between them — visible from the suspension bridge, from the ghats, from the Raghunath temple terrace — is clean enough to photograph without filters. The water is achingly cold for ritual dips, but the handful of devotees who come dip regardless. The town's dharamshala chai, served in glass tumblers at the ghat edge, warms you while the river view does everything else. The drive from Rishikesh is fog-free and stunning in autumn light. Rooms: ₹400-1,000/night.$cst$);
UPDATE destination_months SET prose_payoff = $cst$This is the month for people who genuinely love rain — not the Instagram version, the actual experience of being soaked through by 11am. The forests turn impossibly green, every rock grows a moss beard, and waterfalls multiply across every hillside. Tiger Falls becomes a thundering wall of white water. Birdwatching peaks as breeding season brings out territorial displays and calls. Rooms drop to around ₹1,300/night because most tourists avoid monsoon hills. If you bring waterproof boots, leech socks, and a sense of humour, June rewards you with a Chakrata that postcard photographers never capture.$cst$::text WHERE destination_id||'/'||month = 'chakrata/6';
UPDATE destination_months SET prose_payoff = $cst$This is architectural month. Without crowds, without heat, without rain, the Lakshmi Narayan, Chamunda Devi, and Hari Rai temple complexes reveal their details. The stone carving quality at these 10th-century sites genuinely rivals Khajuraho, though nobody says this because Chamba lacks a PR department. The Bhuri Singh Museum feels personal — the attendant might walk you through the Pahari paintings collection one-on-one. Evening walks to the Chaugan with a shawl and chai in hand are as close to timeless India as tourism gets. Rooms: around ₹1,550/night.$cst$::text WHERE destination_id||'/'||month = 'chamba/11';
UPDATE destination_months SET prose_payoff = $cst$The forests are at their most alive — orchids bloom on tree trunks, butterflies appear in clouds along sunny trail sections, and the air carries the deep petrichor scent that synthetic candles try to imitate. Tiger Falls is still formidable. The Deoban trail is muddy but passable for experienced hikers. This is when you start seeing early autumn mushrooms — locals forage chanterelles and morels along the forest floor. Homestay hosts cook with whatever the forest provides. Rates stay low (around ₹1,300/night) and the experience stays raw. August is the quiet before Chakrata remembers it has a tourist season.$cst$::text WHERE destination_id||'/'||month = 'chakrata/8';
UPDATE destination_months SET prose_payoff = $cst$This is an underrated window. The temples have been washed clean by three months of rain and the afternoon light on the Lakshmi Narayan complex is gallery-quality. Khajjiar meadow is at peak green without peak crowds. The Bharmaur road is clear and the drive through September-green valleys justifies the trip alone. Kalatop forest walks are leech-free again, and the Himalayan bird migration has begun — warblers, flycatchers, and raptors move through the Ravi valley in numbers. Rooms: around ₹2,100/night. September is when Chamba trusts you with its best angle.$cst$::text WHERE destination_id||'/'||month = 'chamba/9';
UPDATE destination_months SET prose_payoff = $cst$October Yamunotri is farewell and ceremony. The temple closing — the deity carried in procession from the temple to Kharsali, with priests chanting, devotees following, and the mountain watching — is one of Hinduism's most poignant rituals. The admission that winter is beyond human control, the trust that the deity will return in spring, the village accepting six months of dormancy. The closing ceremony draws devoted pilgrims who understand this is the end, not the beginning, and find meaning in it. The autumn colours along the gorge are beautiful. The hot springs in October cold (0-10°C) steam dramatically. The last trek of the season has a bittersweet quality. Hotels at around ₹2,250. If you want to understand Yamunotri beyond the Char Dham checklist, come for the closing.$cst$::text WHERE destination_id||'/'||month = 'yamunotri/10';
UPDATE destination_months SET prose_payoff = $cst$Late September Yamunotri is the reward for patience. The monsoon retreats, the trail dries, and the gorge in autumn light is beautiful — the Yamuna settling to clear flow, the rock faces catching warm light, the surrounding forest holding monsoon green while the sky clears blue. The hot springs in cool, clear air produce their most photogenic steam columns. The temple in September has its last active-season energy. The trek (6km) in September conditions is at its most pleasant: cool air, dry trail, fewer pilgrims. The Saptrishi Kund trek to the Yamuna's actual source is most viable in late September — weather stable, trail dry. Hotels at around ₹2,250 with easy availability. September Yamunotri: the connoisseur's Char Dham.$cst$::text WHERE destination_id||'/'||month = 'yamunotri/9';
UPDATE destination_months SET prose_payoff = $cst$November sangam is when photographers make the trip. The Bhagirathi runs emerald, the Alaknanda runs jade, and the boundary between them — visible from the suspension bridge, from the ghats, from the Raghunath temple terrace — is clean enough to photograph without filters. The water is achingly cold for ritual dips, but the handful of devotees who come dip regardless. The town's dharamshala chai, served in glass tumblers at the ghat edge, warms you while the river view does everything else. The drive from Rishikesh is fog-free and stunning in autumn light. Rooms: around ₹1,400/night.$cst$::text WHERE destination_id||'/'||month = 'devprayag/11';
COMMIT;
