-- APPLIED 2026-10-10 via scripts/run-sql-file.mjs. Not in schema_migrations. Supersedes 097 (adds the queue budget-room pass).
-- 101: hotel-budget rows from measured budget rooms (generated by scripts/build-budget-tier-sql.mjs, 2026-10-10).
-- See the script header for the method. Re-runnable: deletes existing hotel-budget rows first.
-- Stats: {"loaded":116,"skipped":{"budget and 3-star priced on different nights":69,"budget n<2 or no URL":76,"no measured 3-star to pair with":41,"budget borrowed from another town":3,"ratio outside 0.2-1":4,"3-star excluded for this place":5}}
BEGIN;
ALTER TABLE destination_costs DROP CONSTRAINT dc_category_check;
ALTER TABLE destination_costs ADD CONSTRAINT dc_category_check CHECK (category = ANY (ARRAY['homestay','hostel-dorm','hotel-budget','hotel-mid','hotel-splurge','food-per-day','transport-taxi-day','transport-intercity','permit-fees','activity-sample']));
DELETE FROM destination_costs WHERE category = 'hotel-budget';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7792/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7792/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7792/50)*50, round(typical_inr*0.7792/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (north) 2026-10-09: budget room median 1683 (n=3) / 3-star median 2160 (n=11) on the same night (12-13 nov) = 0.78; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'chakrata' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.2964/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.2964/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.2964/50)*50, round(typical_inr*0.2964/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (north) 2026-10-09: budget room median 1160 (n=3) / 3-star median 3913 (n=8) on the same night (10-11 oct) = 0.30; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kanatal' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3173/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3173/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3173/50)*50, round(typical_inr*0.3173/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (north) 2026-10-09: budget room median 1392 (n=3) / 3-star median 4387 (n=4) on the same night (12-13 nov) = 0.32; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'tehri' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5335/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5335/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5335/50)*50, round(typical_inr*0.5335/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (north) 2026-10-09: budget room median 1823 (n=4) / 3-star median 3417 (n=22) on the same night (11 oct) = 0.53; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'lansdowne' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4322/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4322/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4322/50)*50, round(typical_inr*0.4322/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (north) 2026-10-09: budget room median 1406 (n=6) / 3-star median 3253 (n=6) on the same night (13 nov) = 0.43; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kargil' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3768/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3768/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3768/50)*50, round(typical_inr*0.3768/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (north) 2026-10-09: budget room median 919 (n=4) / 3-star median 2439 (n=14) on the same night (13-14 nov) = 0.38; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'agra' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4527/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4527/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4527/50)*50, round(typical_inr*0.4527/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C3 (queue-load) 2026-10-10: budget room median 1326 (n=8) / 3-star median 2929 (n=5) on the same night (18-19 nov) = 0.45; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'chitrakoot' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4571/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4571/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4571/50)*50, round(typical_inr*0.4571/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (north) 2026-10-09: budget room median 1600 (n=3) / 3-star median 3500 (n=8) on the same night (12-13 nov) = 0.46; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'yamunotri' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4094/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4094/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4094/50)*50, round(typical_inr*0.4094/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C4 (queue-load) 2026-10-10: budget room median 1981 (n=6) / 3-star median 4320 (n=4) on the same night (18-19 nov) = 0.41; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'guptkashi' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4032/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4032/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4032/50)*50, round(typical_inr*0.4032/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (north) 2026-10-09: budget room median 1250 (n=3) / 3-star median 3100 (n=6) on the same night (11-12 oct) = 0.40; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'devprayag' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5591/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5591/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5591/50)*50, round(typical_inr*0.5591/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (north) 2026-10-09: budget room median 1574 (n=5) / 3-star median 2815 (n=12) on the same night (12-13 nov) = 0.56; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'joshimath' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4284/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4284/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4284/50)*50, round(typical_inr*0.4284/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (north) 2026-10-09: budget room median 2110 (n=4) / 3-star median 4925 (n=11) on the same night (12-13 nov) = 0.43; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'badrinath' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.2627/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.2627/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.2627/50)*50, round(typical_inr*0.2627/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (north) 2026-10-09: budget room median 1100 (n=3) / 3-star median 4188 (n=4) on the same night (undated) = 0.26; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'valley-of-flowers' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.2627/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.2627/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.2627/50)*50, round(typical_inr*0.2627/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (north) 2026-10-09: budget room median 1100 (n=3) / 3-star median 4188 (n=4) on the same night (undated) = 0.26; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'hemkund-sahib' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.8871/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.8871/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.8871/50)*50, round(typical_inr*0.8871/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (north) 2026-10-09: budget room median 1745 (n=8) / 3-star median 1967 (n=16) on the same night (12-13 nov) = 0.89; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'mukteshwar' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4787/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4787/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4787/50)*50, round(typical_inr*0.4787/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (north) 2026-10-09: budget room median 999 (n=3) / 3-star median 2087 (n=4) on the same night (11-12 oct) = 0.48; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'champawat' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6965/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6965/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6965/50)*50, round(typical_inr*0.6965/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B6 (north) 2026-10-09: budget room median 1393 (n=10) / 3-star median 2000 (n=8) on the same night (undated) = 0.70; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'parvati-valley' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5708/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5708/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5708/50)*50, round(typical_inr*0.5708/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B7 (north) 2026-10-09: budget room median 1476 (n=5) / 3-star median 2586 (n=6) on the same night (13-14 nov) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'bir-billing' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7499/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7499/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7499/50)*50, round(typical_inr*0.7499/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B7 (north) 2026-10-09: budget room median 1406 (n=3) / 3-star median 1875 (n=5) on the same night (13-14 nov) = 0.75; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'chamba' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4692/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4692/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4692/50)*50, round(typical_inr*0.4692/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B8 (north) 2026-10-09: budget room median 1770 (n=6) / 3-star median 3368 (n=4) on the same night (13-14 nov) = 0.47; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'sangla' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6518/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6518/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6518/50)*50, round(typical_inr*0.6518/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (west) 2026-10-09: budget room median 2003 (n=3) / 3-star median 3073 (n=7) on the same night (13 nov) = 0.65; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'tarkarli' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3853/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3853/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3853/50)*50, round(typical_inr*0.3853/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (west) 2026-10-09: budget room median 1576 (n=4) / 3-star median 4090 (n=5) on the same night (13 nov) = 0.39; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'panaji' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3957/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3957/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3957/50)*50, round(typical_inr*0.3957/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (west) 2026-10-09: budget room median 1547 (n=9) / 3-star median 3910 (n=6) on the same night (11 oct) = 0.40; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'margao' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6220/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6220/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6220/50)*50, round(typical_inr*0.6220/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (west) 2026-10-09: budget room median 1632 (n=11) / 3-star median 2624 (n=6) on the same night (10-11 oct) = 0.62; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'colva-benaulim' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3828/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3828/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3828/50)*50, round(typical_inr*0.3828/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (west) 2026-10-09: budget room median 2023 (n=6) / 3-star median 5285 (n=5) on the same night (10-11 oct) = 0.38; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'agonda' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6859/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6859/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6859/50)*50, round(typical_inr*0.6859/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (west) 2026-10-09: budget room median 2310 (n=3) / 3-star median 3368 (n=5) on the same night (10-11 oct) = 0.69; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'anjuna' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4868/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4868/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4868/50)*50, round(typical_inr*0.4868/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (west) 2026-10-09: budget room median 1841 (n=3) / 3-star median 3782 (n=5) on the same night (10-11 oct) = 0.49; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'vagator' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3889/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3889/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3889/50)*50, round(typical_inr*0.3889/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (west) 2026-10-09: budget room median 2030 (n=3) / 3-star median 5220 (n=7) on the same night (10-11 oct) = 0.39; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'assagao' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3989/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3989/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3989/50)*50, round(typical_inr*0.3989/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (west) 2026-10-09: budget room median 1739 (n=5) / 3-star median 4359 (n=4) on the same night (10-11 oct) = 0.40; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'morjim' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3798/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3798/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3798/50)*50, round(typical_inr*0.3798/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (west) 2026-10-09: budget room median 1354 (n=6) / 3-star median 3565 (n=4) on the same night (10-11 oct) = 0.38; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'mandrem' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3270/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3270/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3270/50)*50, round(typical_inr*0.3270/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (west) 2026-10-09: budget room median 1208 (n=6) / 3-star median 3694 (n=5) on the same night (10-11 oct) = 0.33; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'arambol' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3823/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3823/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3823/50)*50, round(typical_inr*0.3823/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (west) 2026-10-09: budget room median 1502 (n=3) / 3-star median 3929 (n=14) on the same night (13 nov) = 0.38; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kumbhalgarh' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5892/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5892/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5892/50)*50, round(typical_inr*0.5892/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (west) 2026-10-09: budget room median 1595 (n=4) / 3-star median 2707 (n=4) on the same night (10-11 oct) = 0.59; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'ambaji' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4330/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4330/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4330/50)*50, round(typical_inr*0.4330/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B6 (west) 2026-10-09: budget room median 1800 (n=3) / 3-star median 4157 (n=9) on the same night (10-11 oct) = 0.43; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'statue-of-unity' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6139/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6139/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6139/50)*50, round(typical_inr*0.6139/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B6 (west) 2026-10-09: budget room median 2789 (n=2) / 3-star median 4543 (n=11) on the same night (11 oct) = 0.61; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'saputara' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3290/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3290/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3290/50)*50, round(typical_inr*0.3290/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B8 (west) 2026-10-09: budget room median 1589 (n=6) / 3-star median 4830 (n=10) on the same night (13 nov) = 0.33; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'khandala' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.8362/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.8362/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.8362/50)*50, round(typical_inr*0.8362/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B8 (west) 2026-10-09: budget room median 1409 (n=2) / 3-star median 1685 (n=3) on the same night (13 nov) = 0.84; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'ranjangaon' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7956/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7956/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7956/50)*50, round(typical_inr*0.7956/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (east) 2026-10-09: budget room median 1872 (n=5) / 3-star median 2353 (n=6) on the same night (18-19 nov) = 0.80; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kolkata' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5981/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5981/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5981/50)*50, round(typical_inr*0.5981/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (east) 2026-10-09: budget room median 1527 (n=5) / 3-star median 2553 (n=6) on the same night (18-19 nov) = 0.60; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'shantiniketan' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6244/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6244/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6244/50)*50, round(typical_inr*0.6244/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (east) 2026-10-09: budget room median 1659 (n=3) / 3-star median 2657 (n=6) on the same night (18-19 nov) = 0.62; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'siliguri' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7933/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7933/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7933/50)*50, round(typical_inr*0.7933/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (east) 2026-10-09: budget room median 1965 (n=3) / 3-star median 2477 (n=6) on the same night (18-19 nov) = 0.79; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kalimpong' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7166/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7166/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7166/50)*50, round(typical_inr*0.7166/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (east) 2026-10-09: budget room median 2420 (n=5) / 3-star median 3377 (n=6) on the same night (18-19 nov) = 0.72; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'gangtok' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5500/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5500/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5500/50)*50, round(typical_inr*0.5500/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (east) 2026-10-09: budget room median 1650 (n=4) / 3-star median 3000 (n=3) on the same night (10-11 oct) = 0.55; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'anini' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5423/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5423/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5423/50)*50, round(typical_inr*0.5423/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (east) 2026-10-09: budget room median 1083 (n=5) / 3-star median 1997 (n=7) on the same night (18-19 nov) = 0.54; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'imphal' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7644/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7644/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7644/50)*50, round(typical_inr*0.7644/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (east) 2026-10-09: budget room median 1522 (n=5) / 3-star median 1991 (n=7) on the same night (18-19 nov) = 0.76; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'aizawl' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7652/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7652/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7652/50)*50, round(typical_inr*0.7652/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (east) 2026-10-09: budget room median 2014 (n=4) / 3-star median 2632 (n=6) on the same night (18-19 nov) = 0.77; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'agartala' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4879/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4879/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4879/50)*50, round(typical_inr*0.4879/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (east) 2026-10-09: budget room median 2440 (n=4) / 3-star median 5001 (n=5) on the same night (18-19 nov) = 0.49; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'diu' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4787/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4787/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4787/50)*50, round(typical_inr*0.4787/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (east) 2026-10-09: budget room median 1960 (n=3) / 3-star median 4094 (n=5) on the same night (18-19 nov) = 0.48; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'daman' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5011/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5011/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5011/50)*50, round(typical_inr*0.5011/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (east) 2026-10-09: budget room median 1382 (n=4) / 3-star median 2758 (n=6) on the same night (18 nov) = 0.50; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'patna' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6868/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6868/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6868/50)*50, round(typical_inr*0.6868/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (east) 2026-10-09: budget room median 1605 (n=5) / 3-star median 2337 (n=6) on the same night (18 nov) = 0.69; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'deoghar' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4580/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4580/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4580/50)*50, round(typical_inr*0.4580/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (east) 2026-10-09: budget room median 1292 (n=4) / 3-star median 2821 (n=6) on the same night (18-19 nov) = 0.46; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'ranchi' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7111/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7111/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7111/50)*50, round(typical_inr*0.7111/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (east) 2026-10-09: budget room median 1600 (n=2) / 3-star median 2250 (n=4) on the same night (undated) = 0.71; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'betla' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5006/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5006/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5006/50)*50, round(typical_inr*0.5006/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (east) 2026-10-09: budget room median 1328 (n=5) / 3-star median 2653 (n=6) on the same night (18-19 nov) = 0.50; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'bhubaneswar' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5212/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5212/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5212/50)*50, round(typical_inr*0.5212/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (east) 2026-10-09: budget room median 1353 (n=5) / 3-star median 2596 (n=5) on the same night (18-19 nov) = 0.52; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'cuttack' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4259/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4259/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4259/50)*50, round(typical_inr*0.4259/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (east) 2026-10-09: budget room median 1449 (n=3) / 3-star median 3402 (n=3) on the same night (18-19 nov) = 0.43; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'gopalpur-on-sea' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7069/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7069/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7069/50)*50, round(typical_inr*0.7069/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B6 (east) 2026-10-09: budget room median 1802 (n=6) / 3-star median 2549 (n=6) on the same night (18-19 nov) = 0.71; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'koraput' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5657/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5657/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5657/50)*50, round(typical_inr*0.5657/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B6 (east) 2026-10-09: budget room median 1400 (n=2) / 3-star median 2475 (n=4) on the same night (1 oct) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'taptapani' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4931/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4931/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4931/50)*50, round(typical_inr*0.4931/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B7 (east) 2026-10-09: budget room median 1398 (n=4) / 3-star median 2835 (n=6) on the same night (18-19 nov) = 0.49; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'guwahati' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7608/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7608/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7608/50)*50, round(typical_inr*0.7608/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B7 (east) 2026-10-09: budget room median 1660 (n=4) / 3-star median 2182 (n=6) on the same night (18-19 nov) = 0.76; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'jorhat' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4714/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4714/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4714/50)*50, round(typical_inr*0.4714/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B8 (east) 2026-10-09: budget room median 1491 (n=4) / 3-star median 3163 (n=6) on the same night (18-19 nov) = 0.47; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'shillong' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5620/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5620/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5620/50)*50, round(typical_inr*0.5620/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B8 (east) 2026-10-09: budget room median 2730 (n=4) / 3-star median 4858 (n=4) on the same night (18-19 nov) = 0.56; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'cherrapunji' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4073/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4073/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4073/50)*50, round(typical_inr*0.4073/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B9 (east) 2026-10-09: budget room median 1539 (n=2) / 3-star median 3374 (n=4) on the same night (18-19 nov) = 0.41; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'ziro-valley' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5383/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5383/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5383/50)*50, round(typical_inr*0.5383/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (south) 2026-10-10: budget room median 1672 (n=3) / 3-star median 3106 (n=4) on the same night (18-19 nov) = 0.54; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'araku-valley' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4405/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4405/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4405/50)*50, round(typical_inr*0.4405/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (south) 2026-10-10: budget room median 1850 (n=5) / 3-star median 4200 (n=3) on the same night (18-19 nov) = 0.44; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'horsley-hills' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6044/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6044/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6044/50)*50, round(typical_inr*0.6044/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (south) 2026-10-10: budget room median 1386 (n=5) / 3-star median 2293 (n=6) on the same night (18-19 nov) = 0.60; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'amaravati' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4957/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4957/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4957/50)*50, round(typical_inr*0.4957/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (south) 2026-10-10: budget room median 1776 (n=4) / 3-star median 3583 (n=6) on the same night (18-19 nov) = 0.50; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'chennai' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5660/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5660/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5660/50)*50, round(typical_inr*0.5660/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (south) 2026-10-10: budget room median 1458 (n=3) / 3-star median 2576 (n=6) on the same night (18-19 nov) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'coimbatore' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5884/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5884/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5884/50)*50, round(typical_inr*0.5884/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (south) 2026-10-10: budget room median 2160 (n=5) / 3-star median 3671 (n=6) on the same night (18-19 nov) = 0.59; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'trichy' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6295/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6295/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6295/50)*50, round(typical_inr*0.6295/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (south) 2026-10-10: budget room median 1650 (n=4) / 3-star median 2621 (n=5) on the same night (18-19 nov) = 0.63; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'pondicherry' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6295/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6295/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6295/50)*50, round(typical_inr*0.6295/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (south) 2026-10-10: budget room median 1650 (n=4) / 3-star median 2621 (n=5) on the same night (18-19 nov) = 0.63; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'puducherry' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6973/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6973/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6973/50)*50, round(typical_inr*0.6973/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B10 (south) 2026-10-10: budget room median 1638 (n=3) / 3-star median 2349 (n=5) on the same night (18-19 nov) = 0.70; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'courtallam' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6285/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6285/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6285/50)*50, round(typical_inr*0.6285/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B11 (south) 2026-10-10: budget room median 1247 (n=4) / 3-star median 1984 (n=6) on the same night (18-19 nov) = 0.63; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kanyakumari' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4050/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4050/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4050/50)*50, round(typical_inr*0.4050/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B11 (south) 2026-10-10: budget room median 1540 (n=5) / 3-star median 3802 (n=8) on the same night (18-19 nov) = 0.41; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kodaikanal' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4284/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4284/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4284/50)*50, round(typical_inr*0.4284/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (south) 2026-10-10: budget room median 1164 (n=4) / 3-star median 2717 (n=6) on the same night (18-19 nov) = 0.43; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'madurai' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6294/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6294/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6294/50)*50, round(typical_inr*0.6294/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (south) 2026-10-10: budget room median 1406 (n=5) / 3-star median 2234 (n=6) on the same night (18-19 nov) = 0.63; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'rameswaram' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7017/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7017/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7017/50)*50, round(typical_inr*0.7017/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B12 (south) 2026-10-10: budget room median 1851 (n=4) / 3-star median 2638 (n=6) on the same night (18-19 nov) = 0.70; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kanchipuram' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4431/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4431/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4431/50)*50, round(typical_inr*0.4431/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (south) 2026-10-10: budget room median 1064 (n=3) / 3-star median 2401 (n=6) on the same night (18-19 nov) = 0.44; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'thanjavur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3419/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3419/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3419/50)*50, round(typical_inr*0.3419/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (south) 2026-10-10: budget room median 2000 (n=3) / 3-star median 5850 (n=5) on the same night (18-19 nov) = 0.34; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'mudumalai' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3716/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3716/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3716/50)*50, round(typical_inr*0.3716/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B13 (south) 2026-10-10: budget room median 1159 (n=5) / 3-star median 3119 (n=7) on the same night (18-19 nov) = 0.37; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'palani' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5854/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5854/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5854/50)*50, round(typical_inr*0.5854/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (south) 2026-10-10: budget room median 1320 (n=4) / 3-star median 2255 (n=7) on the same night (18-19 nov) = 0.59; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'tirupati' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4275/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4275/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4275/50)*50, round(typical_inr*0.4275/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (south) 2026-10-10: budget room median 1199 (n=3) / 3-star median 2805 (n=5) on the same night (18-19 nov) = 0.43; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'rajahmundry' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5359/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5359/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5359/50)*50, round(typical_inr*0.5359/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (south) 2026-10-10: budget room median 1500 (n=3) / 3-star median 2799 (n=5) on the same night (18-19 nov) = 0.54; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'maredumilli' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4377/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4377/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4377/50)*50, round(typical_inr*0.4377/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (south) 2026-10-10: budget room median 1562 (n=3) / 3-star median 3569 (n=3) on the same night (18-19 nov) = 0.44; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'pulicat-lake' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5748/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5748/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5748/50)*50, round(typical_inr*0.5748/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (south) 2026-10-10: budget room median 1129 (n=4) / 3-star median 1964 (n=15) on the same night (18-19 nov) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'visakhapatnam' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5622/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5622/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5622/50)*50, round(typical_inr*0.5622/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (south) 2026-10-10: budget room median 1040 (n=2) / 3-star median 1850 (n=20) on the same night (18-19 nov) = 0.56; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'bengaluru' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3556/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3556/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3556/50)*50, round(typical_inr*0.3556/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (south) 2026-10-10: budget room median 1680 (n=3) / 3-star median 4725 (n=4) on the same night (18-19 nov) = 0.36; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'dharmasthala' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6987/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6987/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6987/50)*50, round(typical_inr*0.6987/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (south) 2026-10-10: budget room median 1445 (n=3) / 3-star median 2068 (n=9) on the same night (18-19 nov) = 0.70; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'mangalore' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4932/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4932/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4932/50)*50, round(typical_inr*0.4932/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (south) 2026-10-10: budget room median 1422 (n=6) / 3-star median 2883 (n=9) on the same night (18-19 nov) = 0.49; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'mysore' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3533/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3533/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3533/50)*50, round(typical_inr*0.3533/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (south) 2026-10-10: budget room median 1172 (n=4) / 3-star median 3317 (n=4) on the same night (18-19 nov) = 0.35; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'bidar' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7248/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7248/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7248/50)*50, round(typical_inr*0.7248/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (south) 2026-10-10: budget room median 1620 (n=3) / 3-star median 2235 (n=5) on the same night (18-19 nov) = 0.72; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'bijapur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6528/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6528/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6528/50)*50, round(typical_inr*0.6528/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (south) 2026-10-10: budget room median 1431 (n=4) / 3-star median 2192 (n=6) on the same night (18-19 nov) = 0.65; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'gulbarga' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7754/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7754/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7754/50)*50, round(typical_inr*0.7754/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B5 (south) 2026-10-10: budget room median 877 (n=3) / 3-star median 1131 (n=3) on the same night (18-19 nov) = 0.78; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'belur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5768/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5768/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5768/50)*50, round(typical_inr*0.5768/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B7 (south) 2026-10-10: budget room median 1757 (n=4) / 3-star median 3046 (n=9) on the same night (18-19 nov) = 0.58; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'varkala' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6637/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6637/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6637/50)*50, round(typical_inr*0.6637/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B7 (south) 2026-10-10: budget room median 1585 (n=4) / 3-star median 2388 (n=6) on the same night (18-19 nov) = 0.66; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'guruvayur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5740/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5740/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5740/50)*50, round(typical_inr*0.5740/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B9 (south) 2026-10-10: budget room median 1520 (n=2) / 3-star median 2648 (n=6) on the same night (18-19 nov) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kannur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5144/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5144/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5144/50)*50, round(typical_inr*0.5144/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (central-islands) 2026-10-10: budget room median 2183 (n=4) / 3-star median 4244 (n=6) on the same night (18-19 nov) = 0.51; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'havelock-island' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5710/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5710/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5710/50)*50, round(typical_inr*0.5710/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B1 (central-islands) 2026-10-10: budget room median 2687 (n=4) / 3-star median 4706 (n=6) on the same night (18-19 nov) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'neil-island' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6756/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6756/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6756/50)*50, round(typical_inr*0.6756/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (central-islands) 2026-10-10: budget room median 1739 (n=3) / 3-star median 2574 (n=7) on the same night (18-19 nov) = 0.68; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'port-blair' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5203/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5203/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5203/50)*50, round(typical_inr*0.5203/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B2 (central-islands) 2026-10-10: budget room median 1231 (n=2) / 3-star median 2366 (n=5) on the same night (18-19 nov) = 0.52; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'jagdalpur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4339/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4339/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4339/50)*50, round(typical_inr*0.4339/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (central-islands) 2026-10-10: budget room median 4100 (n=2) / 3-star median 9450 (n=4) on the same night (18-19 nov) = 0.43; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'kavaratti' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.3498/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.3498/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.3498/50)*50, round(typical_inr*0.3498/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (central-islands) 2026-10-10: budget room median 865 (n=3) / 3-star median 2473 (n=6) on the same night (18-19 nov) = 0.35; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'orchha' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6525/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6525/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6525/50)*50, round(typical_inr*0.6525/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B3 (central-islands) 2026-10-10: budget room median 1209 (n=2) / 3-star median 1853 (n=10) on the same night (18-19 nov) = 0.65; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'bhopal' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6559/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6559/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6559/50)*50, round(typical_inr*0.6559/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (central-islands) 2026-10-10: budget room median 1586 (n=3) / 3-star median 2418 (n=6) on the same night (18-19 nov) = 0.66; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'ujjain' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5979/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5979/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5979/50)*50, round(typical_inr*0.5979/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (central-islands) 2026-10-10: budget room median 1322 (n=2) / 3-star median 2211 (n=7) on the same night (18-19 nov) = 0.60; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'jabalpur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5882/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5882/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5882/50)*50, round(typical_inr*0.5882/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (central-islands) 2026-10-10: budget room median 2095 (n=4) / 3-star median 3562 (n=5) on the same night (18-19 nov) = 0.59; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'pachmarhi' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5678/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5678/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5678/50)*50, round(typical_inr*0.5678/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research B4 (central-islands) 2026-10-10: budget room median 1725 (n=3) / 3-star median 3038 (n=4) on the same night (18-19 nov) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'omkareshwar' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5673/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5673/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5673/50)*50, round(typical_inr*0.5673/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C1 (queue-load) 2026-10-10: budget room median 1434 (n=4) / 3-star median 2257 (n=10) on the same night (18-19 nov) = 0.57; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'dalhousie' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5897/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5897/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5897/50)*50, round(typical_inr*0.5897/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C1 (queue-load) 2026-10-10: budget room median 2591 (n=2) / 3-star median 3923 (n=5) on the same night (18-19 nov) = 0.59; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'sissu' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7963/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7963/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7963/50)*50, round(typical_inr*0.7963/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C1 (queue-load) 2026-10-10: budget room median 2174 (n=3) / 3-star median 2730 (n=4) on the same night (18-19 nov) = 0.80; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'tirthan-valley' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.8409/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.8409/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.8409/50)*50, round(typical_inr*0.8409/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C2 (queue-load) 2026-10-10: budget room median 1903 (n=3) / 3-star median 2263 (n=10) on the same night (18-19 nov) = 0.84; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'chikmagalur' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.7200/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.7200/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.7200/50)*50, round(typical_inr*0.7200/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C2 (queue-load) 2026-10-10: budget room median 1890 (n=5) / 3-star median 2625 (n=3) on the same night (18-19 nov) = 0.72; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'idukki' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6581/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6581/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6581/50)*50, round(typical_inr*0.6581/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C3 (queue-load) 2026-10-10: budget room median 1888 (n=5) / 3-star median 2869 (n=7) on the same night (18-19 nov) = 0.66; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'chittorgarh' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.4970/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.4970/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.4970/50)*50, round(typical_inr*0.4970/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C3 (queue-load) 2026-10-10: budget room median 1575 (n=12) / 3-star median 3169 (n=4) on the same night (18-19 nov) = 0.50; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'sarnath' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.6762/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.6762/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.6762/50)*50, round(typical_inr*0.6762/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C4 (queue-load) 2026-10-10: budget room median 2310 (n=3) / 3-star median 3050 (n=4) on the same night (18-19 nov) = 0.68; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'munsiyari' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.5588/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.5588/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.5588/50)*50, round(typical_inr*0.5588/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C4 (queue-load) 2026-10-10: budget room median 1890 (n=5) / 3-star median 3382 (n=3) on the same night (18-19 nov) = 0.56; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'rudraprayag' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
INSERT INTO destination_costs (destination_id, category, season, months, typical_inr, range_low_inr, range_high_inr, unit, source_ref, notes)
  SELECT destination_id, 'hotel-budget', season, months, GREATEST(round(typical_inr*0.2640/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_low_inr, typical_inr)*0.2640/50)*50, 50)::int,
    GREATEST(round(COALESCE(range_high_inr, typical_inr)*0.2640/50)*50, round(typical_inr*0.2640/50)*50, 50)::int,
    'per_night', 'observed_research_2026_10', 'Research C4 (queue-load) 2026-10-10: budget room median 1407 (n=4) / 3-star median 4758 (n=7) on the same night (18-19 nov) = 0.26; applied to this place''s observed 3-star row in each season (097).'
  FROM destination_costs WHERE destination_id = 'uttarkashi' AND category = 'hotel-mid' AND source_ref LIKE 'observed%';
COMMIT;
