-- APPLIED 2026-10-10 via scripts/run-sql-file.mjs. Not in schema_migrations.
-- 111: sentences whose places were measured in the M1-M3 pass (109), reviewed against the updated ledger, 2026-10-10.
-- Generated from fresh-context sentence reviews (Sonnet): each sentence that stated a destination-wide price
-- (room per night, homestay, dorm, food per day, day cab, day totals, season ratios) and disagreed with
-- destination_costs for the right season had only its numbers changed. Named properties, tickets, fares and
-- dishes were left alone. 2 sentences in 2 rows. Old values: backups.prose_cost_20261010.
BEGIN;
CREATE TABLE IF NOT EXISTS backups.prose_cost_20261010 (tbl text, col text, key text, old_value text, saved_at timestamptz default now());
INSERT INTO backups.prose_cost_20261010 (tbl, col, key, old_value) VALUES
('destination_months', 'prose_lead', 'trichy/10', $cst$October in Trichy is the proper return to peak. The northeast monsoon — inland Tamil Nadu's actual rain season — arrives around October 15, dropping 150-200mm across 8-10 wet days through the back half, mostly as late-afternoon and evening showers. Daytime 28-31C, nights 23-24C, humidity 76 percent. The Cauvery and Kollidam at high-channel flow — Srirangam's temple-island geography at year-best visual context. The Rockfort 437-step climb workable through full afternoon for the first time since November; the summit Ucchi Pillayar Ganesha shrine and the Thayumanavar midway-temple at peak visitor density. The temple-circuit (Srirangam Ranganathaswamy world's-largest functioning temple, Jambukeswarar water-element Pancha Bhoota Stalam) at full ritual tempo. Navarathri tail and Dussehra (Vijayadasami, the tenth day, falls in early-to-mid October 2026) bring weapon-worship rituals and Devi processions. Trichy-Tanjore-Kumbakonam Cauvery-circuit day-trips return to year-best comfort. Stay central — Sangam Hotel ₹3-4,500, Femina ₹2,500-4k, Breeze Residency ₹2,200-3,500, homestays ₹900-1,500. Tiruchirapalli International Airport at peak Diwali-NRI inbound traffic.$cst$),
('destination_months', 'prose_lead', 'kashid/12', $cst$December is Kashid at annual peak. Temperatures hold 18-30°C — coolest of the year — with humidity in the 50s, the Arabian Sea glass-calm, and the 3km white-sand strip at year-best cleanliness and firmness. Water-sports run full 7am-6pm hours, Phansad WLS jeep safaris operational, Korlai Fort accessible. Christmas weekend (Dec 24-25) and NYE (Dec 31-Jan 1) drive Mumbai-Pune road-tripper traffic to year-peak. Heritage stays at year-high rates — Kashid Beach Resort ₹4500-8500/night, Hotel Sea Shell ₹3500-6000/night, private homestays ₹2800-5500/night.$cst$);
UPDATE destination_months SET prose_lead = $cst$October in Trichy is the proper return to peak. The northeast monsoon — inland Tamil Nadu's actual rain season — arrives around October 15, dropping 150-200mm across 8-10 wet days through the back half, mostly as late-afternoon and evening showers. Daytime 28-31C, nights 23-24C, humidity 76 percent. The Cauvery and Kollidam at high-channel flow — Srirangam's temple-island geography at year-best visual context. The Rockfort 437-step climb workable through full afternoon for the first time since November; the summit Ucchi Pillayar Ganesha shrine and the Thayumanavar midway-temple at peak visitor density. The temple-circuit (Srirangam Ranganathaswamy world's-largest functioning temple, Jambukeswarar water-element Pancha Bhoota Stalam) at full ritual tempo. Navarathri tail and Dussehra (Vijayadasami, the tenth day, falls in early-to-mid October 2026) bring weapon-worship rituals and Devi processions. Trichy-Tanjore-Kumbakonam Cauvery-circuit day-trips return to year-best comfort. Stay central — Sangam Hotel ₹3-4,500, Femina ₹2,500-4k, Breeze Residency ₹2,200-3,500, homestays around ₹2,250. Tiruchirapalli International Airport at peak Diwali-NRI inbound traffic.$cst$::text WHERE destination_id||'/'||month = 'trichy/10';
UPDATE destination_months SET prose_lead = $cst$December is Kashid at annual peak. Temperatures hold 18-30°C — coolest of the year — with humidity in the 50s, the Arabian Sea glass-calm, and the 3km white-sand strip at year-best cleanliness and firmness. Water-sports run full 7am-6pm hours, Phansad WLS jeep safaris operational, Korlai Fort accessible. Christmas weekend (Dec 24-25) and NYE (Dec 31-Jan 1) drive Mumbai-Pune road-tripper traffic to year-peak. Heritage stays at year-high rates — Kashid Beach Resort ₹4500-8500/night, Hotel Sea Shell ₹3500-6000/night, private homestays around ₹2,450/night.$cst$::text WHERE destination_id||'/'||month = 'kashid/12';
COMMIT;
