/**
 * Outbound tours-&-activities link construction for <BookingHandoff>.
 *
 * Destination pages hand readers off to experience marketplaces for tours,
 * treks, safaris and day activities. These partners attribute on a 30-day
 * cookie, so they survive the research-to-booking gap.
 *
 * WE ONLY LINK WHERE THE PARTNER PROVABLY SELLS SOMETHING THERE.
 *
 * This used to build a free-text SEARCH url for every destination, on the
 * reasoning that a search "never 404s". Measured 2026-09-13, that reasoning was
 * backwards: for a destination a partner does not cover, the search does not
 * fail — it succeeds, confidently, with the wrong continent. GetYourGuide
 * answered "500+ results" for Mukteshwar, Chikmagalur and Ziro and served
 * activities in Urubamba, Muscat, Zurich and Tokyo. Hampi, which has real
 * supply, answered "24 results" with 10 of them in Hampi. A large result count
 * is therefore evidence of ABSENCE, not presence: it means the query fell
 * through to a global catalogue. Sending a reader looking for Ziro to a page
 * selling Zurich costs trust on our highest-traffic pages and earns nothing.
 *
 * So the link set is now an allowlist, not a formula:
 *
 *  1. data/experience-inventory.json — generated by
 *     `scripts/verify-experience-inventory.mjs`, which reads each partner's
 *     results and keeps a destination only when at least one bookable product
 *     sits in a location whose name matches it. It pins the partner's canonical
 *     location page, not a search.
 *  2. data/experience-link-overrides.json — the hand-verified layer, which wins
 *     over the generated file. Thrillophilia lives here only, having no usable
 *     url formula at all.
 *
 * A destination in neither file renders NO experience links, and
 * <BookingHandoff> drops the whole section. That is the correct answer.
 *
 * Links route through buildAffiliateUrl() so they auto-tag the moment the
 * Travelpayouts / Thrillophilia IDs land in env — see affiliate.ts.
 */

import { buildAffiliateUrl, type ExperiencePartner } from "./affiliate";
import overridesData from "../../data/experience-link-overrides.json";
import inventoryData from "../../data/experience-inventory.json";

export type ExperiencePlatform = ExperiencePartner;

export type ExperienceLink = {
  platform: ExperiencePlatform;
  name: string;
  url: string;
  /** Tailwind colour classes for the link pill. */
  color: string;
  /** Partner key for query-param affiliate tagging. */
  affiliate: ExperiencePartner;
};

type DestinationArg = {
  /** Destination id slug — the key for both the verified and override maps. */
  id?: string;
  name: string;
  state?: string;
};

type PartnerUrls = Partial<Record<ExperiencePlatform, string>>;

/** Underscore-prefixed keys in both JSON files are documentation, not data. */
const OVERRIDES = overridesData as unknown as Record<string, PartnerUrls>;
const INVENTORY = inventoryData as unknown as Record<string, PartnerUrls>;

const PRESENTATION: Record<ExperiencePlatform, { name: string; color: string }> = {
  viator: { name: "Viator", color: "text-sky-300 border-sky-500/30 hover:bg-sky-500/10" },
  getyourguide: { name: "GetYourGuide", color: "text-amber-300 border-amber-500/30 hover:bg-amber-500/10" },
  thrillophilia: { name: "Thrillophilia", color: "text-rose-300 border-rose-500/30 hover:bg-rose-500/10" },
};

/** Partner order is fixed so the pills do not reshuffle between destinations. */
const ORDER: ExperiencePlatform[] = ["viator", "getyourguide", "thrillophilia"];

/**
 * Builds the outbound tours-&-activities links for a destination.
 *
 * Returns an empty array when no partner is known to cover it — the common
 * case for offbeat destinations, and the honest one. Callers must handle empty.
 */
export function getExperienceLinks(dest: DestinationArg): ExperienceLink[] {
  if (!dest.id) return [];

  const verified = INVENTORY[dest.id] ?? {};
  const manual = OVERRIDES[dest.id] ?? {};

  return ORDER.flatMap((platform) => {
    // A hand-verified url beats a generated one; neither present means no link.
    const url = manual[platform] ?? verified[platform];
    if (!url) return [];
    return [{
      platform,
      name: PRESENTATION[platform].name,
      url: buildAffiliateUrl(platform, url),
      color: PRESENTATION[platform].color,
      affiliate: platform,
    }];
  });
}
