import { videoSrc } from "./video-url";
import { FESTIVAL_FOOTAGE, FOOTAGE_CREDIT } from "./festival-footage-map";

/**
 * Real-footage hero clips for /festivals/[festivalSlug].
 *
 * Each festival slug is mapped (in festival-footage-map.ts, auto-generated by
 * scripts/_gen-festival-footage-map.mjs) to a footage "family" — an authentic,
 * free-licensed clip of that festival TYPE, stored in R2 as fam-<family>.mp4
 * (one real Holi clip serves every Holi-named festival, etc.). Each clip was
 * verified frame-by-frame at source.
 *
 * A festival with no mapping falls back to the destination hero IMAGE on its
 * page — an honest still beats a clip that misreads as the festival.
 *
 * This replaces the former location-only "landscape B-roll" heroes, which
 * showed the host place (mountains / monsoon / fields) at the festival's time
 * of year and never the festival itself.
 */
export const hasFestivalHero = (slug: string): boolean => slug in FESTIVAL_FOOTAGE;

/** R2 real-footage hero-clip URL for a festival slug, or "" when none exists. */
export function festivalHeroSrc(slug: string): string {
  const family = FESTIVAL_FOOTAGE[slug];
  return family ? videoSrc(`fam-${family}`) : "";
}

/** Visible attribution for a festival hero clip (CC BY-SA families), or "". */
export function festivalHeroCredit(slug: string): string {
  const family = FESTIVAL_FOOTAGE[slug];
  return family ? FOOTAGE_CREDIT[family] ?? "" : "";
}
