import { videoSrc } from "./video-url";
import { FESTIVAL_FOOTAGE, FOOTAGE_CREDIT, FESTIVAL_PHOTO, PHOTO_CREDIT } from "./festival-footage-map";

// R2 image origin (same bucket family as destination images). Festival photos
// are stored as famphoto-<family>.jpg.
const IMAGE_BASE = "https://pub-d8970c901de34c218926ebf4be1ed09a.r2.dev";

/**
 * Real-footage hero clips for /festivals/[festivalSlug].
 *
 * Each festival slug is mapped (in festival-footage-map.ts, auto-generated by
 * scripts/_gen-festival-footage-map.mjs) to a footage "family" — an authentic,
 * free-licensed clip of that festival TYPE, stored in R2 as fam-<family>.mp4
 * (one real Holi clip serves every Holi-named festival, etc.). Each clip was
 * verified frame-by-frame at source.
 *
 * A festival with no mapping falls back to the destination hero IMAGE on its
 * page — an honest still beats a clip that misreads as the festival.
 *
 * This replaces the former location-only "landscape B-roll" heroes, which
 * showed the host place (mountains / monsoon / fields) at the festival's time
 * of year and never the festival itself.
 */
export const hasFestivalHero = (slug: string): boolean => slug in FESTIVAL_FOOTAGE;

/** R2 real-footage hero-clip URL for a festival slug, or "" when none exists. */
export function festivalHeroSrc(slug: string): string {
  const family = FESTIVAL_FOOTAGE[slug];
  return family ? videoSrc(`fam-${family}`) : "";
}

/** Visible attribution for a festival hero clip (CC BY-SA families), or "". */
export function festivalHeroCredit(slug: string): string {
  const family = FESTIVAL_FOOTAGE[slug];
  return family ? FOOTAGE_CREDIT[family] ?? "" : "";
}

/**
 * Real festival-CELEBRATION photo URL for a slug, or "" when none exists.
 * The hero fallback when there's no video: an honest still of the festival
 * itself, shown instead of the destination/place photo.
 */
export function festivalHeroPhotoSrc(slug: string): string {
  const family = FESTIVAL_PHOTO[slug];
  return family ? `${IMAGE_BASE}/festivals/famphoto-${family}.jpg` : "";
}

/** Visible attribution for a festival photo (CC BY-SA families), or "". */
export function festivalHeroPhotoCredit(slug: string): string {
  const family = FESTIVAL_PHOTO[slug];
  return family ? PHOTO_CREDIT[family] ?? "" : "";
}
