// Curated list of dest×month pages that get high GSC impressions but rank
// page 2 (positions 4-15). Internal-link funnel target — surfacing these on
// hubs (/explore, /where-to-go) builds keyword-matched anchors back to URLs
// that need a position bump from rank 8 → rank 3.
//
// Source: data/research/data-baseline-2026-05-09.md (GSC almost-page-1 set,
// 28d window). Refresh every 30-60d as the cohort shifts seasonally; the
// month filter below auto-hides stale rows once we cross into the next month.
//
// Anchor text mirrors the GSC query verbatim — that's the keyword we need
// the page to rank for. Don't invent prettier anchors; SEO leverage comes
// from the literal match.

export type HighImpressionPage = {
  destId: string;
  /** Month slug the page ranks for. */
  monthSlug:
    | "january" | "february" | "march" | "april" | "may" | "june"
    | "july" | "august" | "september" | "october" | "november" | "december";
  /** Visible link text. Mirror GSC query, drop the year for evergreen reuse. */
  anchor: string;
  /** Hover-tooltip + screen-reader context. The full search-intent phrase. */
  query: string;
  /** GSC avg position over the last 28d — informational only. */
  position: number;
  /** GSC impressions over the last 28d — informational only. */
  impressions: number;
  /** Link to the destination HUB (/destination/{id}) instead of the
   *  dest×month page. For pages whose GSC demand lands on the hub itself
   *  (e.g. "shrikhand mahadev weather"); monthSlug still controls WHICH
   *  month's rail cohort surfaces the entry. */
  hubOnly?: boolean;
};

// Sourced from data/research/data-baseline-2026-05-09.md "almost-page-1" set.
// Filtered to ≥75 impressions / position 5-12 (the leverage band where one
// position bump doubles clicks). All entries verified against destinations
// table 2026-05-09 — slugs match the dest×month route param.
// GENERATED by scripts/gen-high-impression-pages.mjs on 2026-09-13 from GSC
// 2026-08-14 → 2026-09-11 (28d), position 5-12, ≥75 impressions. Do not hand-edit;
// re-run the script (monthly, or when the weekly audit shows the cohort shifted).
// GENERATED by scripts/gen-high-impression-pages.mjs on 2026-09-13 from GSC
// 2026-08-14 → 2026-09-11 (28d), position 5-12, ≥75 impressions. Do not hand-edit;
// re-run the script (monthly, or when the weekly audit shows the cohort shifted).
export const HIGH_IMPRESSION_PAGES: HighImpressionPage[] = [
  { destId: "ahobilam", monthSlug: "august", anchor: "Ahobilam weather", query: "ahobilam weather", position: 8.9, impressions: 265 },
  { destId: "manali", monthSlug: "december", anchor: "Manali weather in December", query: "manali weather in december", position: 8.5, impressions: 944 },
  { destId: "mount-abu", monthSlug: "december", anchor: "Mount Abu in December", query: "mount abu in december", position: 8.1, impressions: 645 },
  { destId: "kalpa", monthSlug: "december", anchor: "Kalpa in December", query: "kalpa in december", position: 6.8, impressions: 311 },
  { destId: "chandratal", monthSlug: "december", anchor: "Chandratal in December", query: "chandratal in december", position: 7.2, impressions: 223 },
  { destId: "kukke-subramanya", monthSlug: "july", anchor: "Weather in Kukke Subramanya temple 10 days", query: "weather in kukke subramanya temple 10 days", position: 10.3, impressions: 872 },
  { destId: "landour", monthSlug: "july", anchor: "Landour monsoon season", query: "landour monsoon season", position: 8.7, impressions: 232 },
  { destId: "bhimtal", monthSlug: "july", anchor: "Bhimtal road conditions", query: "bhimtal road conditions", position: 7.5, impressions: 77 },
  { destId: "palitana", monthSlug: "june", anchor: "How many steps in Palitana jain temple", query: "how many steps in palitana jain temple", position: 8.2, impressions: 116 },
  { destId: "horsley-hills", monthSlug: "june", anchor: "Horsley Hills weather", query: "horsley hills weather", position: 9.4, impressions: 84 },
  { destId: "horsley-hills", monthSlug: "may", anchor: "Horsley Hills weather", query: "horsley hills weather", position: 9.9, impressions: 281 },
  { destId: "munnar", monthSlug: "november", anchor: "Climate in Munnar in November", query: "climate in munnar in november", position: 9.9, impressions: 353 },
  { destId: "kolkata", monthSlug: "november", anchor: "Weather in Kolkata in November", query: "weather in kolkata in november", position: 8.1, impressions: 336 },
  { destId: "kalpa", monthSlug: "november", anchor: "Kalpa in November", query: "kalpa in november", position: 8.9, impressions: 157 },
  { destId: "dalhousie", monthSlug: "november", anchor: "Dalhousie temperature in November", query: "dalhousie temperature in november", position: 9.1, impressions: 105 },
  { destId: "jog-falls", monthSlug: "november", anchor: "Jog Falls in November", query: "jog falls in november", position: 7, impressions: 84 },
  { destId: "belum-caves", monthSlug: "november", anchor: "Belum Caves weather", query: "belum caves weather", position: 8.7, impressions: 83 },
  { destId: "lonavala", monthSlug: "november", anchor: "Weather in Lonavala in November", query: "weather in lonavala in november", position: 6.8, impressions: 83 },
  { destId: "manali", monthSlug: "october", anchor: "Manali weather in October", query: "manali weather in october", position: 8.5, impressions: 5506 },
  { destId: "varanasi", monthSlug: "october", anchor: "Weather in Varanasi in October", query: "weather in varanasi in october", position: 8.3, impressions: 4220 },
  { destId: "munnar", monthSlug: "october", anchor: "Munnar weather in October", query: "munnar weather in october", position: 7.9, impressions: 1445 },
  { destId: "daringbadi", monthSlug: "october", anchor: "Daringbadi weather in October", query: "daringbadi weather in october", position: 8.6, impressions: 368 },
  { destId: "chail", monthSlug: "october", anchor: "Chail temperature in October", query: "chail temperature in october", position: 8.5, impressions: 367 },
  { destId: "agra", monthSlug: "october", anchor: "Agra in October", query: "agra in october", position: 7.5, impressions: 298 },
  { destId: "girnar", monthSlug: "october", anchor: "Palitana Girnar October season", query: "palitana girnar october season", position: 5.9, impressions: 295 },
  { destId: "dzukou-valley", monthSlug: "october", anchor: "Dzukou Valley in October", query: "dzukou valley in october", position: 10.4, impressions: 283 },
  { destId: "hanle", monthSlug: "october", anchor: "Hanle temperature in October", query: "hanle temperature in october", position: 8.4, impressions: 250 },
  { destId: "jibhi", monthSlug: "october", anchor: "Jibhi in October", query: "jibhi in october", position: 8.5, impressions: 186 },
  { destId: "gurez-valley", monthSlug: "october", anchor: "Gurez Valley temperature in October", query: "gurez valley temperature in october", position: 6.7, impressions: 162 },
  { destId: "alleppey", monthSlug: "october", anchor: "Alleppey in October", query: "alleppey in october", position: 9, impressions: 159 },
  { destId: "khajuraho", monthSlug: "october", anchor: "Khajuraho weather in October", query: "khajuraho weather in october", position: 7.2, impressions: 145 },
  { destId: "kolkata", monthSlug: "october", anchor: "Kolkata in October", query: "kolkata in october", position: 7.6, impressions: 97 },
  { destId: "aalo", monthSlug: "october", anchor: "On October 25th", query: "on october 25th", position: 7.5, impressions: 95 },
  { destId: "athirapally", monthSlug: "october", anchor: "Athirapally in October", query: "athirapally in october", position: 8.4, impressions: 80 },
  { destId: "morni-hills", monthSlug: "september", anchor: "Morni Hills india", query: "morni hills india", position: 8.3, impressions: 3350, hubOnly: true },
  { destId: "varkala", monthSlug: "september", anchor: "Varkala in September", query: "varkala in september", position: 8.5, impressions: 2853 },
  { destId: "shikharji", monthSlug: "september", anchor: "Shikharji", query: "shikharji", position: 7.4, impressions: 2175, hubOnly: true },
  { destId: "shrikhand-mahadev", monthSlug: "september", anchor: "Weather Shrikhand Mahadev", query: "weather shrikhand mahadev", position: 8.4, impressions: 1796, hubOnly: true },
  { destId: "kedarnath", monthSlug: "september", anchor: "Kedarnath weather in September", query: "kedarnath weather in september", position: 10.8, impressions: 1270 },
  { destId: "gandikota", monthSlug: "september", anchor: "Weather Gandikota", query: "weather gandikota", position: 9.7, impressions: 1174, hubOnly: true },
  { destId: "kiphire", monthSlug: "september", anchor: "Weather Kiphire", query: "weather kiphire", position: 9.6, impressions: 1165, hubOnly: true },
  { destId: "rishikesh", monthSlug: "september", anchor: "Rishikesh in September", query: "rishikesh in september", position: 8.8, impressions: 1045 },
  { destId: "barot-valley", monthSlug: "september", anchor: "Barot Valley in September", query: "barot valley in september", position: 5.6, impressions: 781 },
  { destId: "pangong-lake", monthSlug: "september", anchor: "Pangong in September", query: "pangong in september", position: 7.1, impressions: 717 },
  { destId: "almora", monthSlug: "september", anchor: "Almora weather in September", query: "almora weather in september", position: 7.2, impressions: 709 },
  { destId: "landour", monthSlug: "september", anchor: "Landour weather in September", query: "landour weather in september", position: 10.6, impressions: 640 },
  { destId: "jibhi", monthSlug: "september", anchor: "Jibhi in September", query: "jibhi in september", position: 6.1, impressions: 602 },
  { destId: "chandipur", monthSlug: "september", anchor: "Chandipur", query: "chandipur", position: 8.6, impressions: 371, hubOnly: true },
  { destId: "patnitop", monthSlug: "september", anchor: "Patnitop in September", query: "patnitop in september", position: 9.4, impressions: 349 },
  { destId: "anini", monthSlug: "september", anchor: "Anini weather in September", query: "anini weather in september", position: 5.1, impressions: 307 },
  { destId: "manikaran", monthSlug: "september", anchor: "Manikaran himachal pradesh", query: "manikaran himachal pradesh", position: 11.5, impressions: 284, hubOnly: true },
  { destId: "chitkul", monthSlug: "september", anchor: "Chitkul in September", query: "chitkul in september", position: 9.6, impressions: 268 },
  { destId: "dandeli", monthSlug: "september", anchor: "Dandeli weather in September", query: "dandeli weather in september", position: 7.5, impressions: 268 },
  { destId: "bhimbetka", monthSlug: "september", anchor: "Bhimbetka weather", query: "bhimbetka weather", position: 9.6, impressions: 256, hubOnly: true },
  { destId: "bekal", monthSlug: "september", anchor: "Bekal weather in September", query: "bekal weather in september", position: 6.9, impressions: 244 },
  { destId: "bhopal", monthSlug: "september", anchor: "\"taj-ul-masajid\" \"hamidia hospital\" \"walking distance\"", query: "\"taj-ul-masajid\" \"hamidia hospital\" \"walking distance\"", position: 7.7, impressions: 236, hubOnly: true },
  { destId: "sariska", monthSlug: "september", anchor: "Sariska in September", query: "sariska in september", position: 8, impressions: 235 },
  { destId: "munsiyari", monthSlug: "september", anchor: "Munsiyari in September", query: "munsiyari in september", position: 10.3, impressions: 224 },
  { destId: "vagamon", monthSlug: "september", anchor: "Vagamon in September", query: "vagamon in september", position: 6.9, impressions: 222 },
  { destId: "courtallam", monthSlug: "september", anchor: "Which is crowded during week ends old Courtallam or nee Courtallam", query: "which is crowded during week ends old courtallam or nee courtallam", position: 9.3, impressions: 218, hubOnly: true },
  { destId: "achabal", monthSlug: "september", anchor: "Verinag to Achabal distance", query: "verinag to achabal distance", position: 9.3, impressions: 216, hubOnly: true },
  { destId: "jampui-hills", monthSlug: "september", anchor: "Jampui Hills weather", query: "jampui hills weather", position: 12, impressions: 194, hubOnly: true },
  { destId: "kukke-subramanya", monthSlug: "september", anchor: "Kukke Subramanya weather in September", query: "kukke subramanya weather in september", position: 7.5, impressions: 166 },
  { destId: "khardung-la", monthSlug: "september", anchor: "Khardung La", query: "khardung la", position: 11.6, impressions: 153, hubOnly: true },
  { destId: "gurudongmar-lake", monthSlug: "september", anchor: "Gurudongmar Lake in September", query: "gurudongmar lake in september", position: 6.4, impressions: 123 },
  { destId: "tungnath", monthSlug: "september", anchor: "Mid sept", query: "mid sept", position: 9.1, impressions: 118 },
  { destId: "gulmarg", monthSlug: "september", anchor: "\"highlands park\" \"nedou's hotel\" Gulmarg distance", query: "\"highlands park\" \"nedou's hotel\" gulmarg distance", position: 7.5, impressions: 110, hubOnly: true },
  { destId: "kutch", monthSlug: "september", anchor: "Kutch in September", query: "kutch in september", position: 7, impressions: 108 },
  { destId: "harihareshwar", monthSlug: "september", anchor: "Harihareshwar beach weather", query: "harihareshwar beach weather", position: 9.2, impressions: 88, hubOnly: true },
  { destId: "dzukou-valley", monthSlug: "september", anchor: "Dzukou Valley weather in September", query: "dzukou valley weather in september", position: 11.4, impressions: 85 },
  { destId: "alibaug", monthSlug: "september", anchor: "Alibaug in September", query: "alibaug in september", position: 8.6, impressions: 83 },
  { destId: "diamond-triangle", monthSlug: "september", anchor: "Diamond Triangle", query: "diamond triangle", position: 9.7, impressions: 79, hubOnly: true },
];

/** Filter to the current-month cohort. Used by the rail component. */
export function pagesForMonth(monthSlug: HighImpressionPage["monthSlug"]): HighImpressionPage[] {
  return HIGH_IMPRESSION_PAGES.filter((p) => p.monthSlug === monthSlug);
}
