// Auto-generated by scripts/upload-videos.mjs — do not edit by hand.
// Bumped every time at least one video is uploaded or replaced on R2, so
// browsers with a cached copy of a replaced file re-fetch on next view.
//
// The value is a YYYYMMDD date stamp; collisions within the same day are
// fine since we only care that the cache key changes between replacement
// batches. Older clients see the new URL, old URL stays valid.
export const VIDEO_CACHE_VERSION = "20260424";
